### ISSUE TITLE
Spawning when use for calling `dmenu_run` is very slow

### ISSUE THREAD

**Issue by YoEight** [xmonad/xmonad#100]
Greetings.

### Problem Description

After selecting a program with `dmenu` with `mod+p`, that said program takes a lot of time to launch (about 10s). Why I'm blaming XMonad ? Because when I emulate this same behaviour within a regular terminal, it's instantaneous. Those programs are for example, `emacs`, `google-chrome`, `firefox`. Those programs were resetted to default to rule out configuration issues. Programs like `gedit` doesn't suffer from this. I say 'like' because I don't have an exhaustive application list on this machine as it's dedicated to programming only.

I have several machines running xmonad and that's the first time I stumbled upon this case. All my machines run Archlinux and work as expected. 
The problematic machine runs:

- Ubuntu 64bits 16.04.2 LTS
- XMonad 0.12 (the one provided by the package manager, with verbatim repository settings)
- It seems this version was built with GHC 7.10.3

### Configuration File

I can reproduce this behaviour with the simplest XMonad configuration ever, as described below.

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [*] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [*] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

Thanks for your time.

**Comment by pjones** [comment]
Try using `dmenu_run` from the terminal add see what sort of delay you experience.

It's not very likely that this has anything to do with xmonad.

**Comment by YoEight** [comment]
@pjones 

> Why I'm blaming XMonad ? Because when I emulate this same behaviour within a regular terminal, it's instantaneous.

So as stated in the description, when I run in a terminal:

```
$ dmenu_run
```
Then enter `emacs` or `google-chrome`, the program pops out right away.

**Comment by YoEight** [comment]
I tried the following to confirm that `spawn` was the issue here (and has nothing to do with `dmenu`)

```haskell
module Main (main) where

import XMonad

anotherKeys :: [((KeyMask, KeySym), X ())]
anotherKeys = [ ((mod4Mask, xK_s), spawn "xscreensaver-command --lock") ]

main :: IO ()
main = xmonad (def `additionalKeys` anotherKeys)
```

`xscreensaver-command --lock` took about 10s to start, the same command started immediately in the terminal.

**Comment by geekosaur** [comment]
Is there something about your system that would make `fork()` unusually expensive? Because the only things `spawn` does are two `fork()`s and an `exec()` of `/bin/sh`.

**Comment by pjones** [comment]
Also try running the following from a terminal:  

```
/bin/sh -c xscreensaver-command --lock
```

**Comment by YoEight** [comment]
@geekosaur 

If there is something then I'm not aware about it. If by any mean, you have something able to detect if `fork()` or `exec()` take too much time on my machine, I'll gladly test it out.

@pjones 

I did it and the program is started right away.

--

Thanks for your help.

**Comment by NeQuissimus** [comment]
I have this and `dmenu_run` is near-instant:

```
myKeys conf@(XConfig {XMonad.modMask = modm}) = M.fromList $ [
...
  (modm, xK_d), spawn "/nix/store/b5a3bs087cm2qg616cbrzd0wx4jk61ij-dmenu-4.6/bin/dmenu_run")
...
]
```

**Comment by YoEight** [comment]
Out of curiosity, I wiped my home directory. It did fix my issue. So I'm assuming there were some unity configuration messing up my beloved xmonad setup.

Thanks for your help.
