### ISSUE TITLE
Advise people to use `XMonad.Util.Ungrab.unGrab` when `spawn` makes `scrot --select` fail.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#101]
### Problem Description

`spawn "scrot --select filename.png"` fails because spawn doesn't release its grab on keyboard.
`scrot --select` needs the keyboard to work.

**Comment by geekosaur** [comment]
`unGrab` should really be merged to either `XMonad.Core` or `XMonad.Operations`. But yes, if nothing else this should be a FAQ.

**Comment by liskin** [comment]
+1 on moving unGrab to `XMonad.Operations`

**Comment by iogrt** [comment]
Hello, I tried tackling this without causing xmonad-contrib to break. But unfortunately `xmonad-contrib` itself uses ungrab in the `XMonad.Config.Mate` module and will have an ambiguous reference error if not updated.

What's the course of action then? Are both packages released at the same date making it trivial to just make the necessary changes in `xmonad-contrib` aswell?

I'm also unsure as to where to add the relevant documentation.

**Comment by geekosaur** [comment]
You're missing a step: have `XMonad.Util.Ungrab` re-export `unGrab` from `XMonad.Operations` for backward compatibility.

`xmonad-contrib` can be released without `xmonad`, but an `xmonad` release always comes with an `xmonad-contrib` release, so there is no problem.

**Comment by geekosaur** [comment]
To be more clear: we have a deprecation policy, so if this is released with xmonad 0.18 then `XMonad.Util.Ungrab` should remain with a `DEPRECATED` pragma until (IIRC) 0.20. People kinda don't like their configs breaking with no warning; they expect xmonad to be set-and-forget,
