### ISSUE TITLE
XMonad.Core.recompile doesn't handle build script properly.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#102]
I started using a build script because `/usr/bin/xmonad` couldn't import time package on its own.
I had to turn `~/.xmonad` into a stack or cabal project directory so that my xmonad configuration has access to `time` modules.

### Problem Description

~/.xmonad/build

```
#!/bin/sh -eu

EXE_NAME=xmonad-exec
OUTPUT=$1

stack build
cp -u `stack path --dist-dir`/build/$EXE_NAME/$EXE_NAME $OUTPUT
```

When I press Mod+q to recompile and restart XMonad, I see the following errors.

```
Error detected while loading xmonad configuration file: /home/guardian/.xmonad/xmonad.hs
my-xmonad-conf-0.0.0: unregistering (local file changes: xmonad.hs)
my-xmonad-conf-0.0.0: build (lib + exe)
Preprocessing library my-xmonad-conf-0.0.0...
Preprocessing executable 'xmonad-exec' for my-xmonad-conf-0.0.0...
[1 of 1] Compiling Main             ( xmonad.hs, .stack-work/dist/x86_64-linux-ncurses6/Cabal-1.24.2.0/build/xmonad-exec/xmonad-exec-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux-ncurses6/Cabal-1.24.2.0/build/xmonad-exec/xmonad-exec ...
my-xmonad-conf-0.0.0: copy/register
Installing library in
/home/guardian/.xmonad/.stack-work/install/x86_64-linux-ncurses6/lts-8.12/8.0.2/lib/x86_64-linux-ghc-8.0.2/my-xmonad-conf-0.0.0-8nPXW84KMRtC7tbNBwzyZ5
Installing executable(s) in
/home/guardian/.xmonad/.stack-work/install/x86_64-linux-ncurses6/lts-8.12/8.0.2/bin
Registering my-xmonad-conf-0.0.0...
cp: cannot create regular file '/home/guardian/.xmonad/xmonad-x86_64-linux': Text file busy

Please check the file for errors.
```

This happens because XMonad.Core.recompile doesn't kill the process launched from `xmonad-x86_64-linux` before build script is executed.

The relevant part is https://github.com/xmonad/xmonad/blob/master/src/XMonad/Core.hs#L587-L633

**Comment by crocket** [comment]
I think I found the fix.

The build script examples in xmonad-testing have bugs.

1. `mv` causes errors if I execute `xmonad --recompile` without changing the configuration files because the build result was already displaced by `mv` in previous runs.
2. `cp -u` causes errors because it doesn't forcefully replace `~/.xmonad/xmonad-x86_64-linux` while it is used by a process.

The answer is to use `cp -uf` in build scripts.
I think you should update build script examples in xmonad-testing.

I think `cp -u $(stack path --dist-dir)/build/$EXE_NAME/$EXE_NAME $OUTPUT` is difficult to understand and easy to break.

I recommend using `cp -uf $(stack exec which $EXE_NAME) $OUTPUT` in build script examples in xmonad-testing because it is easier to understand and more resistant to future directory layout changes.

Let `--force` guide you.

**Comment by pjones** [comment]
@crocket Thanks for tracking this down.  Please submit a pull request to xmonad-testing with your changes.

**Comment by colonelpanic8** [comment]
> I recommend using cp -uf $(stack exec which $EXE_NAME) $OUTPUT in build script examples in xmonad-testing because it is easier to understand and more resistant to future directory layout changes.

agreed. $(stack path --dist-dir)/build/$EXE_NAME/$EXE_NAME actually doesn't work for me already!

**Comment by mgsloan** [comment]
I've made a PR to xmonad-testing addressing this issue - https://github.com/xmonad/xmonad-testing/pull/12

**Comment by crocket** [comment]
I think the proper way to handle this is to turn my xmonad setup into its own linux distribution package.
