### ISSUE TITLE
Can I add decoration to floating windows?

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#109]
### Problem Description

Since I set `FocusFollowsMouse` to True and `borderWidth` to 0, I often find myself pressing `q` to close a floating `mpv` window when it is not in focus.

I prefer `NoFrillsDecoration` to XMonad default border, but NoFrillsDecoration is not applied to floating windows.

### Configuration File

```haskell
import XMonad
-- xmonad-contrib
import XMonad.Util.Run (spawnPipe)
import XMonad.Hooks.ManageDocks (docks, avoidStruts)
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.EwmhDesktops (ewmh, fullscreenEventHook)
import XMonad.Layout.NoFrillsDecoration
import XMonad.Layout.Spacing
import XMonad.Layout.Tabbed (tabbed)
import XMonad.Layout.Renamed (renamed, Rename(Replace, CutWordsLeft))
import XMonad.Util.NamedScratchpad
-- my lib
import qualified XMonad.MyTheme as T

main :: IO ()
main = do
  xmproc <- spawnPipe "xmobar"
  xmonad $ ewmh $ docks def
    { terminal = "st tmux new-session -A -D -s main"
    , modMask = myModMask
    , borderWidth = 0
    , workspaces = ["MAIN", "DRAW", "LANG"]
    , layoutHook = avoidStruts $ addTopBar $
      (renamed [Replace "Tall"] $ smartSpacing 7 $ Tall 1 (3/100) (1/2)) |||
      (renamed [Replace "Tabbed"] $ tabbed shrinkText T.tabs)
    , logHook = dynamicLogWithPP . namedScratchpadFilterOutWorkspacePP $
                xmobarPP
                { ppOutput = hPutStrLn xmproc
                , ppTitle = xmobarColor "#d1f442" "" . shorten 50
                }
    , focusFollowsMouse = True
    , clickJustFocuses = False
    , handleEventHook = handleEventHook def <+> fullscreenEventHook
    , manageHook =  myManageHook <+> namedScratchpadManageHook scratchpads
    , startupHook = spawn "compton"
    }

-- Layout elements
addTopBar = renamed [CutWordsLeft 1] . noFrillsDeco shrinkText T.topBar
```

**Comment by geekosaur** [comment]
Anything that is part of a layout does not get applied to floating windows. Although there are hacky ways around this, such as the `SimpleFloat` layout which captures a tiled window, applies a `Decoration`, and then floats the result. (But this won't work for windows that are floated by xmonad itself, such as windows which declare a fixed size via `WM_NORMAL_HINTS` or which have `WM_TRANSIENT_FOR` set.)

Floating windows are, in general, handled very poorly. I have notes somewhere about extending layouts to support them (and a few other things like EWMH layers) better, but it would be a fair amount of work and supporting the aforementioned special cases would be a breaking change to both `ManageHook`s and `Layout`s.

**Comment by crocket** [comment]
I somehow found a way to add a border 2 pixels wide only to floating windows that don't span entire screen. I'll show you how.

```haskell
import XMonad
-- xmonad-contrib
import XMonad.Hooks.ManageDocks (docks, avoidStruts)
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.EwmhDesktops (ewmh, fullscreenEventHook)
import XMonad.Layout.NoFrillsDecoration
import XMonad.Layout.Spacing
import XMonad.Layout.Tabbed (tabbed)
import qualified XMonad.Layout.NoBorders as NB
import XMonad.Layout.Renamed (renamed, Rename(Replace, CutWordsLeft))
import XMonad.Util.NamedScratchpad
import XMonad.Util.Run (spawnPipe)
-- my lib
import qualified XMonad.MyTheme as T

myModMask :: KeyMask
myModMask = mod4Mask

main :: IO ()
main = do
  xmproc <- spawnPipe "xmobar"
  xmonad $ ewmh $ docks def
    { terminal = "st tmux new-session -A -D -s main"
    , modMask = myModMask
    , borderWidth = 2
    , normalBorderColor = T.base03
    , focusedBorderColor = T.active
    , workspaces = ["MAIN", "DRAW", "LANG"]
    , layoutHook = avoidStruts $ addTopBar $
      NB.lessBorders NB.OnlyFloat $ NB.noBorders $
      (renamed [Replace "Tall"] $ smartSpacing 7 $ Tall 1 (3/100) (1/2)) |||
      (renamed [Replace "Tabbed"] $ tabbed shrinkText T.tabs)
    , logHook = dynamicLogWithPP . namedScratchpadFilterOutWorkspacePP $
                xmobarPP
                { ppOutput = hPutStrLn xmproc
                , ppTitle = xmobarColor "#d1f442" "" . shorten 50
                }
    , focusFollowsMouse = True
    , clickJustFocuses = False
    , handleEventHook = handleEventHook def <+> fullscreenEventHook
    , manageHook =  myManageHook <+> namedScratchpadManageHook scratchpads
    , startupHook = spawn "compton"
    }

-- Layout elements
addTopBar = renamed [CutWordsLeft 1] . noFrillsDeco shrinkText T.topBar
```

The important part is `NB.lessBorders NB.OnlyFloat $ NB.noBorders`.

`NB.noBorders` is applied to tiled windows, but not to floating windows. Thus, only floating windows get borders. Tiled windows are decorated only by NoFrillsDecoration.

`NB.lessBorders NB.OnlyFloat` removes borders from floating windows that span entire screen.

I think this can be documented in something like a cook book.

**Comment by crocket** [comment]
I just realized that the size of fullscreen floating window doesn't account for borders.
With borders 2 pixels wide, a fullscreen floating window bleeds into the next screens by border widths.

It seems I need to read https://funktionaali.com/posts/2014-07-01-How%20to%20get%20XMonad%20play%20well%20with%20fullscreen%20mpv.html

I'll report again after reading that article.

**Comment by crocket** [comment]
I'm closing this issue because the actual issue I want to solve is something else.
