### ISSUE TITLE
How do I retrieve an exitcode from spawned process?

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#113]
### Problem Description

I want to check whether tmux server is running.
To do so, I can check the exit code of `tmux ls`. I do not know any other reliable way of checking the presence of tmux server.
However, since XMonad ignores SIGCHLD, `waitForProcess` throws an exception instead of returning exitcode.

**Comment by geekosaur** [comment]
You'll want to look at the implementation of `XMonad.Util.Run`. _Not_ the actual exported functions; it doesn't export anything that exposes an exit status, sadly. But the code shows how you disable and re-enable the `SIGCHLD` handling.

Onw warning si that you should make sure whatever you run blocks for only a very short time, or arrange to handle it by running in a thread and reporting the result back to the main loop as a `ClientMessage` that you can receive in `handleEventHook`. Blocking the window manager is a bad idea --- and a worse one if what you're blocking on opens a managed window (not that you are doing that here, I think).

**Comment by crocket** [comment]
`tmux ls` blocks for a short amount of time, but I wouldn't count on it.
Sending a `ClientMessage` makes it complicated to check an exitcode.
It seems I need to look for something other than exitcode.

**Comment by geekosaur** [comment]
Actually I seem to have mispointed you as that module doesn't actually use what you need :(

As long as it's not blocking for very long, you can use http://hackage.haskell.org/package/xmonad-0.13/docs/XMonad-Core.html#v:uninstallSignalHandlers to disable the SIGCHLD handler, then http://hackage.haskell.org/package/xmonad-0.13/docs/XMonad-Core.html#v:installSignalHandlers to reinstall them. The main problems are waiting too long, and something else exiting while you are wating (I'm not sure what will happen but I suspect a small memory leak in the ghc runtime because it holds the exit record for something else that will never collect it).

**Comment by crocket** [comment]
Using uninstallSignalHandlers and installSignalHandlers feels wrong.
I think a racing condition could occur if something else calls installSignalHandlers right after uninstallSignalHandlers is called although such a racing condition would normally not occur without deliberate efforts.
As you said, it could also lead to small memory leaks.

**Comment by geekosaur** [comment]
It's the normal way to do it, though. xmonad is fairly low level, which makes it lightweight but means all the sharp edges of things like the raw POSIX APIs are visible. And the POSIX process control APIs have lots of annoyingly sharp edges. :/

**Comment by crocket** [comment]
I ended up wrapping a shell script in a function.

```haskell
module XMonad.ExitCode where

import XMonad.Core (X)
import XMonad.Util.Run (runProcessWithInput)
import Text.Printf

type Cmd = String
exitSuccess :: Cmd -> X (Either String Bool)
exitSuccess cmd = do
  let silence = (++" >/dev/null 2>&1")
      getExitCode =
        printf "if %s; then echo -n yes; else echo -n no; fi" . silence
  output <- runProcessWithInput "sh" ["-c",  getExitCode cmd] ""
  case output of
    "yes" -> return $ Right True
    "no" -> return $ Right False
    _ -> return $ Left output
```

With this, I don't have to worry about signal handlers. Actually, I use POSIX shell script a lot in my xmonad configuration. I write mini shell script compilers. I know it's a hack. I just haven't found better solutions.
