### ISSUE TITLE
Failing to build with ghc8/gcc7 on archlinux

### ISSUE THREAD

**Issue by fommil** [xmonad/xmonad#119]
I stripped my haskell install down to the bare minimum ghc / cabal-install and `cabal install xmonad` gives me ld linker errors.

Archlinux recently upgraded ghc and they could have messed something up... but I'm able to build other packages with cabal so this could be isolated to xmonad.

Sorry, I don't currently have access to x11 to copy paste anything into a browser (on my phone now). Attaching an image of the screen.

**Comment by fommil** [comment]
![14982569527192064428962](https://user-images.githubusercontent.com/1914041/27502426-dcf9a266-586b-11e7-898d-6134f3f9ef8e.jpg)

**Comment by fommil** [comment]
FWIW all those libs do exist under subdirectories of /usr/lib/ghc-8.0.2 but have -ghc8.0.2.so suffixes.

**Comment by fommil** [comment]
And if I create symbolic links without these suffixes, it starts to compile again... is it possible that xmonad's build needs to account for these suffixes or is this an archlinux bug?

**Comment by fommil** [comment]
Bug on archlinux side https://bugs.archlinux.org/task/54561

**Comment by geekosaur** [comment]
Yes, this is Arch's fault, they package a ghc configured to link Haskell libraries statically but the xmonad and xmonad-contrib packages (on AUR, at least) explicitly remove the static libraries.

**Comment by fommil** [comment]
Ok, so arch's ghc is broken?

I'm building this github master branch of xmonad and it fails.

There is a proposed patch to xmonad in the linked ticket, does it look sensible to you?

**Comment by fommil** [comment]
Their patch makes no difference to compile failures of xmonad.

**Comment by geekosaur** [comment]
Either arch's ghc should be configured for dynamic by default, or the xmonad and xmonad-contrib (and quite possibly other Haskell library) packages should not delete the static libraries (see end of https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xmonad-git). We are not the Arch maintainers, so it's up to them to sort out.

The shared objects deliberately have the additional version information on them because ghc has rather specific binary versioning constraints on its libraries; this is generally not relevant with static linking, but dynamic libraries need to also match at runtime.

**Comment by fommil** [comment]
thanks. I managed to reinstall the arch-built xmonad package and manually trigger a dynamic recompile. Hopefully they can fix this.

**Comment by fommil** [comment]
FYI this is the "stable" build, also deleting static binaries https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/xmonad

I'm surprised they are doing this, I thought the whole point was to compile into a single binary :confused: 

I do wonder if perhaps the xmonad recompile script could benefit from logic to keep the old binary around and swap it in if linking fails... this is a rather bad failure mode.

**Comment by geekosaur** [comment]
So it sounds like it's a more general Arch problem and also affecting cabal-install (and a report on IRC #haskell suggests also affecting stack).

**Comment by fommil** [comment]
This is what happens when package managers try to repackage things that have been packaged properly by the authors / community in the first place. Also see the jvm world.

**Comment by toZen** [comment]
xmonad 0.13-3 just released on archlinux.org
Problem sorted

**Comment by fommil** [comment]
I think I'm going to set up stack... I don't think I want to trust `pacman` anymore to manage haskell builds.

**Comment by f1u77y** [comment]
@fommil ArchHaskell still works fine. Just don't use [community] for Haskell packages.

**Comment by ikyp** [comment]
Download `stack`, and install `xmonad` from `stack`

1.  Download binary `stack` and installed.
2.  Use `stack steup` 
3.  `stack update` and `stack install xmonad`

All done.

Then , edit yourself `.xmonad` file to use.

Easy way.


## Attention:

Before you install `stack`, Delete your installed `cabal-install` and `ghc` with `pacman`.

Only install binary `stack` & use `stack`.

**Comment by fommil** [comment]
These instructions are incorrect. They broke too on Arch. See my dotfiles for the correct instructions including a build script in .xmonad.
