### ISSUE TITLE
Arch Linux 

### ISSUE THREAD

**Issue by kasrasadeghi** [xmonad/xmonad#121]
### Problem Description

If I install xmonad on Arch Linux, it doesn't link properly.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
import XMonad

main :: IO ()
main = xmonad defaultConfig { ... }
```

See [this pastebin](https://pastebin.com/5JpcpTQf).

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
Arch's ghc 8.0.2 is broken. We can't fix it.
