### ISSUE TITLE
[question] Remapping Mode_switch+left_mouse_drag to Alt+left_mouse_drag

### ISSUE THREAD

**Issue by amosbird** [xmonad/xmonad#122]
Hi, is it possible to only remap the Mode_switch+left_mouse_drag to Alt+left_mouse_drag in xmonad? I've changed my right alt key to mode_switch and the left click button of touchpad is on the left side of the keyboard. So alt dragging is hard to be done.

**Comment by geekosaur** [comment]
You can specify the modifier(s) to use in the `mouseBindings`. But you seem to have already configured something oddly, we don't normally use `Mode_switch` as the "master" modifier key --- the usual choices are the default `mod1Mask` aka `Alt` and `mod4Mask` aka `Super`.
