### ISSUE TITLE
Set _JAVA_AWT_WM_NONREPARENTING when starting

### ISSUE THREAD

**Issue by plexus** [xmonad/xmonad#126]
### Problem Description

Java Swing GUI applications are known to misbehave under XMonad and other non-reparenting window managers, the result being a blank window.

The reason is that AWT contains a hard coded list of window managers

``` java
static boolean isNonReparentingWM() {
    return (XWM.getWMID() == XWM.COMPIZ_WM || XWM.getWMID() == XWM.LG3D_WM || XWM.getWMID() == XWM.CWM_WM);
}
```

People run into this, google around and learn that there's a workaround by setting `wmname LG3D`, in other words making Java think you're running the Looking Glass 3D desktop.

Some distributions have patched JDK to check for a `_JAVA_AWT_WM_NONREPARENTING` environment variable. From JDK 9 this is being incorporated upstream, so it's now the officially supported way for a window manager to communicate to Java that it is non-reparenting. See https://bugs.openjdk.java.net/browse/JDK-8058197

If XMonad could set this automatically so that it's inherited by child processes it would mean Swing/AWT apps finally work out of the box, potentially saving future users a lot of frustration.

**Comment by liskin** [comment]
Setting wm name to `LG3D` unfortunately breaks Chrome/Chromium's WM detection and results in glitches when moving tabs.
Setting `_JAVA_AWT_WM_NONREPARENTING` only works if all apps are spawned from `xmonad` itself, but some people spawn apps from their GNOME/KDE/Mate/whatever sessions that don't run as children of xmonad.

What I'm trying to say is: there is no single standard way of doing this that just works, and we're better off keeping the core minimal and letting people use what works in their setups. In https://github.com/xmonad/xmonad-contrib/pull/464 we added/documented one of these hacks into xmonad-contrib to make it easier to find/use. If anyone believes it should be easier to find, feel free to submit a PR that updates some documentation, website, or whatever is best.
