### ISSUE TITLE
XMonad Maintainers.md Core Team List Github URLs broken

### ISSUE THREAD

**Issue by madnight** [xmonad/xmonad#130]
### Problem Description

Describe the problem you are having, what you expect to happen
instead, and how to reproduce the problem.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
This was fixed by https://github.com/xmonad/xmonad/commit/b59c768cdd96694226b85118b91002e295cfde56
