### ISSUE TITLE
The default exported bitwise operators in module XMonad

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad#131]
### Problem Description
When I was trying to perform bitwise AND, I found out that the module XMonad only exports (.|.) but not the other bitwise operators (like bitwise AND).
I think the common bitwise operators from Data.Bits should also be exported. (But perhaps not all of them). Since the bitwise OR operator is exported, I would expect the other common bitwise operators to be exported from the same module.

### Checklist

  - [*] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
I'd be wary of exporting more symbols from `XMonad`, especially stuff that few people need and can easily be imported explicitly. Let me just close this for now. If you do believe this should indeed be exported, and can convince us that it's a good idea, feel free to open a PR.
