### ISSUE TITLE
When a floating window disappears, the focus goes to the last tiled window.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#138]
### Problem Description

When a floating window disappears, the focus goes to the last tiled window instead of the lastly focused tiled window.

This is problematic when a floating dialog window pops up or when I use a scratchpad.

I want the focus to go back to the lastly focused tiled window when I close or hide a floating window.

**Comment by namo626** [comment]
I also have the same problem when using tabbed layout. Perhaps a hook can be used to focus the most recent window in history after closing the floating one.

**Comment by LSLeary** [comment]
@crocket @namo626 I happen to have written such functionality recently, see xmonad/xmonad-contrib#256. Though I'm not distinguishing between floating and tiled windows. There's a simple bug to fix, so when I do that I'll also look into a float-only version, or perhaps a more general one to which you supply a `Window -> X Bool `.

**Comment by crocket** [comment]
Can I consider this fixed? RefocusLast module was merged into xmonad-contrib last year.

**Comment by slotThe** [comment]
Definitely fixed, yes
