### ISSUE TITLE
Need easy HiDPI support (or at least documentation)

### ISSUE THREAD

**Issue by heyakyra** [xmonad/xmonad#140]
### Problem Description

Everything is illegibly small on hidpi screens.

### Configuration File

defaults

### Checklist

  - [ ✓ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [   ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by MichielDerhaeg** [comment]
XMonad's responsibilities are nowhere near managing HiDPI scaling. I understand why you might think it might be as desktop environments usually configure this for you. I suggest configuring .Xresources to set your DPI, as most GUI toolkits like Qt and GTK try to respect these settings as much as possible. Take a look at [this article](https://wiki.archlinux.org/index.php/HiDPI#X_Resources) from the Arch Wiki. Sometimes scaling issues are resolved by simply increasing the font size, like in urxvt.

**Comment by heyakyra** [comment]
Thank you for the link to arch wiki's article. I did go to the IRC channel and now understand that the scaling doesn't make sense to be handled by xmonad. It would be good to at least link to the arch wiki from the xmonad faq and/or other documentation on the website.

**Comment by colonelpanic8** [comment]
Close this issue?

**Comment by MichielDerhaeg** [comment]
Sure, close it.
