### ISSUE TITLE
st crashing immediately (Error in function getWindowAttributes)

### ISSUE THREAD

**Issue by annacrombie** [xmonad/xmonad#150]
### Problem Description

I'm running xmonad 0.13, with a fresh gentoo, and I have no other wm/desktop environment installed.

Recently, when I open st strange behavior occurs.  Usually the window opens for a second, then exits.  Somtimes it will open and show my prompt but if I enter any keys into the program it will exit.  Other times it will just be a black screen.  The only way I can get a usable terminal is to hold down the shortcut for terminal and create about 20 windows.  Most just vanish immediately and others exhibit the other behaviors mentioned, however a few will be usable and normal and I don't experience any other problems with these windows.  I haven't noticed this problem with any other programs.

I always start xmonad with `startx` and when I switch back to the virtual console using ctrl-alt-f1, there are lots of errors, all more or less this:
```
user error (Error in function getWindowAttributes)
X Error of failed request: BadWindow (invalid Window parameter)
  Major opcode of failed request: 25 (X_SendEvent)
  Resource id of failed request: 0x1e00007
  Serial number of failed request: 700
  Current serial number in output stream: 700
```

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
import XMonad
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.ManageDocks

setWallpaper = spawn "/home/lattis/.fehbg"
xmobar'      = spawn "/home/lattis/.cabal/bin/xmobar"

main = do
  setWallpaper
  xmproc <- xmobar'
  xmonad $ docks defaultConfig
      { manageHook = manageDocks <+> manageHook defaultConfig
      , layoutHook = avoidStruts  $  layoutHook defaultConfig
      , modMask = mod4Mask
      , terminal = "st"
      }
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
Known issue, see xmonad-contrib/#146 and https://github.com/xmonad/X11/issues/51. Tracking and fixing these is a PITA.
