### ISSUE TITLE
xmonad fails to start

### ISSUE THREAD

**Issue by su8** [xmonad/xmonad#159]
Just rebooted my pc and xmonad refuses to start, log from xmonad.errors: [xmonad.txt](https://github.com/xmonad/xmonad/files/1866843/xmonad.txt)

**Comment by MichielDerhaeg** [comment]
This looks like you've upgraded GHC or GCC and lost ABI compatability along the way. I don't think this issue is caused by xmonad in any way. Try clearing any build biproducts in ~/.xmonad and try again.

What distro are you using?

**Comment by su8** [comment]
None of those packages was recently upgraded on my system. I'm using Gentoo. And I've tried to clean the **.o** and **.hi** files.

```bash
~ > compiletime gcc
gcc-4.8.4: Sat Aug 29 02:11:33 2015: 32 minutes, 2 seconds
gcc-4.8.5: Mon Aug 31 00:06:08 2015: 40 minutes, 22 seconds
gcc-4.9.3: Thu Mar  3 19:09:29 2016: 37 minutes, 26 seconds
gcc-4.9.3: Sat Mar  5 16:59:47 2016: 42 minutes, 8 seconds
gcc-4.9.3: Sat Mar  5 17:52:55 2016: 42 minutes, 53 seconds
gcc-4.9.3: Sun Mar  6 13:30:04 2016: 42 minutes, 25 seconds
gcc-4.9.3: Sun Mar 13 07:48:49 2016: 46 minutes, 45 seconds
gcc-4.9.3: Mon May  9 12:17:05 2016: 44 minutes, 13 seconds
gcc-4.9.3: Wed Jun 22 13:40:08 2016: 43 minutes, 17 seconds
gcc-4.9.3: Tue Jul  5 18:33:45 2016: 33 minutes, 18 seconds
gcc-4.9.3: Wed Jul  6 02:25:04 2016: 35 minutes, 1 second
gcc-4.9.3: Wed Jul  6 12:51:10 2016: 36 minutes, 33 seconds
gcc-4.9.3: Wed Jul  6 20:28:03 2016: 32 minutes, 22 seconds
gcc-5.4.0-r3: Wed Jun  7 12:16:22 2017: 1 hour, 5 minutes, 5 seconds
gcc-5.4.0-r3: Wed Sep 27 23:35:20 2017: 50 minutes, 24 seconds
gcc-6.4.0-r1: Mon Feb 26 17:17:53 2018: 1 hour, 24 seconds
gcc: 16 times
~ > compiletime ghc
ghc-7.6.3-r1: Sat Aug 29 03:22:18 2015: 46 minutes, 23 seconds
ghc-7.6.3-r1: Mon Aug 31 07:32:14 2015: 1 hour, 2 minutes, 10 seconds
ghc-7.8.4: Thu Mar  3 19:49:35 2016: 52 minutes, 33 seconds
ghc-7.8.4: Sun Mar 13 10:14:49 2016: 56 minutes, 27 seconds
ghc-7.10.3: Sun May 15 21:20:01 2016: 1 hour, 43 minutes, 50 seconds
ghc-7.10.3: Wed Jul  6 10:09:00 2016: 1 hour, 9 minutes, 38 seconds
ghc-7.10.3: Thu Jul  7 03:36:59 2016: 1 hour, 7 minutes, 15 seconds
ghc-7.10.3: Mon Sep 26 16:58:38 2016: 1 hour, 17 minutes, 45 seconds
ghc-7.10.3: Sun Dec  4 20:07:09 2016: 1 hour, 10 minutes, 20 seconds
ghc-8.0.2: Wed Sep 27 13:59:49 2017: 2 hours, 5 minutes, 12 seconds
ghc: 10 times
```

**Comment by su8** [comment]
Do I need to add -fPIC to my **make.conf** and recompile ghc and xmonad + xmonad contrib ?

**Comment by su8** [comment]
Switched to gcc 5.4.0 and it re-compiles without any issues, but I've been running xmonad on gcc 6.4.0 from one month up until yesterday. Closing this issue as it's solved, thanks for pointing gcc as it reminded me that I have several versions installed.

```bash
sudo gcc-config -l

#  [1] x86_64-pc-linux-gnu-5.4.0
#  [2] x86_64-pc-linux-gnu-6.4.0 *

# followed by

sudo gcc-config x86_64-pc-linux-gnu-5.4.0
```

**Comment by MichielDerhaeg** [comment]
I see, this issue is probably caused by the fact that GCC 6.4 on Gentoo now compiles with position independant executables by default. If you wanna start using the new version you probably need to recompile your entire system to prevent linker issues like this.

I suggest you read this: https://www.gentoo.org/support/news-items/2017-11-30-new-17-profiles.html

**Comment by su8** [comment]
@MichielDerhaeg Can you ping me back with "@su8 ping" ? I need at least one notification to add a new github notification support option to https://github.com/su8/pinky-bar

Sorry for the off-topic
