### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by MichielDerhaeg** [xmonad/xmonad#161]
I would like to see if there is some consensus on whether or not we should be doing a new release anytime soon. In light of the `xmonad.state` bug and the advent of GHC 8.4 I believe it would be desirable to have a new release so not to cause any unnecessary issues for distro maintainers.

**Comment by d3adb5** [comment]
A minor release to include the problematic `xmonad.state` bug would be welcome.

**Comment by arrowd** [comment]
FreeBSD is going to update GHC to 8.4 soon, so it would be great to have new xmonad release.

**Comment by asr** [comment]
I would appreciate a release supporting GHC 8.4.2.

**Comment by LeifW** [comment]
Arch Linux's GHC package is 8.4.2, so a new release would be helpful for that.

**Comment by peti** [comment]
https://hackage.haskell.org/package/xmonad-0.14

**Comment by MichielDerhaeg** [comment]
You made the new release with broken manpage generation. It would have
been nice if #173 was merged before making the new release.

**Comment by peti** [comment]
Yes, you are right. I wanted to make progress with *building* xmonad. When I looked at https://github.com/xmonad/xmonad/pull/173, I found that the resulting code does not compile. Later, I added af104509c3a4d93e1544651b025abe003f783abe to fix that, but that was after the release had been made. Let's consolidate matters for a few days, and then we can release 0.14.1 to mitigate those issues

**Comment by MichielDerhaeg** [comment]
Agreed, thanks for putting in all the effort :)
