### ISSUE TITLE
Windows that are fullscreened that were created before a strut window appear beneath strut

### ISSUE THREAD

**Issue by colonelpanic8** [xmonad/xmonad#162]
### Problem Description

This may or may not be related to #89 or #106.

When I restart or otherwise create a strut AFTER I have some application (chrome typically) running, and then I do something to make that application go full screen, the strut will appear over the fullscreen window.

This will stop happening if I then restart the application again, or if the restart of the strut window never happens.

Interestingly, If I manually float ANY (not necessarily belonging to the application) window, and make it overlap the strut window momentarily, and then go fullscreen again, the problem does not present itself.

### Configuration File

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

(Will update momentarily)

### Checklist

  - [x ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

(In progress)

**Comment by geekosaur** [comment]
If you're not using EwmhDesktops, the behavior of a fullscreened window is completely up to the application. And windows with struts are self-managing. In short, neither is visible to, or under control of, xmonad.

**Comment by colonelpanic8** [comment]
> If you're not using EwmhDesktops, the behavior of a fullscreened window is completely up to the application. And windows with struts are self-managing. In short, neither is visible to, or under control of, xmonad.

I am using EWMH desktops. How does this affect things?

Good to know these things, but then how can we explain:

> Interestingly, If I manually float ANY (not necessarily belonging to the application) window, and make it overlap the strut window momentarily, and then go fullscreen again, the problem does not present itself.

Is something in the strut windows process raising or lowering the strut? seems unlikely to me.

**Comment by colonelpanic8** [comment]
I suppose that this was more an issue with my bar than with xmonad

See travitch/taffybar#275

**Comment by geekosaur** [comment]
Sorry. My remark was more that reproducing it without `EwmhDesktops` is not entirely helpful because bars don't work right anyway.
