### ISSUE TITLE
VLC controls

### ISSUE THREAD

**Issue by lkjell** [xmonad/xmonad#171]
### Problem Description
Not sure if this is VLC problems or XMonad's. However, on the latest version of VLC the volume scrolling will also scroll the position. Appropriate setting are done in setting. When in fullscreen the control menu is not visible.

VLC media player 4.0.0-dev Otto Chriek (revision 4.0.0-dev-2880-g3a8ae5e94f)
VLC version 4.0.0-dev Otto Chriek (4.0.0-dev-2880-g3a8ae5e94f)
Compiled by kl on arch.localdomain (May 17 2018 11:09:37)
Compiler: gcc version 8.1.0 (GCC)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public License;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.

xmonad 0.13

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
conf = ewmh mateConfig
	{ manageHook = manageDocks <+> _manageHook
		<+> manageHook mateConfig
	, workspaces = _workspaces
	, layoutHook = smartBorders $ avoidStruts $ boringWindows $ minimize $ _layout
	, handleEventHook = restoreMinimizedEventHook  `mappend` fullscreenEventHook
	, focusFollowsMouse = False
	, modMask = mod1Mask
	, terminal = "mate-terminal"
	}`additionalKeys`
		[ ((mod1Mask .|. shiftMask, xK_x), withFocused minimizeWindow)
		, ((mod1Mask, xK_x), sendMessage RestoreNextMinimizedWin)
		, ((mod1Mask .|. shiftMask, xK_d), withAll minimizeWindow)
		, ((mod1Mask, xK_d), withAll bringRestored >> focusMaster)
		, ((mod1Mask .|. shiftMask, xK_t), sendMessage ToggleStruts)
--		, ((mod1Mask, xK_n), spawn "nautilus ~/")
		, ((mod1Mask, xK_n), spawn "caja ~/")
		, ((mod1Mask, xK_m), spawn "update-manager")
	--	, ((mod1Mask, xK_Tab), focusDown)
	--	, ((mod1Mask .|. shiftMask , xK_Tab), focusDown)
		, ((mod1Mask, xK_j), focusDown)
		, ((mod1Mask, xK_k), focusUp)
		, ((mod1Mask, xK_p), spawn "dmenu_run")
		, ((mod1Mask, xK_Print), spawn "mate-screenshot -i")
		, ((mod1Mask .|. shiftMask, xK_q), spawn "mate-session-save --kill")
--		, ((mod1Mask .|. shiftMask, xK_comma), spawn "gnome-session-quit --power-off")
		, ((mod1Mask .|. shiftMask, xK_g     ), windowPromptGoto  defaultXPConfig)
		, ((mod1Mask .|. shiftMask, xK_b     ), windowPromptBring defaultXPConfig)
		, ((mod1Mask .|. shiftMask, xK_h     ), sendMessage MirrorShrink)
		, ((mod1Mask .|. shiftMask, xK_l     ), sendMessage MirrorExpand)]

main = do
--	xmproc <- spawnPipe "xmobar"
	mateRegister :: MonadIO m => m()
	xmonad conf
		{ startupHook = startupHook conf >> setWMName "LG3D"
--		, logHook = takeTopFocus >> setWMName "LG3D"
	--	, logHook = dynamicLogWithPP $ xmobarPP
	--		{ ppOutput = hPutStrLn xmproc
	--		, ppCurrent = xmobarColor "#FF0088" ""
	--		, ppLayout = xmobarColor "#FFFF00" ""
	--		, ppTitle = xmobarColor "blue" "" . shorten 50
	--	 }
	}

```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
You generally want to use an EWMH-enabled config with programs like vlc. See https://wiki.haskell.org/Xmonad/Config_archive/Template_xmonad.hs_(darcs) second example.

**Comment by lkjell** [comment]
@geekosaur link broken. "wiki.haskell.org/Xmonad/Config_archive/Template_xmonad.hs_(darcs)" works but does not show how to enable ewmh.

Anyway I do have ewmh enable with fullscreenEventHook.

**Comment by liskin** [comment]
Is this still an issue? Can you please include a screenshot/video of the problem, or a better description of how to exactly reproduce it, what you expect to happen and what happens instead?

**Comment by slotThe** [comment]
Will closed this due to inactivity; feel free to chime in again
