### ISSUE TITLE
Should the generated files really go into the config directory?

### ISSUE THREAD

**Issue by xaverdh** [xmonad/xmonad#178]
### Problem Description

At the moment generated files (hi, object files) go into the config directory.
This is true even if all XDG_*_HOME variables are set.
Now in some cases it seems desirable to store the source files in a separate location from the arch specific files. My use case would be sharing the configuration between several machines by just mirroring the directory.

As a side note, although I am not too familiar with the xdg spec, I wonder if putting the hi/object files into the config directory is consistent with the specification.

**Comment by liskin** [comment]
This is a good point actually, we might want to add `-outputdir ~/.local/share/xmonad` to the `ghc` command-line.

**Comment by liskin** [comment]
Implemented in https://github.com/xmonad/xmonad/pull/318 if you'd like to help with testing/review :-)
