### ISSUE TITLE
Hackage and GitHub xmonad-0.14.1 release tarballs differ

### ISSUE THREAD

**Issue by solpeth** [xmonad/xmonad#181]
### Problem Description

It appears that `xmonad.hs` is not in the `man/` directory in the [tarball fetched from hackage](http://hackage.haskell.org/package/xmonad-0.14.1/src/), but it is in the [tarball fetched from xmonad on GitHub](https://github.com/xmonad/xmonad/releases/tag/v0.14.1).

I'm aware of the changes to `data-files` as of this release, but I'm not sure why the tarballs differ.

### Checklist

- [x]  I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by peti** [comment]
I accidentally dropped that file from the `extra-source-files` attribute. Thanks for pointing that out! I'll release 0.14.2 to fix that issue in a minute.

**Comment by solpeth** [comment]
No worries! Cheers.
