### ISSUE TITLE
Blank unresponsive screen on login, on Mint 19

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad#184]
### Problem Description

The version of xmonad available in the Mint 19 repositories (namely, xmonad 0.13-7) produced a totally blank and unresponsive screen after installation and upon login. I had to open a tty and reboot.

### Configuration File

I used the default config.

### Checklist

  - [ x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
I have looked at it.
  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
I have not, but still, and as I say, I made no configuration changes. I could find no log file entries that seemed relevant to the problem or indeed to xmonad.

**Comment by peti** [comment]
We're at xmonad 0.15 now. Please try updating to that version.
