### ISSUE TITLE
Under some circumstances dock status is not preserved over restart

### ISSUE THREAD

**Issue by hramrach** [xmonad/xmonad#189]
### Problem Description

On some systems (with nVidia blobware drivers? multiple displays? older ghc version ?) restarting xmonad results in docks losing their dock status. Observed from .13 to .15 but not on all systems.

A dock (lxpanel or gkrellm with proper settings) works ok until xmonad is restarted. When xmonad is restarted the space is no longer reserved for the dock. Restarting the dock fixes the issue.

**Comment by liskin** [comment]
Do you by any chance use `docksEventHook`/`manageDocks` directly instead of `docks`, but without also using `docksStartupHook`? There was a performance fix around the 0.12 release which unfortunately (and I still believe unnecessarily) changed the API.

**Comment by hramrach** [comment]
Yes, that would be the case.

**Comment by liskin** [comment]
Maybe I should, even after all these years, try to make the change I suggested back then to make `docksStartupHook` unnecessary. :-)

**Comment by liskin** [comment]
https://github.com/xmonad/xmonad-contrib/pull/406 was merged a couple months ago so I think we can close this as fixed.
