### ISSUE TITLE
Upgrading to 0.12 change first Workspace behavior

### ISSUE THREAD

**Issue by Maeda1** [xmonad/xmonad#19]
Hi !

I just upgraded to xmonad 0.12, and I have two xmobar process. With xmonad 0.11, no problem, opening several windows on the first workspace is working as expected. Now, with 0.12, windows is above the second xmobar menu (as soon as I open one window). It's not happening on other workspaces.

An idea ?

Here is my xmonad.hs : http://lpaste.net/5889344209512562688

Thanks.

N.B. : the second xmobar menu is launched by my ~/.xinitrc

**Comment by f1u77y** [comment]
#18

**Comment by Maeda1** [comment]
You're right, solved by adding handleEventHook = docksEventHook.
Thanks.
