### ISSUE TITLE
alacritty, spotify and chromium sometimes 'freeze' in xmonad

### ISSUE THREAD

**Issue by Memorytaco** [xmonad/xmonad#201]
### Problem

alacritty and chromium has been affected and i have no idea. They just don't get updated and the problem occured quite often. I have to pkill them and reopen it but same situation will appear quite soon. gvim, firefox and st seems working fine. btw, spotify has been affected also. inner process doesn't affected which means they are not actually 'freezed', but just don't respond to workspace change. I have gotten a running compiling job in a 'freezing' alacritty and it has exited successfully because compiling process stopped latter and compiled program working normally. but alacritty don't respond though. chromium has similar issue. Just like what the image shows behind.

unfortunately, there is no obvious way to reproduce this problem, it just happened occasionally. 

here is the image when only open a alacritty and idled sometime(it's not in float mode, something didn't get rendered here):

![capture](https://user-images.githubusercontent.com/30775014/67954866-9c25e300-fc2c-11e9-8411-482383808b28.png)

### Configuration File and releated Info

```haskell
-- haskell config file
{-# LANGUAGE OverloadedStrings #-}
import XMonad
import XMonad.Util.EZConfig (additionalKeys)
import System.IO

main = do
  spawn "ibus-daemon -rdx"
  spawn "feh --bg-fill ~/.config/awesome/wall.jpg"
  xmonad $ def {
      terminal = "alacritty"
    , borderWidth = 2
    , modMask = mod4Mask
    , focusedBorderColor = "#ebdbb2" -- "#3ab811"
    , normalBorderColor = "#282828"
    } `additionalKeys`
    [
      ((mod4Mask, xK_d), spawn "rofi -show run")
    ]
```

```bash
# .xinitrc file
QT_IM_MODULE=ibus
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus

xrdb -merge .Xresources
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session /home/user/.local/bin/xmonad
```

here is linux version `uname output : Linux Pixel 5.3.7-gentoo #7 SMP Mon Oct 21 19:00:46 CST 2019 x86_64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz GenuineIntel GNU/Linux`.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
> i didn't test it with xmonad-testing because my configuration is quite simple and shouldn't go wrong.

**Comment by geekosaur** [comment]
Recent chromium has been reported to "freeze" like this when EWMH isn't enabled; apparently it relies on the EWMH root window properties to know when a workspace change has occurred, instead of map/unmap. You'll need http://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Hooks-EwmhDesktops.html#v:ewmh if this is one of those chromium releases.

Increasingly `EwmhDesktops` should be the first thing you try if some program doesn't work.

**Comment by Memorytaco** [comment]
Thanks for your replying, gotta the code added with your advice. I need some time to deep into xmonad-contrib and testing whether this will work. Thanks again! :)

**Comment by Memorytaco** [comment]
There still exists 'freeze' problem with ewmh in code.

```haskell
{-# LANGUAGE OverloadedStrings #-}
import XMonad
import XMonad.Util.EZConfig (additionalKeys)
import XMonad.Hooks.EwmhDesktops
import System.IO

main = do
  spawn "ibus-daemon -rdx"
  spawn "feh --bg-fill ~/.config/awesome/wall.jpg"
  xmonad $ ewmh def {
      terminal = "alacritty"
    , borderWidth = 2
    , modMask = mod4Mask
    , focusedBorderColor = "#ebdbb2" -- "#3ab811"
    , normalBorderColor = "#282828"
    } `additionalKeys`
    [
      ((mod4Mask, xK_d), spawn "rofi -show run")
    ]
```

no chromium or spotify running this time when alacritty freezed.

i don't know how to deal with ewmh, sorry...

![capture](https://user-images.githubusercontent.com/30775014/68192676-a8bf8800-ffec-11e9-898a-05e7be7785d3.png)

**Comment by geekosaur** [comment]
I can't currently install alacritty with this network connection for testing, sorry.

Just for grins and giggles, can you see if running `compton --backend=glx` improves things any? It may be relying on something else initializing the GPU. Alternately if `compton` fails then it's something about availability of the GPU and it might be necessary to e.g. force load of a GPU driver into X11.

**Comment by Memorytaco** [comment]
sorry for not responding. I didn't use a compositor for x window, but now i'm trying compont now.

**Comment by Memorytaco** [comment]
Installing a light weight compositor like `compton` seems fixing this problem. This problem doesn't appear anymore when using this compositor.

**Comment by geekosaur** [comment]
That may be the simplest solution, then. `xmonad` doesn't and can't use the GPU, so can't keep it prepared for applications to use. I'd argue this as an application bug that they shouldn't assume something else has set the GPU up, but there might not be a proper API for non-compositors to set it up.

**Comment by Memorytaco** [comment]
This problem seems being solved now. After a long night compiling and upgrading job, the terminal didn't freeze. The solution is to use a light weight compositor like **compton** and enable **ewmh**(i'm not sure whether `ewmh` is required but i have added to my configuring file and it works).

Maybe it's a good idea to let xmonad-contrib add some abilities for xmonad to handle this.. :)

to me, compositor is a magic and all graphic related issue on linux is black magic. Er..
