### ISSUE TITLE
blank white screen on save, save as, and open file in applications:

### ISSUE THREAD

**Issue by zeta-00** [xmonad/xmonad#210]
Hello there, i am currently using nixos with the nix package manager, i completely removed my desktop environment and installed xmonad by itself. So far xmonad has been working great, but for some reason whenever I try to do a save, save as, or open file in an application, such as libre office or the atom text editor, it takes me to a blank screen, I have no idea why this is happening or how to troubleshoot this issue, maybe, since i am only using xmonad, I am missing some application from a desktop environment that provides this functionality. Also, when I am in firefox when i try press a button prompt to select a picture from my user directories, it also takes me to a blank screen, at this point I have no idea? If you could help me solve this issue, thanks

**Comment by zeta-00** [comment]
here is my xmonad.hs configuration:

import XMonad
import qualified XMonad.StackSet as W
import XMonad.Util.EZConfig
import Graphics.X11.ExtraTypes.XF86
--import qualified XMonad.Util.Brightness as Bright

main = xmonad $ defaultConfig

                { modMask = mod4Mask -- Use Super instead of Alt
                , terminal = "terminator"
                }

                `additionalKeysP`
                [ ("M-!", windows $ W.greedyView "1")
                , ("M-S-!", windows $ W.shift "1")
                , ("M-\"", windows $ W.greedyView "2")
                , ("M-S-\"", windows $ W.shift "2")
                , ("M-(", windows $ W.greedyView "3")
                , ("M-S-(", windows $ W.shift "3")
                , ("M-j", windows $ W.greedyView "4")
                , ("M-S-j", windows $ W.shift "4")
                , ("M-y", windows $ W.greedyView "5")
                , ("M-S-y", windows $ W.shift "5")
                , ("M-z", windows $ W.greedyView "6")
                , ("M-S-Z", windows $ W.shift "6")
                , ("M-k", windows $ W.greedyView "7")
                , ("M-S-k", windows $ W.shift "7")
                , ("M-+", windows $ W.greedyView "8")
                , ("M-S-+", windows $ W.shift "8")
                , ("M-*", windows $ W.greedyView "9")
                , ("M-S-*", windows $ W.shift "9")
                , ("<XF86AudioMute>", spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle")
                , ("<XF86AudioLowerVolume>", spawn "pactl set-sink-volume @DEFAULT_SINK@ -1.5%")
                , ("<XF86AudioRaiseVolume>", spawn "pactl set-sink-volume @DEFAULT_SINK@ +1.5%")
                --, ("<XF86MonBrightnessDown>", Bright.decrease)
                --, ("<XF86MonBrightnessUp>", Bright.increase)
                , ("M-S-e", spawn "emacs")
                , ("M-S-w", spawn "firefox")
                , ("M-S-v", spawn "kodi")
                ]

**Comment by zeta-00** [comment]
also here is my xmonad installation/configuration in home.nix:

  xsession = {
    enable = true;
    windowManager.xmonad = {
      enable = true;
      enableContribAndExtras = true;
      extraPackages = haskellPackages: with haskellPackages; [
        xmonad
        monad-logger
        xmonad-contrib
        xmonad-entryhelper
        # xmonad-eval
        xmonad-extras
        xmonad-screenshot
        xmonad-utils
        xmonad-volume
        xmonad-wallpaper
        # xmonad-windownames
      ];
      config = ./xmonad.hs;
    };
  };

**Comment by geekosaur** [comment]
LibreOffice, at least, is known to require EwmhDesktops for its dialogs to work. The easiest way to do this is to import XMonad.Hooks.EwmhDesktops and insert "ewmh" before "defaultConfig".

**Comment by zeta-00** [comment]
ok, I tried your solution and xmonad compiled  without any errors, but it did not fix my issue? also, i tried the example code from this link but that did not fix the issue either: https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Hooks-EwmhDesktops.html  , i also installed ewmh as a python package to make sure there are no missing dependencies, as well as the wmctrl package. Maybe there is functions from that link that i need to implement as well?

**Comment by zeta-00** [comment]
import XMonad
import qualified XMonad.StackSet as W
import XMonad.Util.EZConfig
import Graphics.X11.ExtraTypes.XF86
--import qualified XMonad.Util.Brightness as Bright
import XMonad.Hooks.EwmhDesktops

main = xmonad $ ewmh defaultConfig

                { modMask = mod4Mask -- Use Super instead of Alt
                , terminal = "terminator"
                }

                `additionalKeysP`
                [ ("M-!", windows $ W.greedyView "1")
                , ("M-S-!", windows $ W.shift "1")
                , ("M-\"", windows $ W.greedyView "2")
                , ("M-S-\"", windows $ W.shift "2")
                , ("M-(", windows $ W.greedyView "3")
                , ("M-S-(", windows $ W.shift "3")
                , ("M-j", windows $ W.greedyView "4")
                , ("M-S-j", windows $ W.shift "4")
                , ("M-y", windows $ W.greedyView "5")
                , ("M-S-y", windows $ W.shift "5")
                , ("M-z", windows $ W.greedyView "6")
                , ("M-S-Z", windows $ W.shift "6")
                , ("M-k", windows $ W.greedyView "7")
                , ("M-S-k", windows $ W.shift "7")
                , ("M-+", windows $ W.greedyView "8")
                , ("M-S-+", windows $ W.shift "8")
                , ("M-*", windows $ W.greedyView "9")
                , ("M-S-*", windows $ W.shift "9")
                , ("<XF86AudioMute>", spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle")
                , ("<XF86AudioLowerVolume>", spawn "pactl set-sink-volume @DEFAULT_SINK@ -1.5%")
                , ("<XF86AudioRaiseVolume>", spawn "pactl set-sink-volume @DEFAULT_SINK@ +1.5%")
                --, ("<XF86MonBrightnessDown>", Bright.decrease)
                --, ("<XF86MonBrightnessUp>", Bright.increase)
                , ("M-S-e", spawn "emacs")
                , ("M-S-w", spawn "firefox")
                , ("M-S-v", spawn "kodi")
                ]

**Comment by zeta-00** [comment]
If I still can't figure this out then I will try out some setups from the xmonad cofiguration archive, and maybe one of them will help me solve my problem, at this point I have no idea? https://wiki.haskell.org/Xmonad/Config_archive

**Comment by zeta-00** [comment]
In emacs when i press the tab buttons file and open file, and press enter a couple of times it opens up a pdf file, so that means that it is working but it goes to a blank white screen, that must mean that xmonad is not drawing context menu, maybe there is a nix option that i can set so xmonad shows the context menu, at this point i have no idea

**Comment by ali-abrar** [comment]
It might just be opening an incorrectly sized file dialog. Try pressing mod-t when that white screen opens up (assuming standard keybindings).

**Comment by zeta-00** [comment]
Yes, thanks ali-abrar, mod-t resizes the file dialog to fit into the window, so it feels good to finally be able to save, open, and upload files. This is ok for now but eventually I need to figure out how to permanently set the window size so that it will automatically render to the correct size. In nixos i already set my dpi to work with my HiDPI laptop so i don't want to change it, maybe there is a nix option somewhere to change the file dialog size, let me know, thanks for the help guys.

**Comment by geekosaur** [comment]
So we've been tossing this around in IRC, and as a workaround we're forcing file dialogs to be tiled. This means a `manageHook` fragment, or in this case the only entry in the `manageHook`:

    import qualified XMonad.StackSet as W
    
    main = xmonad $ ewmh defaultConfig
                { modMask = mod4Mask -- Use Super instead of Alt
                , terminal = "terminator"
                , manageHook = stringProperty "WM_WINDOW_ROLE" =? "GtkFileChooserDialog" -->
                               ask >>= doF . W.sink
                }
                ... rest of config here ...

It would be nice to figure out what's going wrong here, but there are multiple variables including that the user has HiDPI enabled which throws off a number of things related to rendering.

**Comment by zeta-00** [comment]
hello @geekosaur @ali-abrar ,
That worked, thanks for the help guys, go ahead and close this issue.
