### ISSUE TITLE
Inaccurate comment that spawn double-forks

### ISSUE THREAD

**Issue by jasonvaccaro** [xmonad/xmonad#211]
Hi xmonad folks! New user here.

This is a minor concern about a comment in the source code.  XMonad.Core has a function called spawn. As far as I can tell, spawn only forks once, but the comment above the function definition says that it double-forks.

I request that this comment be corrected.

Thanks,
Jason

**Comment by geekosaur** [comment]
If it's not double-forking any more, then we're effectively Linux-only. Can the double fork be put back?

**Comment by MichielDerhaeg** [comment]
Was changed in this commit, and docs were never updated:
https://github.com/xmonad/xmonad/commit/0fecae0abc0cc6871580ac0bb4a1b5c0d4b5aa03

Reverting to double-forking looks like a significant change in contrib.

**Comment by geekosaur** [comment]
Contrib should be using `xfork`; it's `spawn`, which starts an independent process that can't be used to e.g. read its stdout, that should be double forking. This at least used to be the case.

Or are we just explicitly becoming linux only at this point? Not every target OS sets the child process limit as high as Linux does.

**Comment by slotThe** [comment]
> Or are we just explicitly becoming linux only at this point? Not every target OS sets the child process limit as high as Linux does.

There still seem to be many happy BSD users around (as evidenced by the fact that OpenBSD and FreeBSD were both quite fast at updating to 0.17.0)—I guess this doesn't really matter for them either (a commit from 2009 would surely have been noticed by now!)
