### ISSUE TITLE
`who` doesn't update to reflect new terminal emulators open

### ISSUE THREAD

**Issue by Radvendii** [xmonad/xmonad#212]
### Problem Description

When I open a new terminal emulator, the `who` command does not change to reflect the additional connection.

Looking online, I found this answer: https://unix.stackexchange.com/questions/441717/w-command-doesnt-show-all-pseudo-terminal-sessions, which suggests that terminal emulators won't, in general, update the file that `who` reads from, but they can be made to. I tried running `xterm +ut` as it suggested and that didn't do it either.

If I run `sudo login`, and log in, the `who` command does gain an additional update.

Ultimately, I am not concerned about the `who` command, but I do want `talk` to ring on my terminal emulators, which it seems to only do when they are listed in `who`.

### Configuration File

(I didn't just leave this as is. I tested the problem with this blank configuration.)

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
`+ut` doesn't work any more because `xterm` needs to be setuid for it to work and this is considered a security hole. Some other terminal emulators have a setuid helper which does so.

**Comment by Radvendii** [comment]
Oh, interesting. I have tried now with many different terminal emulators, several of which my coworkers use and they all have `who` update when they open a new terminal window. The only difference I can see between my configuration and theirs is that I am running xmonad. Is it even possible that that could be causing the issue?

**Comment by geekosaur** [comment]
There's a number of possibilities including how they get their parameters (if dconf is running it will win, otherwise it uses dotfiles which probably don't exist).

I use `mate-terminal`, which has a profile option to run a login shell. (I keep it turned off, for what it's worth.) Check terminal settings for similar options; for `mate-terminal` it's in the profile, in the `title and command` tab.

**Comment by geekosaur** [comment]
Most people run sessions which configure things like dconf for them; xmonad is a simple window manager and doesn't set up a full session.

**Comment by Radvendii** [comment]
Ah, okay, this worked. Thank you so much.

Now the entries in `who` don't disappear when I close the window, but I'm guessing that's something I can figure out by digging into dconf and the differences between login and non-login shells.

**Comment by geekosaur** [comment]
There's a comment in `login` manpage that something else needs to clean up after it. I don't know if the same applies to `libutempter`.
