### ISSUE TITLE
customFloating named scratchpad not floating

### ISSUE THREAD

**Issue by Norem80** [xmonad/xmonad#214]
### Problem Description

I have set up a named scratchpad with spotify and made it `customFloating` with `RationalRectangle` and added `namedScratchpadManageHook` to manage hooks but the window still does not float.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
myScratchpads = [ NS "spotify" spawnSpotify findSpotify manageSpotify ]
  where
    spawnSpotify = "spotify"
    findSpotify = resource =? "Spotify"
    manageSpotify = customFloating $ W.RationalRect (1/3) 0 (1/3) (2/3)


main = do
  xmproc <- spawnPipe myBar
  xmonad
    $ ewmh
    $ docks
    $ dynamicProjects projects
    $ defaultConfig
    { manageHook                    = manageDocks <+> manageHook defaultConfig <+> namedScratchpadManageHook myScratchpads
    , logHook                       = dynamicLogWithPP xmobarPP
                { ppOutput          = hPutStrLn xmproc
                , ppCurrent         = wrap "[" "]"
                , ppVisible         = wrap "" ""
                , ppHidden          = wrap "*" ""
                , ppHiddenNoWindows = wrap "" ""
                , ppTitle           = shorten 80
                , ppSep             = " : "
                , ppUrgent          = wrap "!" "!"
                , ppExtras          = []
                , ppOrder           = \(ws:l:t:ex) -> [ws,l]++ex++[t]
                }
    , layoutHook                    = avoidStruts  $  layoutHook defaultConfig
    , modMask                       = mod4Mask
    , terminal                      = myTerminal
    , startupHook                   = myStartupHook
    , borderWidth                   = 2
    , normalBorderColor             = "#000000"
    , focusedBorderColor            = "#ffffff"
    , clickJustFocuses              = True
    , focusFollowsMouse             = False
    , workspaces                    = myWorkspaces
    } `additionalKeys` myKeys
```

**Comment by geekosaur** [comment]
I can't test this now (or for the next two weeks) but make sure you have the right resource name / `appName` or `className`. Initial uppercase for an `appName` looks suspicious, although I vaguely recall that Spotify doesn't follow the ICCCM here.

**Comment by Norem80** [comment]
I tried with lower case letter and it didn't change anything.

**Comment by ouzned** [comment]
I had a similar issue with an instance of whatsapp running in a chrome window that I used as a scratchpad. It turned out that the specific "WhatsApp" appName was not available on start and I had to use the DynamicProperty module from xmonad-contrib to make it work 

http://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-DynamicProperty.html

![image](https://user-images.githubusercontent.com/876544/91766124-5930f500-ebda-11ea-91c8-228217360a48.png)

**Comment by asolopovas** [comment]
Has any one succeeded setting this up? Could you please share example config?

**Comment by Jake-Moss** [comment]
I found this [Reddit post](https://www.reddit.com/r/xmonad/comments/ay7824/floating_spotify_in_a_namedscratchpad/) which worked for me.

For the sake of preservation here are the code snippets I used.
```
import Data.Semigroup
import XMonad.Hooks.DynamicProperty
```

```
myHandleEventHook :: Event -> X All
myHandleEventHook = dynamicPropertyChange "WM_NAME" (title =? "Spotify" --> floating)
        where floating = customFloating $ W.RationalRect (1/6) (1/6) (2/3) (2/3)
```

```
handleEventHook = myHandleEventHook
```

**Comment by arifer612** [comment]
The hack by @Jake-Moss  works perfectly for me when creating an Emacs scratchpad. I just wanted to point out that there should not be a need for the `Data.Semigroup` import.

**Comment by wdobler** [comment]
The `DynamicProperty` solution by @Jake-Moss works perfectly with a Spotify scratchpad for me.

(The `Data.Semigroup` import is only needed if you declare the type of your `myHandleEventHook` function,  as @Jake-Moss did in his post. It will give you the `All` type.)

**Comment by arifer612** [comment]
You are right! It is defined in `Data.Semigroup`. I failed to recognise that since I had `Data.Monoid` imported and did not realise that `All` was imported as part of its sub-import.

**Comment by mikenrafter** [comment]
I no longer use spotify, though when I did, it was spotty at best.

What I used was: `resource ~? "spotify"`

Whereas `~?` is:
```haskell
q ~~? x = isInfixOf x <$> q
q ~? x = q ~~? (tail x)
```

After the first few seconds of startup, this worked.

**Comment by slotThe** [comment]
Closed by https://github.com/xmonad/xmonad-contrib/commit/ab98b40034cd5ec3581884aea054dc6886e54f17
