### ISSUE TITLE
Trayer not working properly with xmonad/xmobar

### ISSUE THREAD

**Issue by eazar001** [xmonad/xmonad#22]
I have the following in a bash script which is executed by `spawn ::  string -> IO ()`

```
trayer --SetDockType true --expand true --edge top --align right --width 15 --height 18 --transparent true --alpha 255 &
```

Now, everything works properly when I look for the process with `ps ax | grep trayer`. The output indicates that the process is indeed running. However, opening up relevant processes such as transmission-gtk and skype will not bring up the icon in the sys tray. However, when I `pkill trayer`, and then run trayer again, it will then show the icons. Is there something peculiar to xmonad or xmobar that could be hiding the systray due to a race condition of some sort?

**Comment by eazar001** [comment]
Alright, so I did a lightweight sherlock-holmes and here's what happened:
After modifying the spawn command to sleep for 60 seconds prior to executing the trayer command, it appears that it functions correctly without needing to kill it and restart it. So it really does seem to be a race condition. I wonder if there is a better way to get this to start after xmonad and xmobar have finished starting up.

**Comment by mkoskar** [comment]
Sounds like your `xmobar` is placed on top of `trayer`. Just configure it such that it leaves a space for it e.g., `position = TopP 0 100` will leave space top-right of 100px. Note that xmobar doesn't work well with expanding trayer, see https://github.com/jaor/xmobar/issues/239.

**Comment by f1u77y** [comment]
if you like to use statusbar with tray, why don't you use taffybar?

**Comment by eazar001** [comment]
@mkoskar thanks. You're right, that does seem to work now without adding any time delays into my starup. I'll close this issue for now, as the issue seems to be resolved.

**Comment by crocket** [comment]
stalonetray blends well into xmobar.
