### ISSUE TITLE
Does XMonad use xcb or xlib?

### ISSUE THREAD

**Issue by Joe23232** [xmonad/xmonad#226]
I am looking for the right tiling window manager so I just have some questions. Does XMonad use xcb or xlib?

If it uses Xlib does XMonad plan to change to xcb library?

**Comment by geekosaur** [comment]
It uses xlib and can't be changed without changing the entire API because it's a very thin layer over it.

**Comment by Joe23232** [comment]
That's a bit unfortunate but thanks anyways :)
