### ISSUE TITLE
Black screen after login on Ubuntu 20, can't render a terminal

### ISSUE THREAD

**Issue by mchaver** [xmonad/xmonad#228]
### Problem Description

I have a new computer (Ubuntu 20 and  Gnome 3.36.2) and I wanted to run Xmonad on it. I originally asked this question on reddit, but it remains unresolved so I thought it would be better to ask the maintainers.
https://www.reddit.com/r/xmonad/comments/hehp99/unable_to_open_terminal_in_fresh_install/

If I use the xmonad login, nothing renders. I started without a xmonad.hs file, then added a minimal one, then tried adding a few things I thought would render, then went back to the minimal one without any change. I can logout with super+shift+q. super+shift+enter does not render a terminal (I have gnome-terminal, xterm and urxvt and I have tried them all as terminal in def), shift+p does nothing either. I believe it just isn't rendering because logout works and I can switch the super key and logout reflects that. I switch to gnome to edit and compile xmonad.hs, then I logout and test by logging into xmonad with the same user.

I installed xmonad, libghc-xmonad-contrib-dev, suckless-tools and xterm. After I make a change to xmonad I run `xmonad --recompile`. I also tried building and running from stack but it gave me the same result;

### Configuration File

Currently as minimal as possible.

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def {modMask = mod4Mask}
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by mchaver** [comment]
I don't know much about displays, but I was thinking what if xmonad is correct finding the display (it's a laptop)?

```
xrandr --query
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080    120.00*+  60.00  
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
```

```
lspci
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 05)
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1f99 (rev a1)
```

**Comment by mchaver** [comment]
I see that `echo $DISPLAY` returns `:1` whereas on another laptop it without a dedicated GPU it returns `:0`. 

I think this is the issue because I proved I can call a terminal but can't see anything. I logged into xmonad, then typed mod+shift+return, then `echo "test" >> .xmonad/log.txt`, logged out, logged into gnome, then opened the file and saw it had appended text.

How do I tell xmonad to look for display `:1` as the primary display?

**Comment by mchaver** [comment]
It looks like the display name is not part of a config and xmonad is doing `openDisplay ""` by default. Does this automatically render on ":0"? Is there a way to open it from ":1" or the value stored in "$DISPLAY"?
https://github.com/xmonad/xmonad/blob/c54e7088f003228e31096e68eabc75d50d227c1c/src/XMonad/Main.hs#L177

**Comment by geekosaur** [comment]
That should use $DISPLAY.

**Comment by mchaver** [comment]
Is another possibility that it is rendering outside the bounds of the screen?

**Comment by geekosaur** [comment]
It shouldn't be.

There have been reports of xmonad not handling :1 correctly before,
IIRC. I don't think anyone has been in a position to test it properly,
but there may be hardcoded references to the root window of screen 0
somewhere in the core.

-- 
brandon s allbery kf8nh
allbery.b@gmail.com

**Comment by liskin** [comment]
I had no problems with xmonad on :1, ever. Used it on and off for >10 years.

**Comment by liskin** [comment]
> I don't know much about displays, but I was thinking what if xmonad is correct finding the display (it's a laptop)?
> 
> ```
> xrandr --query
> Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
> DP-0 disconnected (normal left inverted right x axis y axis)
> DP-1 disconnected (normal left inverted right x axis y axis)
> eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
>    1920x1080    120.00*+  60.00  
> HDMI-1-1 disconnected (normal left inverted right x axis y axis)
> ```
> 
> ```
> lspci
> 00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 05)
> 01:00.0 VGA compatible controller: NVIDIA Corporation Device 1f99 (rev a1)
> ```

Is this from xmonad or from GNOME? This looks almost exactly like what I get when I run X using this config: https://github.com/liskin/dotfiles/blob/de01228269d563e67d7c2104dbf1e9ad26f404a3/etc/X11/xorg.conf.nvidia and _then_ pass the intel outputs to nvidia using https://github.com/liskin/dotfiles/blob/30a3317fb35a0412ddb86098f9a91be0eff9a856/.xsession#L12-L13. Without those two xrandr commands, a black screen is what I get. It shouldn't be necessary with a recent xorg-server (https://gitlab.freedesktop.org/xorg/xserver/-/commit/078277e4d92f05a90c4715d61b89b9d9d38d68ea), but as there have been no releases recently, no one is running a recent xorg-server.

**Comment by liskin** [comment]
That being said, are you absolutely sure you want nvidia to be your primary GPU, given this is a laptop and it's going to increase the power consumption by several watts?

**Comment by mchaver** [comment]
> Is this from xmonad or from GNOME?

From GNOME.

> That being said, are you absolutely sure you want nvidia to be your primary GPU, given this is a laptop and it's going to increase the power consumption by several watts?

Doesn't have to be my primary. I am happy with having the ability to switch as needed, but even happier to have any working solution at the moment, hehe. Probably for most of my use a GPU isn't important.

> two xrandr commands

I will test these out and report back

**Comment by liskin** [comment]
> Doesn't have to be my primary. I am happy with having the ability to switch as needed, but even happy to have any working solution at the moment, hehe. Probably for most of my use a GPU isn't important.

Well then why is nvidia enabled as primary in your configuration? If my understanding is correct (and I have no reason to believe it is not, as I've been using Optimus laptops for 9 years and was involved a tiny bit in making it work on Linux), it's not set up that way by default, but it's a choice a user has to make deliberately. If you'd used the default configuration, you shouldn't have this problem in the first place. :-/

**Comment by mchaver** [comment]
@geekosaur @liskin 
Thanks for the help! The two lines from @liskin 's .xsession file make it render on my screen now.

@liskin 
How would you set it to render with the integrated graphics card instead of the GPU?

**Comment by mchaver** [comment]
@liskin I just purchased this laptop from system76. It is installed with ubuntu 20. I am using it as is out of the box with the default configurations that the vendor set. I am still very new to window management.

**Comment by liskin** [comment]
> How would you set it to render with the integrated graphics card instead of the GPU?

https://github.com/liskin/dotfiles/blob/de01228269d563e67d7c2104dbf1e9ad26f404a3/etc/X11/xorg.conf, but I believe even with no xorg.conf this should be the default. What does your xorg.conf look like? Can you also list your /etc/X11/xorg.conf.d/ and /usr/share/X11/xorg.conf.d?

**Comment by liskin** [comment]
Oh, a vendor. :-)
That would explain everything. :-)

**Comment by mchaver** [comment]
There is no xorg.conf in /etc/X11 nor /etc/X11/xorg.conf.d

/usr/share/X11/xorg.conf.d
10-amdgpu.conf  10-nvidia.conf  10-quirks.conf  10-radeon.conf  11-nvidia-prime.conf  40-libinput.conf  70-wacom.conf

**Comment by liskin** [comment]
I'm guessing either 10-nvidia.conf or 11-nvidia-prime.conf is the one causing nvidia to be treated as primary. Anyway, this really is out of scope of xmonad so I'll refer you to system76/ubuntu documentation and/or forums, if you wish to find out why it's configured that way and how/if to change it.
