### ISSUE TITLE
Fails to work on arm: schedule: re-entered unsafely.

### ISSUE THREAD

**Issue by nomeata** [xmonad/xmonad#23]
A Debian user reported this problem when using xmonad on arm:

```
xmonad-arm-linux: schedule: re-entered unsafely.
   Perhaps a 'foreign import unsafe' should be 'safe'?
```

https://bugs.debian.org/813154

It would be good to know if anyone else has succeeded in using xmonad on arm, in order to narrow down the problem. Thanks!

**Comment by geekosaur** [comment]
This sounds like https://ghc.haskell.org/trac/ghc/ticket/11190 (which refers to https://ghc.haskell.org/trac/ghc/ticket/9920). Debian stable needs a backport of an LLVM 3.5 bug fix.

**Comment by nomeata** [comment]
Hmm, should have found that. Thanks for the pointers!
