### ISSUE TITLE
How could Ibus input method work on XMonad?

### ISSUE THREAD

**Issue by KyleJKC** [xmonad/xmonad#232]
### Problem Description

Hello, I **have to input Chinese with Ibus**, but the way that I search on google can not absolutly work, so how can I input chinese with Ibus? **THANK YOU SO MUCH!!!!!!**

### Configuration File

I have no config for input method yet...

```haskell
-
```

### Checklist

  - [ * ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ * ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
Xmonad should support XIM, but you would need to configure it to use ibus
before xmonad starts, probably with a wrapper script or by starting xmonad
from a session manager with ibus support like mate-session.

**Comment by geekosaur** [comment]
Do you have any other questions?

**Comment by slotThe** [comment]
Doesn't seem like it (though feel free to chime in again!)
