### ISSUE TITLE
multiple screens shown as selected with solid cursors

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [xmonad/xmonad#233]
### Problem Description

Following the tutorial https://xmonad.org/tour.html and when I got to the *moving focus* section with `mod-,` and `mod-.` there were two terminals with solid cursors. Both cursors would remain solid even when typing. However, when `mod-j` or `mod-k` correct cursor became solid.

### Configuration File

default config file

**Comment by slotThe** [comment]
This seems to be an xterm thing (i.e., I can reproduce it with xterm but not with alacritty or urxvt) so I don't think there is much that we can do here

**Comment by geekosaur** [comment]
That's an old xterm bug, although I've never heard of or seen it triggering that reliably.
