### ISSUE TITLE
getting xmonad working with ubuntu on virtualbox:

### ISSUE THREAD

**Issue by zeta-00** [xmonad/xmonad#235]
### Problem Description

Describe the problem you are having, what you expect to happen
instead, and how to reproduce the problem.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
You can make edits to GitHub issues, no need to create new ones when you forget something or make typos.
