### ISSUE TITLE
Config doesnt update anything 

### ISSUE THREAD

**Issue by Fentanull** [xmonad/xmonad#238]
So i've looked around a bit to find a way to fix this issue but doesnt seem to be a post anywhere about it. Recently i installed xmonad to try out the tiling and i installed it using apt get on my linux mint machine. I downloaded the config from the wiki and put it into the .xmonad folder and started editing it. I save it (and it does save ive checked) then i restart and nothing updates that i wrote while its all there in the config still just how i wrote it.

Its the smallest updates to the config not anything extra just the config wont actually configure xmonad lol.

I run linux mint 19

**Comment by arkoinad** [comment]
It would be helpful for people to help you out with your issue once you post the little change and also xmonad config.
Did you check logs to see if there were any errors reported?

**Comment by xaverdh** [comment]
Actually while working on https://github.com/xmonad/xmonad/pull/240 I noticed that restart might just be broken..

If I read the current code correctly it shells out to `xmonad --recompile` and then `xmonad --restart`. The latter will do `sendRestart`, this gets picked up by the event handler, and calls `restart "xmonad" True` (from `XMonad.Operations`).
`restart` in turn will search for "xmonad" in `PATH` and execute it.

But `recompile` does not put the new binary magically into `PATH` or something, so it will execute whatever it finds there (probably the old / distributed `xmonad`).

If that chain of reasoning is correct, putting the `datadir` (where your compiled binary resides) into your search `PATH` and adding a `symlink` there called "xmonad" pointing to the compiled binary should make it work..

**Comment by xaverdh** [comment]
Turns out I indeed misinterpret the code. It does what I said, but the new `xmonad` process should recompile itself and execute the binary from `datadir`..

**Comment by chrissound** [comment]
This should probably be closed now I assume? @xaverdh

**Comment by xaverdh** [comment]
You mean this issue? I don't think so, since my guess turned out to be wrong..
although it would probably help if @Fentanull could give some more details

**Comment by liskin** [comment]
As we haven't heard back from the reporter, I'll close this for now.
