### ISSUE TITLE
xmonad not respecting .icons local styling

### ISSUE THREAD

**Issue by michaelmyc** [xmonad/xmonad#246]
### Problem Description

- xmonad version: 0.15

It seems to me that xmonad is not reading the styling defined in `~/.icons/default/index.theme`. Only when editing `/usr/share/icons/default/index.theme` does the cursor styling becomes effective. In other wm like bspwm, the wm respects the local settings but xmonad doesn't. 

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
import XMonad

main = do
  xmonad $ def
    {  terminal      = "termite"
    ,  modMask       = mod4Mask
    ,  borderWidth   = 2
    }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by aij** [comment]
I'm guessing you have something else that's reading `/usr/share/icons/default/index.theme`. Are you using some sort of display manager (`gdm`, `lightdm`, `xdm`, etc) or using `startx`?

I wouldn't expect XMonad to mess with the cursor settings unless you tell it to.

Perhaps you want to run `xsetroot` or `lxappearance` or something cursor and/or theme related. I'm not sure how you have bspwm configured nor what it might run by default.

**Comment by michaelmyc** [comment]
I'm running `lightdm`, which doesn't respect the local settings as expected (after all, you haven't logged in). 

My theming is being set with `lxappearance`, so all local theming issues should be handled there. I did check the gtk2 and gtk3 config files and also the default theme config file in the local `.icons` folder, and I can confirm that they are being set by `lxappearance` correctly. 

I did a clean install of i3 on Manjaro, so I'm running the default i3 config, and the cursor theming works fine. Xmonad doesn't seem to care about local theming. I didn't have any program that autostarts at boot/login except for systemd stuff, which I can confirm doesn't mess with the cursor. So this leads me to believe that it's xmonad that is the issue here.

**Comment by geekosaur** [comment]
Xmonad doesn't care about theming at all. I don't know what normally
applies cursor theming in a desktop environment, aside from tools like
lxappearance.

**Comment by michaelmyc** [comment]
Aha. I think probably that's the reason. I guess it's because lightdm set the cursor style and xmonad doesn't know to change it to the local user's settings. Lemme search for ways to change stylings in lightdm as part of startup script. If that works, I'll post my solution and close this.

**Comment by michaelmyc** [comment]
Can confirm that changing `xcursor-theme-name` in lightdm-gtk-greeter config changes the cursor in xmonad as well. This isn't perfect, as it only works with the gtk greeter. The simple (but bad) hack is to change the Inherit theme to the desired cursor theme in `/usr/share/icons/default/index.theme`. I'll explore other ways to potentially fix this and will post if I found a good way to address this issue.
