### ISSUE TITLE
Update MAINTAINERS.md

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad#248]
### Problem Description
The file https://github.com/xmonad/xmonad/blob/master/MAINTAINERS.md seems outdated (broken links, did the core team change?). Also, the points from #75 don't seem to be entirely taken care of (I'd do it myself, but I don't have sufficient information). 

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - ~~[ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~

**Comment by slotThe** [comment]
As for the links, it just seems like GitHub removed linking to people in that
way; I guess one could just pick out the respective profiles from the [people
page](https://github.com/orgs/xmonad/people) and replace the links.

**Comment by slotThe** [comment]
@TheMC47 #257 should have solved at least part of this; what do you think is still missing?

**Comment by TheMC47** [comment]
@slotThe it's better; we can close this, but I think #75  should be taken care of before the new release

**Comment by liskin** [comment]
This is relevant again. Peter Simons should be moved to the hall of fame and @slotThe, will you please add yourself?
