### ISSUE TITLE
Multiple monitor issue

### ISSUE THREAD

**Issue by MrBrokenHelm** [xmonad/xmonad#249]
### Problem Description

I have a laptop with a docking station, which has two outputs.
Currently my configuration is:
- Display 1, the laptop display
- Display 2, monitor 1
- Display 3, monitor 2

I am using autorandr to ensure the displays are setup correctly, however for unknown reason to me Display 2 and Display 3 are handled as a single workspace. Where I would expect that this is a seperate workspace per screen(/monitor).

When testing with another Window manager (bspwm) each work monitor is handled correctly. This problem only exist in Xmonad.

Currently I am stuck with this behaviour, however I have no idea how to fix it or if it is a bug.

### Configuration File

Not included as I don't use XMonad.Layout.IndependentScreens.

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
Can you please post the result of `ghc -e "Graphics.X11.openDisplay [] >>= Graphics.X11.Xinerama.getScreenInfo"`?
Or, if you're using stack to compile xmonad, `stack exec ghc --package X11 -- -e "Graphics.X11.openDisplay [] >>= Graphics.X11.Xinerama.getScreenInfo"`

**Comment by MrBrokenHelm** [comment]
Hi Liskin,

Hereby the output:
`[Rectangle {rect_x = 0, rect_y = 0, rect_width = 1920, rect_height = 1080},Rectangle {rect_x = 1920, rect_y = 0, rect_width = 1920, rect_height = 1080},Rectangle {rect_x = 3840, rect_y = 0, rect_width = 1920, rect_height = 1080}]
`
For the complete picture, this is the output of the xrandr:

_eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.01*+  59.93  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
DVI-I-2-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
DVI-I-1-1 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08_  


As I am using autorandr for setting up my displays upon login, the config:

_output DP1
off
output DP2
off
output HDMI1
off
output HDMI2
off
output VIRTUAL1
off
output eDP1
crtc 0
mode 1920x1080
pos 0x0
primary
rate 60.01
output DVI-I-2-2
crtc 4
mode 1920x1080
pos 1920x0
rate 60.00
output DVI-I-1-1
crtc 5
mode 1920x1080
pos 3840x0
rate 60.00_

**Comment by liskin** [comment]
That is truly weird, the Xinerama output looks okay and xmonad should just use that. Can you try if the issue persists when you reload xmonad (mod-q)? I remember that xrandr used to send several events so maybe this is some sort of race condition that is fixed by forcibly reloading the Xinerama state.

If that doesn't help, I'm really out of ideas and you may need to start adding debug prints all over the place. :-)

**Comment by MrBrokenHelm** [comment]
Hi Liskin,

Reloading is the first thing I did :), but I agree is seems like a wierd race condition.
However I believe this is, now, not caused by Xmonad. I have tested with my HDMI out port directly on the laptop, this works correct.
When using the docking station the problem occurs, so I will first spend some more time debugging that area.

**Comment by drewbarbs** [comment]
I'm also having issues where Xmonad (0.15) is not picking up the monitor layout from Xinerama on change.

**Edit:** I apologize, I too am starting to think my problems lie outside of xmonad. Setting a monitor "left-of" or "right-of" my laptop's display works well w/ xmonad. The issue arises when one monitor has a Y-offset. In my case, my left monitor is at 0x400 (400 pixel offset), but instead of all the windows being moved down accordingly, it's as though the top 400 pixels of the window are cut off, and there's a corresponding black bar on the bottom of my monitor. Both xmonad and feh fail to cover this area

**Comment by slotThe** [comment]
Closing this as "probably not xmonad related" for now
