### ISSUE TITLE
Feature request: see all windows in menu bar

### ISSUE THREAD

**Issue by R0binvd** [xmonad/xmonad#25]
Would be great if there was a option to show all the windows of the current workspace in the menu bar (xmobar or dzen2) istead of one. 

For example: |Firefox| urxvt pavucontrol. where firefox is the current active window.

**Comment by pjones** [comment]
This really has nothing to do with xmonad directly.  Maybe (just a tiny bit) it has something to do with xmonad-contrib.

There are plenty of task/status bars that can do what you are asking.  Getting xmobar or dzen2 to do the same would just require a bit of coding on your end to write out the information on the relevant pipe.

If you want some guidance on how to do that ask the mailing list or the IRC channel.

**Comment by liskin** [comment]
You may get some inspiration here: https://github.com/liskin/liskin-xmonad-conf/blob/master/xmonad.hs#L280

**Comment by geekosaur** [comment]
On Mon, Feb 8, 2016 at 4:07 PM, Peter J. Jones notifications@github.com
wrote:

> This really has nothing to do with xmonad directly. Maybe (just a tiny
> bit) it has something to do with xmonad-contrib.

That's overstating things a bit; it'd be an alternative DynamicLog (the
current one could only do it via ppExtras and some munging in ppOutput).

## 

brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by pjones** [comment]
I suppose in that case an issue should be opened with xmonad-contrib asking for a new DymanicLog function.  It could be based on the one suggested by @liskin.

**Comment by R0binvd** [comment]
Yea i found a way to do it with ppExtras (Thanks for your config), still think it should be inplemented by default.

**Comment by pjones** [comment]
Please feel free to submit a patch to xmonad-contrib.
