### ISSUE TITLE
cant import module

### ISSUE THREAD

**Issue by AlexisFinn** [xmonad/xmonad#262]
### Problem Description
So i'm trying to import a module to xmonad and it refuses to compile because it can't find the module.
But i'm doing everything i'm supposed to (i think), and ghc which to my understanding is what xmonad uses to compile by default works just fine, but xmonad wont compile

### Configuration File
```haskell
-- IMPORTS
import XMonad
import Data.Monoid
import System.Exit

import qualified XMonad.StackSet as W
import qualified Data.Map        as M

import Colors
```
### module
```haskell
module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/Images/Wallpapers/968167.png"

-- Special
background="#0f1010"
foreground="#e8eae5"
cursor="#e8eae5"

-- Colors
color0="#0f1010"
color1="#6DACA5"
color2="#7DC2BD"
color3="#9DA2A0"
color4="#A5A6A5"
color5="#D7A091"
color6="#B8C6C5"
color7="#e8eae5"
color8="#a2a3a0"
color9="#6DACA5"
color10="#7DC2BD"
color11="#9DA2A0"
color12="#A5A6A5"
color13="#D7A091"
color14="#B8C6C5"
color15="#e8eae5"
```
### case 1
I put the colors.hs file in ~/.xmonad/lib/colors.hs

result with `xmonad --recompile: 
```
Error detected while loading xmonad configuration file: /home/alexis/.xmonad/xmonad.hs

xmonad.hs:9:1: error:
    Could not find module `Colors`
    Use -v to see a list of the files searched for.
  |
9 | import Colors
  | ^^^^^^^^^^^^^

Please check the file for errors
```
result with `ghc -v xmonad.hs`
```
xmonad.hs:9:1: error:
    Could not find module ‘Colors’
    Locations searched:
      Colors.hs
      Colors.lhs
      Colors.hsig
      Colors.lhsig
  |
9 | import Colors
  | ^^^^^^^^^^^^^
```
### case 2
Ok, so it's looking for the file with an uppercase and it's not looking in ~/.xmonad/lib which to my understanding it should be but whatever.
So now `mv .xmodan/lib/colors.hs .xmonad/Colors.hs`

result with `xmonad --recompile`
```
xmonad.hs:9:1: error:
    Could not find module ‘Colors’
    Use -v to see a list of the files searched for.
  |
9 | import Colors
  | ^^^^^^^^^^^^^

Please check the file for errors.
```
result with `ghc -v xmonad`
```
compile: input file ./Colors.hs
*** Checking old interface for Colors (use -ddump-hi-diffs for more details):
[1 of 2] Compiling Colors           ( Colors.hs, Colors.o )
*** Parser [Colors]:
!!! Parser [Colors]: finished in 0.22 milliseconds, allocated 0.580 megabytes
*** Renamer/typechecker [Colors]:
!!! Renamer/typechecker [Colors]: finished in 28.86 milliseconds, allocated 9.962 megabytes
```
etc... it compiles just fine... wtf !!!
So i've been using i3 for a while now, but since i'm a computer programmer I thought i might like to delve a bit deeper into tiling window managers, but I must admit this is kind of putting me off, I mean I really want to use, configure and like xmonad but how come everything has to be so incredibly complicated or is there something I'm just not understanding somewhere ?

Please help me.

**Comment by AlexisFinn** [comment]
ps: 
- Ubuntu 20.04
- xmonad 0.15
- ghc 8.6.5

**Comment by geekosaur** [comment]
Xmonad overrides the default module path with -ilib, so you will get a
different result compiling manually unless you include that option.

**Comment by slotThe** [comment]
On Mon, Jan 11 2021 14:03, AlexisFinn wrote:
> result with `ghc -v xmonad`

As was already said, this is not quite how xmonad recompiles itself.
The real command [1] is more like

    ghc --make xmonad.hs -i -ilib -fforce-recomp -main-is main -v0 -o ~/.xmonad/xmonad.hs

Notice in particular `-i' and `-ilib'; this achieves what geekosaur was
talking about.

> So now `mv .xmodan/lib/colors.hs .xmonad/Colors.hs`

Perhaps you should try `~/.xmonad/lib/Colors.hs'?  We definitely do look
in the `lib' directory (see above). 


[1] https://github.com/xmonad/xmonad/blob/master/src/XMonad/Core.hs#L651

**Comment by AlexisFinn** [comment]
Ok, mooving it to lib and making having the filename exactly match the module name worked (I thought I had tried that before, but watever.)

Now if can only get my monitors to work properly, I think I have two haskell x11 libraries installed, probably one was pulled through apt, and the other through cabal.

So I have to reconfigure haskell by... doing a bunch of stuff. I swear this feels so complicated and convoluted just to get it up and working properly so that I can start hacking and breaking it.

I am having a bit of fun though, but boy this is a really steep learning curve, I hope haskell will come in handy .

**Comment by AlexisFinn** [comment]
Anyway many thanks for the swift reply and help. I can't wait to get xmonad up and running properly so I can start breaking it :wink:
