### ISSUE TITLE
Next release (v0.17.0)

### ISSUE THREAD

**Issue by slotThe** [xmonad/xmonad#264]
#### pre-release

* [x] prepare https://github.com/xmonad/xmonad-web/pull/40 to be mergeable (finalize the date, push to liskin.github.io/xmonad-web/, run linkchecker, …)
* [x] packdeps
* [x] version numbers in xmonad.cabal
* [x] version number and date in CHANGES.md
* [x] https://github.com/xmonad/xmonad-contrib/issues/393 pre-release

#### release

* [x] create release in GitHub UI, wait for CI
* [x] check candidate on Hackage and its docs
* [x] manually run the Haskell-CI workflow again to finalise the Hackage release
* [x] https://github.com/xmonad/xmonad-contrib/issues/393 release
* [x] merge https://github.com/xmonad/xmonad-web/pull/40
* [x] drop/change the "we're working hard on the 0.17 release" at https://github.com/sponsors/xmonad
* [x] announcement to `{xmonad,haskell-cafe}@haskell.org`
* [x] announcement to https://discourse.haskell.org/
* [x] announcement to Twitter
* [x] announcement to https://old.reddit.com/r/xmonad/

#### post-release
* [ ] maybe bump it in Stackage?

### Original issue body

> ### Problem Description
>
> I think that when xmonad/xmonad-contrib/issues/393 hits we should also
prepare another release of xmonad itself, so these two new versions may
be used with each other.
>
> There hasn't been a lot happening here, but in particular it would be
nice to include #258 (though I'm obviously biased there) in a release as
soon as possible.  I'm no expert on whether this should then be a minor
release or anything like that, so I'll leave that to people who actually
know what they are talking about.

**Comment by liskin** [comment]
:+1: 

It's worth noting that https://github.com/xmonad/xmonad/commit/735fb58f6cc2b52fcc2c8b24d5e1d3e127bae86e and https://github.com/xmonad/xmonad/commit/6dc1e319d177ac9aa6b9b6f6395077827ee7e1a3 are breaking changes that need an xmonad-contrib release first. Without these, we could just release the few fixes here separately. You all probably knew this but it's better to have it explicitly stated.

Also, I'd love to gather feedback on #260 from the Debian package maintainers (who were Cc:d on the mailing list thread) and resolve the stalemate here. This, I believe, will need @byorgey's involvement.

I also did hope that I'd finish https://github.com/xmonad/xmonad-contrib/pull/399 before [the xmonad-contrib release](https://github.com/xmonad/xmonad-contrib/issues/393), which would require an additional [X11 pull and release](https://github.com/xmonad/X11/pull/71), but my motivation evaporated recently, so I no longer feel it's fair to be holding the release. I do believe https://github.com/xmonad/xmonad-contrib/issues/396 is a real issue that will affect users, but it's totally fair to do a release with all the other fixes/improvements earlier.

**Comment by liskin** [comment]
https://xmonad.org/news/2021/10/27/xmonad-0-17-0.html
