### ISSUE TITLE
Cannot find module Prelude when compiling xmonad

### ISSUE THREAD

**Issue by Bietola** [xmonad/xmonad#269]
### Problem Description

xmonad misteriously stopped working after I installed ghcup, though trying to just remove the latter didn't seem to solve anything, so the error might be unrelated...

When botting the system in a tty and running `xmonad --recompile` I get this:

```
xmonad.hs:1:1: error:
    Could not find module ‘Prelude’
    There are files missing in the ‘base-4.14.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | import XMonad
  | ^

xmonad.hs:1:1: error:
    Could not find module ‘XMonad’
    There are files missing in the ‘xmonad-0.15’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | import XMonad
  | ^^^^^^^^^^^^^
```

Running `ghc-pkg check`, as instructed, produces the following:

```
Warning: haddock-interfaces: /usr/share/doc/stack/html/stack.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/stack/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-zlib/html/zlib.haddock doesn't exist or isn't a file
Warning: haddock-html: /usr/share/doc/haskell-zlib/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /usr/share/doc/haskell-zip-archive/html/zip-archive.haddock doesn't exist or isn't a file
[...] (this goes on for some time)
```

### Configuration File

I used to have a somewhat complicated config, but I substituted it with a simple one (as suggested). Still the problem persisted. Here is said simple config:

```haskell
import XMonad

main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
    NB. Only the part relating to issues.

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
    I decided not to do this, as the problem seems to be of a very foundamental nature... still I will do it with no problems if urged to.

**Comment by slotThe** [comment]
Presumably, `ghcup` installed ghc and cabal and perhaps now you have two global versions of that and they're getting confused.  Perhaps try uninstalling one of the two

**Comment by slotThe** [comment]
@Bietola did you end up fixing this?
