### ISSUE TITLE
Bluetooth Keyboard not working with Xmonad/Xmobar

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad#272]
### Problem Description

Describe the problem you are having, what you expect to happen
instead, and how to reproduce the problem.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
I'm trying to figure out why Xmonad and Xmobar stops my bt keyboard from working. On a fresh install of arcolinux -xmonad, pairing and using the keyboard via bt works fine. Only after changing the xmonad.hs does the bluetooth keyboard stop inputting and registering text. 
For example, I'm using someone else's config to start - https://gitlab.com/dwt1/dotfiles/-/blob/master/.xmonad/xmonad.hs

Why would tinkering with .hs stop bluetooth keyboards from registering input?

**Comment by slotThe** [comment]
> Why would tinkering with .hs stop bluetooth keyboards from registering input?

It wouldn't, normally, but I encourage you to find out what exactly is causing this by commenting out more and more of that config you linked until you find the culprit
