### ISSUE TITLE
Can't build xmonad-0.15 with ghc-9.0.1

### ISSUE THREAD

**Issue by l29ah** [xmonad/xmonad#280]
### Problem Description

```
[8 of 9] Compiling XMonad.Main      ( src/XMonad/Main.hs, dist/build/XMonad/Main.o, dist/build/XMonad/Main.dyn_o )

src/XMonad/Main.hs:64:21: error:
    Found a binding for the ‘@’ operator in a pattern position.
    Perhaps you meant an as-pattern, which must not be surrounded by whitespace
    Possibly caused by a missing 'do'?
   |
64 |               conf' @ XConfig { layoutHook = Layout l }
   |                     ^
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
This was fixed by 2a1a18023a15d13247148638edf29ca6bf9c3bce; you will need to build from git (or wait for 0.16).
