### ISSUE TITLE
Update the xmonad cheatsheet

### ISSUE THREAD

**Issue by slotThe** [xmonad/xmonad#287]
The [current cheatsheet](https://wiki.haskell.org/wikiupload/b/b8/Xmbindings.png) is really nice and still quite up-to-date; with the exception of `M-S-/` missing to bring up and `xmessage` window with the default keybindings.  It would be great to redo it for the next release! 

Indeed, even the [help function](https://github.com/xmonad/xmonad/blob/master/src/XMonad/Config.hs#L289) doesn't mention its own keybinding!  This could be fixed in tandem with the new picture. 

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  ~~- [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~

**Comment by liskin** [comment]
> Indeed, even the [help function](https://github.com/xmonad/xmonad/blob/master/src/XMonad/Config.hs#L289) doesn't mention its own keybinding! This could be fixed in tandem with the new picture.

Or it could be generated by a similar logic to GenerateManpage (I hinted to this in #285, #286). It's probably a waste of time but if anyone wants to play with that, I'd be happy to assist them.
