### ISSUE TITLE
`bindKeys` binds `KeySym` 0 to all unbound keys

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad#293]
`bindKeys` doesn't check that a `KeySym` is valid before looking up the keycode(s) it's bound to. In particular, `KeySym` 0 gets mapped to every unbound keycode, since they will have `NoSymbol` == 0 for their base `KeySym`.

This can most easily be reproduced using `statusBar` in xmonad-contrib, with `def` as the key-mapping function; this unexpectedly invokes the following instances:

```haskell
instance Default b => a -> b where def = const def
instance (Default a, Default b) => (a, b) where def = (def, def)
instance Default CInt where def = 0
```
thus producing a function which binds `toggleStruts` to the `(KeyMask,KeySym)` pair `(0,0)` (and demonstrating why `Default` is a dangerous abstraction). Note that it is not reliably possible to override `def` in this situation; the only thing we can do is try to avoid the aftermath, and I would expect that an inadvertent 0 `KeySym` is the most common error here anyway.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
This seems to actually be a regression since v0.12: https://github.com/xmonad/xmonad/commit/40cb12ce174ab55c5b2bbfeee2d966645a9121d4#diff-4b2452220f2cba63bd5acb25330c082ee87389fec382baa85bfb452b47242664L362 :-)

I'll put the `/= 0` back.
