### ISSUE TITLE
Black Screen After Xrandr Rotate

### ISSUE THREAD

**Issue by cmt227** [xmonad/xmonad#296]
### Problem Description

When I run `xrandr --output eDP-1 --rotate left` from a terminal, my screen goes black. I retain a mouse pointer that I can control via my trackpad, and its orientation has changed as I would expect from the rotate operation. However, no windows or background are displayed. I know that XMonad is still running, as I can exit with a keybinding, or from killing the process from another VT.

I don't think this is really an XMonad issue, as I also tried the same xrandr call from within Openbox, with the exact same results. Interestingly, on both XMonad and Openbox, I can use the arrow key and some blind typing to re-execute the xrandr call with "normal" instead of "left" and all of my windows reappear in the normal orientation. So obviously the window manager isn't crashing and all of my open programs are unaffected.

This makes me think this is more of an X11 issue or a kernel driver issue or something.

I start X with `startx` and my .xinitrc file is:

```
xcompmgr -c &
feh --bg-max ~/wallpapers/florida.jpg
xrdb -merge .Xresources
xmodmap ~/.xmodmap

exec xmonad 2> ~/err
```

After trying the rotate operation, `err` contains only one line: `User error (error in function getWindowAttributes)` which I researched and found a couple of related, unresolved issues:

https://github.com/xmonad/X11/issues/51

https://github.com/xmonad/xmonad-contrib/issues/146

But these seem to not be of the exact same cause / consequence.

One other interesting thing I noticed is that my Xorg.0.log file contains the lines:

```
(II) modeset(0): Allocate new frame buffer 1800x3200
(II) failed to add rotate fb
```

I also researched this and learned how to rotate the linux framebuffer using the file `/sys/class/graphics/fbcon/rotate` which works with no issues in the virtual terminal. I played around with this though, rotating the framebuffer, then running `startx`, then running the xrandr command, and ran into some super weird issues, culminating in a kernel panic that required a reboot.

I'm running up-to-date Arch Linux, and using the distribution's xmonad binary (version 0.13), installed using pacman. My computer is an HP Envy x360 from 2017, with a High DPI display (3200 x 1800 resolution). I believe I'm using the `i915` driver, and have an Intel HD Graphics 620 integrated graphics hardware. 

I've been an avid Linux user for many years now, and am looking for ways to contribute code and fixes, so I'm very interested in learning what is causing this issue and how I can fix it and help others too.

Thanks for any help you can give me.

**Comment by liskin** [comment]
If this is reproducible in openbox, it really is unlikely to be an issue with xmonad or the [Haskell X11 bindings](https://github.com/xmonad/X11/). I'll close it then. Doesn't seem you're getting any more helpful answers anyway.
