### ISSUE TITLE
configuration not compiling

### ISSUE THREAD

**Issue by Chaitanyabsprip** [xmonad/xmonad#298]
### Problem Description
I am not being able to use xmonad. It does start but it throws these errors when I run `xmonad --recompile`

```
XMonad will use ghc to recompile, because "/home/chaitanya/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/chaitanya/.xmonad/xmonad.hs

xmonad.hs:13:1: error:
    Could not load module ‘XMonad’
    It is a member of the package ‘xmonad-0.15-1Vwc5FoSZfx6Vsxacie0H7’
    which is unusable due to missing dependencies:
      X11-1.9.2-JuqOkXPYHHHDX5QPzci7Ja data-default-0.7.1.1-DVZWGRf90hqGebpGTaPvOV utf8-string-1.0.2-7pqBkplor7g1hjwTjVt3SV
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
13 | import XMonad
   | ^^^^^^^^^^^^^

xmonad.hs:14:1: error:
    Could not load module ‘XMonad.StackSet’
    It is a member of the package ‘xmonad-0.15-1Vwc5FoSZfx6Vsxacie0H7’
    which is unusable due to missing dependencies:
      X11-1.9.2-JuqOkXPYHHHDX5QPzci7Ja data-default-0.7.1.1-DVZWGRf90hqGebpGTaPvOV utf8-string-1.0.2-7pqBkplor7g1hjwTjVt3SV
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
14 | import qualified XMonad.StackSet as W
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Please check the file for errors.
```

### Configuration File

I am using the config file from here `https://archives.haskell.org/code.haskell.org/xmonad/man/xmonad.hs`

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by TheMC47** [comment]
Which distro are you on? How did you install xmonad?

**Comment by Chaitanyabsprip** [comment]
> Which distro are you on? How did you install xmonad?

I am on arch linux and I installed using pacman.

**Comment by TheMC47** [comment]
There isn't really much we can do here, arch kinda broke Haskell packaging. I suggest you build from the source with [stack](https://docs.haskellstack.org/en/stable/README/). Thew work-in-progress tutorial has an install guide here https://github.com/slotThe/xmonad/blob/new-tutorial/INSTALL.md

**Comment by Chaitanyabsprip** [comment]
okay, I'll try that. Thank you for assisting.

**Comment by Chaitanyabsprip** [comment]
```fish
[1 of 2] Compiling Main             ( /home/chaitanya/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/chaitanya/.stack/setup-exe-src/setup-mPHDZzAJ.o )

/home/chaitanya/.stack/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:
    Could not find module ‘Prelude’
    There are files missing in the ‘base-4.14.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | import Distribution.Simple
  | ^

/home/chaitanya/.stack/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:
    Could not find module ‘Distribution.Simple’
    There are files missing in the ‘Cabal-3.2.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | import Distribution.Simple
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

--  While building simple Setup.hs (scroll up to its section to see the error) using:
      /usr/bin/ghc-8.10.4 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-3.2.1.0 /home/chaitanya/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/chaitanya/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/chaitanya/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4
    Process exited with code: ExitFailure 1
```

I tried building it using stack as described in the link that you sent, and it gave me these errors. How can I resovle this?

**Comment by TheMC47** [comment]
Are you sure you're starting from scratch?

**Comment by Chaitanyabsprip** [comment]
yes, I uninstall everything xmonad related and removed ghc and stack and cabal, then installed stack, and cabal then I followed the instructions in the link.

**Comment by slotThe** [comment]
On Fri, May 28 2021 07:05, Chaitanya Sharma wrote:
> yes, I uninstall everything xmonad related and removed ghc and stack
> and cabal, then installed stack, and cabal then I followed the
> instructions in the link.

You probably only want to install stack (the statically linked version
at that)

**Comment by Chaitanyabsprip** [comment]
I redid the steps I mentioned earlier and could build xmonad. however, now I am facing this error
```
XMonad is recompiling and replacing itself with another XMonad process because the current process is called "xmonad" but the compiled configuration should be called "xmonad-x86_64-linux"
XMonad will use build script at "/home/chaitanya/.config/xmonad/build" to recompile.
XMonad recompilation process exited with success!
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  7
  Current serial number in output stream:  8
```

**Comment by slotThe** [comment]
This is usually the case when another window manager is already running.  How are you starting xmonad?

**Comment by Chaitanyabsprip** [comment]
I am running xmonad --recompile. I don't have other option, it's not showing up on my lightdm

**Comment by ixzh** [comment]
> I am running xmonad --recompile

I think he means at startup another window manager started. I quote the following [FAQ](https://wiki.haskell.org/Xmonad/Frequently_asked_questions#Setting_the_X_cursor) for your reference:

"X Error of failed request: BadAccess (attempt to access private resource denied)

This message seen at xmonad's stdout when starting xmonad means that another window manager is already running. If the other WM was started from a DE, you can use Util.Replace to have xmonad ask the other WM to exit before starting up. Note: If exiting your previously running wm would lead to your X session ending, then this method won't work.

Otherwise **refer to the appropriate page for starting xmonad instead of your other WM (Gnome, KDE).** "

which, in your case, is the lightdm configuration.

**Comment by Chaitanyabsprip** [comment]
![IMG_20210626_204400.jpg](https://user-images.githubusercontent.com/55058351/123517555-459dd000-d6bf-11eb-8aeb-6ee59119d9cc.jpg)
Thank you for bearing with a picture, but this is the error I get if run xmonad from tty

**Comment by geekosaur** [comment]
Xmonad doesn't start the server for you, like a desktop environment would. You would normally arrange for it to be run via `startx` (usually from `.xinitrc`) or from a display manager.

**Comment by ixzh** [comment]
> ![IMG_20210626_204400.jpg](https://user-images.githubusercontent.com/55058351/123517555-459dd000-d6bf-11eb-8aeb-6ee59119d9cc.jpg)
> Thank you for bearing with a picture, but this is the error I get if run xmonad from tty

not from command line...you will need to create an xmonad.desktop file in your xsession folder,  in that file you can execute xmonad (the xmonad path must be added/linked to $PATH)

**Comment by Dema** [comment]
I've created small package for myself that puts xsession file https://gist.github.com/Dema/62eb3713a149206bf89464abc9213fbf Be sure to change the username in `Exec=` field. I don't know if `$HOME` would work here, so I just hardcoded my username since I'm a single user

**Comment by slotThe** [comment]
@Chaitanyabsprip did you end up fixing this?

**Comment by Chaitanyabsprip** [comment]
No @slotThe

**Comment by slotThe** [comment]
So where do we stand?  What are your remaining issues?

**Comment by kim366** [comment]
I will leave my solution, it should be helpful to anyone using `xmonad-git` and `xmonad-contrib-git` from AUR: the issue is that these two packages don't get rebuilt when there is an update of haskelll packages. So the solution is not reinstalling haskell packages, but reinstalling xmonad. You can probably create a pacman hook for this, although I don't know how

**Comment by Mustang-ssc** [comment]
> I will leave my solution, it should be helpful to anyone using `xmonad-git` and `xmonad-contrib-git` from AUR: the issue is that these two packages don't get rebuilt when there is an update of haskelll packages. So the solution is not reinstalling haskell packages, but reinstalling xmonad. You can probably create a pacman hook for this, although I don't know how

Thanks for pointing out this, I just had to deal with it after some Haskell updates, for me this happened with the official repository Xmonad packages in Arch.

My approach to solve it was a bit more brute: Uninstall every Xmonad, Xmobar & Haskell packages, reboot, reinstall & recompile.

**Comment by ideasman42** [comment]
Ran into this problem too and `ghc-pkg recache` resolved it for me.

**Comment by ninetynin** [comment]
> Ran into this problem too and `ghc-pkg recache` resolved it for me.

![image](https://user-images.githubusercontent.com/91336664/207467852-e81b6722-388e-443c-a037-20dea7d8190e.png)
I still face the same issue even after doing that tho

**Comment by geekosaur** [comment]
This si a different problem from not finding packages. Where is your `xmonad.hs`?

**Comment by ninetynin** [comment]
> This si a different problem from not finding packages. Where is your `xmonad.hs`?

.xmonad/xmonad.hs that was the path im using 
and it was some other issue if figured it out it was because of missing build file that it was requesting and the imports werent there [stackoverflow-link](https://stackoverflow.com/questions/50119141/cannot-compile-xmonad-hs-file#:~:text=Here%20is%20my%20command%20history%20if%20it%20is%20of%20any%20help%3A) this helped me out
