### ISSUE TITLE
Help with Broken XMonad after Pacman Update

### ISSUE THREAD

**Issue by psygo** [xmonad/xmonad#301]
### Problem Description

> This issue was [first posted on r/xmonad](https://www.reddit.com/r/xmonad/comments/nkayyu/help_with_broken_xmonad_after_pacman_update/), but, since I couldn't find anything that worked &mdash; I do appreciate the help there though! &mdash;, I decided to repost it here. Sorry if this feels like too much copying, but I really wish my dear XMonad work once again!

I'm using Artix mainly with Pacman as a package manager. Today, after about a week, I've upgraded many packages and it ended up breaking XMonad.

This is the message I get from `xmonad --recompile -v`:

```error
XMonad is recompiling and replacing itself another XMonad process because the current process is called "xmonad" but the compiled configuration should be called "xmonad-x86_64-linux"
XMonad will use ghc to recompile, because "/home/philippe/.xmonad/build" does not exist.
XMonad skipping recompile because it is not forced (e.g. via --recompile), and neither xmonad.hs nor any *.hs / *.lhs / *.hsc files in lib/ have been changed.
/home/philippe/.xmonad/xmonad-x86_64-linux: error while loading shared libraries: libHSxmonad-contrib-0.16-KKfUmtIonstICqbgIKQKYh-ghc8.10.4.so: cannot open shared object file: No such file or directory
```

I've tried a ton of solutions people mentioned on the internet &mdash; so far I've spent more than 3 hours trying to debug this &mdash;, among them, notably:

- `cabal install --lib xmonad-contrib`, which had solved some issues I've had with XMonad in the past.
- Removing and reinstalling Stack, GHC, Cabal, and XMonad itself.
- Installing XMonad through Stack.
    - This ended up giving me the same error message, the difference is that I had to execute `~/.local/bin/xmonad --recompile -v` instead.

Does anyone have an idea of how to solve this? I've had problems with upgrades of XMonad before, but never anything close to this &mdash; I love Haskell as a language, but its package management is one of the most disgusting, overcomplicated pieces of software I've ever experienced in my 10+ years of programming life.

### Configuration File

I don't know how posting my config will help, since it was working without errors for months. But here it is:

> My complete dotfiles can be found [here](https://github.com/psygo/dotfiles).

```haskell
--------------------------------------------------------------------------------
import Data.List

import XMonad
import System.Exit

import XMonad.Actions.CycleWS
import qualified XMonad.Actions.DynamicWorkspaceOrder as DWO

import qualified XMonad.StackSet as W
import qualified Data.Map        as M

import XMonad.Prompt
import XMonad.Prompt.Shell
import XMonad.Prompt.FuzzyMatch

import XMonad.Layout.ThreeColumns
import XMonad.Layout.Accordion
import XMonad.Layout.Tabbed
--------------------------------------------------------------------------------
main = xmonad def
        { modMask            = mod4Mask
        , terminal           = "kitty"
        , borderWidth        = 3
        , normalBorderColor  = "#dddddd"
        , focusedBorderColor = "ff0000"
        , workspaces         = ["1", "2", "3", "4", "5", "6", "8", "9"]
        , keys               = myKeys
        , layoutHook         = myLayout
        }
--------------------------------------------------------------------------------
myXPConfig :: XPConfig
myXPConfig = def
      { font                = "xft:Fira Code:style=Bold:pixelsize=16"
      , bgColor             = "#292d3e"
      , fgColor             = "#d0d0d0"
      , bgHLight            = "#c792ea"
      , fgHLight            = "#000000"
      , borderColor         = "#535974"
      , promptBorderWidth   = 1
      , position            = CenteredAt { xpCenterY = 0.3, xpWidth = 0.3 }
      , height              = 40
      , historySize         = 256
      , historyFilter       = id
      , defaultText         = []
      , showCompletionOnTab = False
      , searchPredicate     = fuzzyMatch
      , alwaysHighlight     = True
      , maxComplRows        = Nothing
      }
--------------------------------------------------------------------------------
myLayout = tiled
       ||| Mirror tiled
       ||| Full
       ||| threeCol
       ||| Accordion
       ||| Mirror Accordion
  where
     tiled    = Tall nmaster delta ratio
     nmaster  = 1
     ratio    = 1/2
     delta    = 1/100
     threeCol = ThreeCol 1 (3/100) (1/2)
--------------------------------------------------------------------------------
myKeys conf@XConfig {XMonad.modMask = modm} = M.fromList
    [
      --------------------------------------------------------------------------
      -- Basic
      ((modm .|. shiftMask, xK_Return), spawn $ XMonad.terminal conf)
    , ((modm .|. shiftMask, xK_c     ), kill)
    , ((modm              , xK_b     ), spawn brave)
    , ((modm              , xK_f     ), spawn ferdi)
    , ((modm              , xK_t     ), spawn qutebrowser)
    , ((modm              , xK_e     ), spawn emacs)
    , ((modm              , xK_p     ), shellPrompt myXPConfig)
    , ((modm              , xK_d     ), spawn deadKeysLayout)
    , ((modm              , xK_u     ), spawn usLayout)
    , ((modm              , xK_r     ), spawn ranger)
    , ((modm .|. shiftMask, xK_f     ), spawn krusader)
    , ((modm              , xK_Print ), spawn screenshot)
      --------------------------------------------------------------------------
      -- Window Management
    , ((modm .|. shiftMask, xK_space ), sendMessage NextLayout)
    , ((modm,               xK_Tab   ), windows W.focusDown)
    , ((modm .|. shiftMask, xK_Tab   ), windows W.focusUp)
    , ((modm,               xK_j     ), windows W.focusDown)
    , ((modm,               xK_k     ), windows W.focusUp)
    , ((modm,               xK_m     ), windows W.focusMaster)
    , ((modm,               xK_Return), windows W.swapMaster)
    , ((modm,               xK_h     ), sendMessage Shrink)
    , ((modm,               xK_l     ), sendMessage Expand)
    , ((modm              , xK_comma ), sendMessage (IncMasterN 1))
    , ((modm              , xK_period), sendMessage (IncMasterN (-1)))
      --------------------------------------------------------------------------
      -- Workspace and Screen Management
    , ((modm .|. shiftMask, xK_j     ), DWO.moveTo Next HiddenWS)
    , ((modm .|. shiftMask, xK_k     ), DWO.moveTo Prev HiddenWS)
    , ((modm .|. shiftMask, xK_l     ), nextScreen)
    , ((modm .|. shiftMask, xK_h     ), prevScreen)
    , ((modm .|. shiftMask, xK_Down  ), DWO.shiftTo Next HiddenWS)
    , ((modm .|. shiftMask, xK_Up    ), DWO.shiftTo Prev HiddenWS)
    , ((modm .|. shiftMask, xK_Right ), shiftNextScreen)
    , ((modm .|. shiftMask, xK_Left  ), shiftPrevScreen)
      --------------------------------------------------------------------------
      -- XMonad Management
    , ((modm .|. shiftMask, xK_q     ), io exitSuccess)
    , ((modm              , xK_q     ), spawn restartRecompile)
      --------------------------------------------------------------------------
    ]

-- Commands
restartRecompile = "xmonad --recompile; xmonad --restart"
deadKeysLayout   = "setxkbmap -layout us -variant intl; xmodmap ~/.Xmodmap"
usLayout         = "setxkbmap -layout us; xmodmap ~/.Xmodmap"
ranger           = "kitty -e ranger"
brave            = "brave"
firefox          = "firefox"
emacs            = "emacs"
ferdi            = "ferdi"
krusader         = "krusader"
qutebrowser      = "qutebrowser"
screenshot       = "scrot ~/Pictures/Screenshots/screenshot.png"
--------------------------------------------------------------------------------
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
I can't comment on the error as I don't use Arch—it's some dark dynamic
linking magic I'm sure.  However:

On Tue, May 25 2021 06:04, Philippe Fanaro wrote:
> Pacman

Personally, I would recommend that anyone using Arch (or a derivative
thereof) install xmonad via a stack project.  I know you said that you
already tried via stack, but it sounded more like `stack install
xmonad`, which is not what I'm saying.

Uninstall every Haskell package except for stack (even GHC; stack will
download the correct version by itself) and then follow the instructions
in the new INSTALL.md [1].  I believe there's also a `stack-static`
package for a statically linked stack; might be useful.

> I love Haskell as a language, but its package management is one of the
> most disgusting, overcomplicated pieces of software I've ever
> experienced in my 10+ years of programming life.

Frankly, it's not Haskell's fault that Arch decided to break its package
management; blame them instead.

[1]: https://github.com/xmonad/xmonad/blob/883143fd5895e0da4ee8e50722e3011cf30e2ca6/INSTALL.md

**Comment by psygo** [comment]
If I end up then, like you said, managing everything through Stack, is there a way of locking Pacman away from managing Haskell modules so that I don't accidentally/unexpectedly break them in the future?

**Comment by slotThe** [comment]
On Tue, May 25 2021 06:57, Philippe Fanaro wrote:
> If I end up then, like you said, managing everything through Stack, is
> there a way of locking Pacman away from managing Haskell modules so
> that I don't accidentally/unexpectedly break them in the future?

If you only install stack-static then that should be the only Haskell
package on your system—Pacman can't break things it doesn't know
anything about.  No more having to update 300 packages because one
dependency got bumped

**Comment by psygo** [comment]
Ok, I've managed to wipe out everything Haskell-related in my system. Then I reinstalled all the essentials through `stack` &mdash; I used the [`curl` recommended version](https://docs.haskellstack.org/en/stable/install_and_upgrade/) on their site; is that better or worse than [`stack-static`](https://aur.archlinux.org/packages/stack-static/)? &mdash;, but now, when trying to do `xmonad --recompile` once again, I get:

```error
XMonad will use ghc to recompile, because "/home/philippe/.xmonad/build" does not exist.
xmonad: ghc: runProcess: runInteractiveProcess: exec: inappropriate type (Not a directory)
```

(I do have an `~/.xmonad/build/` folder by the way...)

This looks like a noobie error, but I don't remember ever getting it. Does anyone know what's going on? I couldn't find any help on the internet about it so far...

**Comment by geekosaur** [comment]
If you're using stack now, you need a build script. The one at https://github.com/xmonad/xmonad-testing/blob/master/build-scripts/build-with-stack.sh should do as a start, at least once customized as necessary for your setup (see the comments within it).

**Comment by liskin** [comment]
This should answer the recompilation question in more detail: https://github.com/slotThe/xmonad/blob/new-tutorial/INSTALL.md#tell-xmonad-how-to-recompile-itself

**Comment by liskin** [comment]
(I do have some ideas how to make that process less complicated, but it'll take a while until I actually get to implementing them. 😞)

**Comment by psygo** [comment]
Thank you guys for helping me with this, it helped a bunch.

In the end, @liskin's link to [this tutorial](https://github.com/slotThe/xmonad/blob/new-tutorial/INSTALL.md#tell-xmonad-how-to-recompile-itself) made the difference. Everything finally compiled. However, I still got errors for when calling `exec xmonad` directly on `.xinitrc`, I had to use the other `exec $HOME/.xmonad/xmonad-x86_64-linux` in order to truly make it work.

**Comment by psygo** [comment]
I ended up creating [a StackOverflow post](https://stackoverflow.com/q/67710115/4756173) with the distilled solution, hopefully it will help someone in the future.

**Comment by liskin** [comment]
What errors were you getting with `exec xmonad`? If our tutorial doesn't work, we'd surely like to update it instead of hoping other poeple find your StackOverflow post. ;-)

**Comment by psygo** [comment]
I'm not sure if I'm what I'm getting is truly the responsibility of XMonad, and I haven't been able to find a predictable way of getting the error yet. If I find out more information about this topic I'll come back here. :)

Your tutorial does work though, at least the last mentioned method.

**Comment by geekosaur** [comment]
I wouldn't be surprised if `~/.local/bin` isn't in `$PATH` since only Fedora configures `$PATH` to anything other than `/bin:/usr/bin`.
