### ISSUE TITLE
Could'nt match expected type. I don't know this much

### ISSUE THREAD

**Issue by ashincoder** [xmonad/xmonad#302]
### Problem Description

I added the following lines to my xmonad config. This maybe a stupid issue but I am 0 in haskell.It says:

```
xmonad.hs:178:5: error:
    • Couldn't match expected type ‘([Char], m6 ())
                                    -> ([Char], m5 ())
                                    -> ([Char], m4 ())
                                    -> ([Char], m3 ())
                                    -> ([Char], m2 ())
                                    -> ([Char], m1 ())
                                    -> ([Char], m0 ())
                                    -> (String, X ())’
                  with actual type ‘([Char], m7 ())’
    • The function ‘("M-d", spawn "dmenu_run")’
      is applied to 7 arguments,
      but its type ‘([Char], m7 ())’ has none
      In the expression:
        ("M-d", spawn "dmenu_run")
          ("M-c", spawn "dmconf") ("M-x", spawn "dmlogout")
          ("M-p", spawn "dmkill") ("M-m", spawn "dmsounds")
          ("M-S-w", spawn "dmwifi") ("M-o", spawn "todo")
          ("<XF86AudioLowerVolume>",
           spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%")
      In the expression:
        [("M-j", windows W.focusDown), ("M-k", windows W.focusUp),
         ("M-S-j", windows W.swapDown), ("M-S-k", windows W.swapUp), ....]
    |
178 |     ("M-d", spawn "dmenu_run")
```

### Configuration File

-------------------- Dmenu and Scripts --------------------
    -- Dmenu Run
    ("M-d", spawn "dmenu_run")
    -- Dmenu Conf Editor
    ("M-c", spawn "dmconf")
    -- Dmenu Logout
    ("M-x", spawn "dmlogout")
    -- Dmenu Program Killer
    ("M-p", spawn "dmkill")
    -- Dmenu Music Player
    ("M-m", spawn "dmsounds")
    -- Dmenu wifi menu
    ("M-S-w", spawn "dmwifi")
    -- Dmenu todo menu
    ("M-o", spawn "todo")

Thank you in advance for explaining

**Comment by ashincoder** [comment]
The block saying config is the one reproducing the issues

**Comment by geekosaur** [comment]
You're missing commas between all the keybindings, so it thinks you're applying them to each other.

**Comment by ashincoder** [comment]
Thank you so much. I should've noticed that. Thank you
