### ISSUE TITLE
stack requires upgrade or xmonad + contrib installation fails

### ISSUE THREAD

**Issue by instantepiphany** [xmonad/xmonad#303]
### Problem Description

The readme and installation instructions ask users to install stack via apt.

On my just upgraded PopOS (Ubuntu based) system, installing stack via apt gave version `1.9.3.1`. This version failed when I ran `stack init` - it tried to retrieve the `.yaml` files from the wrong URL. Running `stack upgrade` resolved the problem.

Should a section be added to INSTALL.md (https://github.com/xmonad/xmonad/blob/master/INSTALL.md#install-stack) suggesting users run this command to ensure they have the latest (therefore likely working) stack version?

I would create the PR myself but have never used stack before, so maybe I am missing something here.

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - ~[ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~

**Comment by slotThe** [comment]
I think this is a very good point—didn't realize that even Ubuntu packages stack version that are that old!

> I would create the PR myself but have never used stack before, so maybe I am missing something here.

I'd say go for it!  Running `stack upgrade` first sounds entirely reasonable to me
