### ISSUE TITLE
tings-manager

### ISSUE THREAD

**Issue by psiayn** [xmonad/xmonad#305]
### Problem Description

Describe the problem you are having, what you expect to happen
instead, and how to reproduce the problem.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
@psiayn Is there an actual issue lurking here or was this a mistake? :)

**Comment by psiayn** [comment]
Oh I'm sorry I kinda killed my window manager and looks like it pasted something. Sorry 😓
