### ISSUE TITLE
Xmobar config < 0.17 should be without ewmhFullscreen in tutorial

### ISSUE THREAD

**Issue by kaistian** [xmonad/xmonad#307]
### Problem Description

The tutorial on line [464](https://github.com/xmonad/xmonad/blame/b14b3ffcecfbc11d7c8df221693f627ddf3eb182/TUTORIAL.md#L464) have the following configuration for <0.17
`main = xmonad . ewmhFullscreen . ewmh =<< xmobar myConfig`
shouldn't that be
`main = xmonad . ewmh =<< xmobar myConfig`
since <0.17 doesn't have `ewmhFullscreen`?

**Comment by slotThe** [comment]
Indeed it should, well spotted.  Contributions welcome!

**Comment by slotThe** [comment]
Fixed by 28637d0db78650c0e58c9d550d5aaf5a03d61847, closing
