### ISSUE TITLE
Native recompilation support for stack/cabal installed XMonad

### ISSUE THREAD

**Issue by MuhammedZakir** [xmonad/xmonad#310]
A cli option for this would be nice. Simple support is enough. That is, for example, `xmonad --tool stack`, will run `stack ghc ...` instead of `ghc ...`. If a user needs to compile in a different way (e.g. with different flags), they can always use build script.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment]
As I recently commented in https://github.com/xmonad/xmonad/issues/199#issuecomment-853477664, a good first step would be to detect `stack.yaml` next to `xmonad.hs` and invoke `stack ghc …` automatically if it's there. We could possibly also add a command-line option to specify the path to `stack.yaml` to use, but I'm not at all sure how useful that would be.

For cabal, I believe we should just recommend the use of `--package-env=$HOME/.xmonad/` (https://github.com/xmonad/xmonad/issues/199#issuecomment-609433196). I haven't tested this yet though.

**Comment by MuhammedZakir** [comment]
That's enough. :-)

---

In build script usage example in `INSTALL.md`, rather than suggesting `xmonad-ARCH` executable, isn't it better to add a test in build script?

```
if [ ./xmonad.hs -ot ./"$1" ]; then
    return 0
fi
```
