### ISSUE TITLE
Submap and LiftIO $ runProcessWithInput Problem

### ISSUE THREAD

**Issue by NnAsUnKnOwn** [xmonad/xmonad#313]
Hello i have an action in `additionalKey` that works perfectly but when i decided to put the same in a submap it simply doesn't work, i'll put my .cabal file because i had problems trying xmonad-testing, no compiling errors

this is the action :
liftIO ( runProcessWithInput "dmenu" (["-p", "Desea Salir?"]) "si\nno\n" >>= putStrLn )
                                           
Thanks!!

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

--------------------------------------------------------------------------------                                                                                          
import System.Exit
import XMonad
import XMonad.Config.Desktop
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.ManageHelpers
import XMonad.Layout.BinarySpacePartition (emptyBSP)
import XMonad.Layout.NoBorders (noBorders)
import XMonad.Layout.ResizableTile (ResizableTall(..))
import XMonad.Layout.ToggleLayouts (ToggleLayout(..), toggleLayouts)
import XMonad.Prompt
import XMonad.Prompt.ConfirmPrompt
import XMonad.Prompt.Shell
import XMonad.Util.EZConfig


import qualified Data.Map as M
import qualified XMonad.Actions.Submap as SM
import XMonad.Util.Run

--------------------------------------------------------------------------------                                                                                          
main = do
  spawn "xmobar" -- Start a task bar such as xmobar.                                                                                                                      
  xmonad $ desktopConfig
    { modMask    = mod4Mask -- Use the "Win" key for the mod key                                                                                                          
    , manageHook = myManageHook <+> manageHook desktopConfig
    , layoutHook = desktopLayoutModifiers $ myLayouts
    , logHook    = dynamicLogString def >>= xmonadPropLog
    }
    `additionalKeys` -- Add some extra key bindings:                                                                                                                      
      [ ((mod4Mask, xK_q    ), confirmPrompt myXPConfig "exit" (io exitSuccess))
      , ((mod4Mask, xK_x    ), shellPrompt myXPConfig)
      , ((mod4Mask, xK_space), sendMessage (Toggle "Full"))
      , ((mod4Mask, xK_F6   ), liftIO ( runProcessWithInput "dmenu" (["-p", "Desea Salir?"]) "si\nno\n" >>= putStrLn ) )                                                  
      , ((mod4Mask, xK_o    ), SM.submap . M.fromList $
          [
            ((0, xK_q ), liftIO ( runProcessWithInput "dmenu" (["-p", "Desea Salir?"]) "si\nno\n" >>= putStrLn ) )
          ] )
      ]

myLayouts = toggleLayouts (noBorders Full) others
  where
    others = ResizableTall 1 (1.5/100) (3/5) [] ||| emptyBSP

myXPConfig = def
  { position          = Top
  , alwaysHighlight   = True
  , promptBorderWidth = 0
  , font              = "xft:monospace:size=9"
  }

myManageHook = composeOne
  [ className =? "Pidgin" -?> doFloat
  , className =? "XCalc"  -?> doFloat
  , className =? "mpv"    -?> doFloat
  , isDialog              -?> doCenterFloat
  , transience
  ]
```

.cabal file
```yaml
cabal-version:       >=1.10                                                                                                                                               
name:                my-xmonad
version:             0.1.0.0
synopsis:            My tiling xmonad
license-file:        LICENSE
author:               XXXX
maintainer:        XXXXX
copyright:           GNU/GPL V3
build-type:          Simple

executable my-xmonad
  main-is:             xmonad.hs
  build-depends:       base >= 4.12
                     , containers
                     , data-default
                     , fuzzy
                     , monoid-subclasses
                     , mtl
                     , process
                     , unix
                     , utf8-string
                     , X11 >= 1.9.2
                     , X11-xft >= 0.3.1
                     --, X11-extras >= 0.4
                     , xmobar >= 0.36
                     , xmonad >= 0.15
                     , xmonad-contrib >= 0.15
                     ,text
  default-language:    Haskell2010
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment]
~~I can reproduce this, even with `safeSpawn` and variants.  A somewhat smaller test file:~~

``` haskell
import XMonad
import XMonad.Util.EZConfig
import XMonad.Util.Run

import qualified Data.Map              as M
import qualified XMonad.Actions.Submap as SM

--------------------------------------------------------------------------------
main = xmonad $ def
  `additionalKeysP`
    [ ("M-s", spawn "dmenu")
    , ("M-o", SM.submap . M.fromList $ [((0, xK_q), safeSpawn "dmenu" [])])
    ]
```

~~This is pretty weird, since all the submap does is issue some keyboard grabs (which it releases anyways before executing the action)...  Substituting `safeSpawn` for `spawn` works, however, so I'm guessing there is some unix process magic going on here~~

EDIT: No, see below

**Comment by liskin** [comment]
Trying to reproduce this with `spawn "dmenu"` or `safeSpawn "dmenu"` is a bit silly as dmenu expects a list of items on stdin. `spawn` happens to "work" because it redirects stdin from /dev/null, but `safeSpawn` doesn't, so if you're running `xmonad` from a terminal (as I guess you are when testing stuff like this), that `dmenu` waits for input. Absolutely do feel free to push a patch that flips `safeSpawn` over to `xfork` to avoid this confusion in the future.

This would mean that `safeSpawn "dmenu"` shouldn't work even outside the submap. You may want to try that first to check if what I'm saying is correct. And if it is, then I guess this simple reproducer is invalid and we'll need to look for another one.

**Comment by geekosaur** [comment]
Both of you are correct, but in different senses. @liskin is correct about your reproducer, but running a windowed program with `runProcessWithInput` or `runProcessWithInputAndWait` is inviting problems. I'd suspect the only involvement of `SubMap` is just happening to change timing enough to trigger problems.

**Comment by slotThe** [comment]
Ah of course, I must have still been sleeping when writing that reply...  Switching both occurences with the original `runProcessWithInput` certainly does reproduce the problem with the minimal config though. 

@geekosaur in what sense is it inviting problems?  Can anything be done about this or is it more fundamental?

**Comment by geekosaur** [comment]
The documentation for it says "Returns the output". This means it runs dmenu while the main loop isn't running, so really xmonad would be expected to hang unless dmenu itself sets `override_redirect`. So it's even worse than I remembered and `Submap` shouldn't matter.

**Comment by liskin** [comment]
So, what's "the problem" exactly? The original report says "simply doesn't work", but what does that mean? I don't think xmonad hanging is problematic here: I've been using dmenu/rofi in a similar fashion for years, and yeah, xmonad might not be running for a second or two until I finish my interaction with dmenu/rofi, but that's never been a problem. So what is it?

**Comment by NnAsUnKnOwn** [comment]
ohh thank you all for your help, as i understand reading your replies it might not be a problem .
if there is another method to accomplish to evaluate an output in a submap i would appreciate, i've thinking in XMonad.Hooks.ServerMode
for now i just simply want to do io (exitWith ExitSuccess)

Greetings!

**Comment by liskin** [comment]
> as i understand reading your replies it might not be a problem

I don't think we understood each other. I didn't mean “there might not be a problem”, I meant “your description isn't clear, can you please elaborate on what were your reproduction steps, what did you expect to happen and what happened instead?”

**Comment by liskin** [comment]
Anyway, I managed to reproduce the issue using the following minimal config:

```haskell
import XMonad
import XMonad.Config.Bluetile

import qualified Data.Map as M
import qualified XMonad.Actions.Submap as SM
import XMonad.Util.EZConfig
import XMonad.Util.Run

main :: IO ()
main = xmonad $ bluetileConfig{terminal = "urxvt"} `additionalKeys`
    [ ((mod4Mask, xK_p), liftIO (runProcessWithInput "dmenu" (["-p", "Desea Salir?"]) "si\nno\n" >>= putStrLn))
    , ((mod4Mask, xK_o), SM.submap . M.fromList $
        [ ((0, xK_q), liftIO (runProcessWithInput "dmenu" (["-p", "Desea Salir?"]) "si\nno\n" >>= putStrLn))
        ])]
```

Here's a proposed fix: https://github.com/xmonad/xmonad-contrib/pull/586

(If any of you had said “dmenu starts but does not seem to receive any input” I'd probably figure this out earlier, as I wouldn't need to isolate the reproducer first, which was enough for my procrastination to kick in. 😃)

**Comment by rambip** [comment]
I have almost the same issue: dmenu works outside submap, dmenu_run works inside submap, but I can't get a string from dmenu (or rofi, same issue).

The issue can't come from stdandard input of rofi, because when I try do to `spawn "rofi -show run" ` inside submap this doesn't work.

I will post a reproducible example soon.

**Comment by liskin** [comment]
@rambip Are you running a recent enough version that includes https://github.com/xmonad/xmonad-contrib/pull/586?

**Comment by NnAsUnKnOwn** [comment]
it works my fiends , greetings
