### ISSUE TITLE
Add a flake.nix file so that xmonad can be easily used as a flake in nix-builds

### ISSUE THREAD

**Issue by colonelpanic8** [xmonad/xmonad#315]
Is this something the maintainers would be open to? I have one ready to go.

**Comment by slotThe** [comment]
On Sat, Jul 31 2021 00:20, Ivan Malison wrote:
> Is this something the maintainers would be open to? I have one ready
> to go.

Sounds good to me :+1:; tighter nix integration is always nice.

**Comment by liskin** [comment]
Yeah, we'll sure be happy to merge it. 👍

Just one little thing: correct me if I'm wrong but I think none of the active xmonad maintainers are very familiar with Nix, nor use Nix to install xmonad, so it'd be nice to clarify the future maintenance of those files. Like either say it's contributed, no guarantees, submit fixes if anything goes wrong, or mention a specific GitHub username(s) or e-mail(s) that should be pinged in case of problems and PRs.

Oh and if you'd be willing to submit another PR with a GitHub Actions workflow that tested this, that would be awesome, too. Not necessary, but certainly nice to have. :-)
(Doesn't need to be perfect, I'll be happy to take a draft PR and polish it, but right now I know absolutely nothing about Nix, have no idea where to start, and tbh I lack motivation as well, Nix isn't really compatible with the way I want my computer to be set up.)

**Comment by colonelpanic8** [comment]
> so it'd be nice to clarify the future maintenance of those files.

I can volunteer to maintain them (I will be doing so anyway, since I've actually already had these flake files for a while and I actively use them to compile my xmonad config).    

> Nix isn't really compatible with the way I want my computer to be set up

I seriously doubt that. I think you probably mean NixOS which is not the same as the Nix package manager. You can download the Nix package manager on any distro and use it as much or as little as you want.
```
curl -L https://nixos.org/nix/install | sh
```

is all you need to do to install.

Then with  this PR merged, all you would need to do is run `nix build` in the repositiory to build xmonad.

**Comment by colonelpanic8** [comment]
> I know absolutely nothing about Nix, have no idea where to start, and tbh I lack motivation as well,

As I said, nix the package manager should be extremely easy to use with the flake file I provided. If you want to build and test that the flake works you can either just `nix build` or run `nix develop` which will give you a shell with cabal, and appropriate ghc compiler and all the dependencies needed to compile xmonad. At that point simply running cabal new-build should do the trick.

**Comment by liskin** [comment]
> ```
> curl -L https://nixos.org/nix/install | sh
> ```

I'm not going to run any `curl | sh`. I may try `apt install nix-bin nix-setup-systemd` later in a VM, but I guess you already see where this is going. I'm not going to like that nix will download binaries not signed by Debian gpg keys (not saying they aren't trustworthy, just that _I_ don't trust them), and I'm also not going to like that nix-built stuff won't share libraries with the rest of my system (or will it?).

Anyway, this is not the place to do advocacy for Nix. Different people have different needs. If you're okay with maintaining the flake, please mention it in the file. Thanks.

**Comment by colonelpanic8** [comment]
> stuff won't share libraries with the rest of my system (or will it?)

nix installed libraries will share libraries between themselves, but not with non nix-installed things.

> Anyway, this is not the place to do advocacy for Nix.

Right, sorry, I wasn't trying to advocate, so much as point out that it should be quite easy to install nix and verify without the need to understand very much.

> nix will download binaries not signed by Debian gpg keys

Won't be signed by Debian gpg, but will be signed by nix keys.

> I'm not going to run any curl | sh. I may try apt install nix-bin nix-setup-systemd

Sure I was just giving a platform agnostic way to get nix, but I understand your hesitancy. `apt install nix-bin nix-setup-systemd` is indeed a better way to do it, but I had no way of knowing what linux distro you are using.

> If you're okay with maintaining the flake, please mention it in the file

of course.
