### ISSUE TITLE
Is there a way to bind ONLY the Super Key to a Command

### ISSUE THREAD

**Issue by Kjvthomas** [xmonad/xmonad#317]
### Problem Description

I've been trying different methods for hours and my issue is I would like to set my super key to bring up my dmenu

### LINE 3 is where i'd like to bind SUPER to open the Dmenu###
myKeys conf@(XConfig {XMonad.modMask = modMask}) = M.fromList $
  ----------------------------------------------------------------------
1 -- SUPER + FUNCTION KEYS

2  [ ((modMask, xK_e), spawn $ "atom" )
3  , ((modMask, xK_d), spawn $ "dmenu_run -c -bw 2 -l 20 -g 4 -p 'Run'" )

### Checklist
I have read alot of different supporting documents and the Xmonad Wiki on Arch

  - [ X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
  - 
My config works great, however whenever I try a trick like modMask, 0, or 0, modMask, or anything else, I can't figure out how to simply bind the SUPER key to dmenu

  - [ X] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

Right now my Xmonad works great, dmenu pulls up with the flags when I press SUPER d, but I would like to change it to just SUPER to pull up the dmenu

Thanks for your help!

**Comment by geekosaur** [comment]
`(0, xK_Super)`

This will require importing `Graphics.X11.Types` to get the definition of `xK_Super`. It will also be confusing at best, especially if you're also using the Super key as a modifier.

**Comment by Kjvthomas** [comment]
> `(0, xK_Super)`
> 
> This will require importing `Graphics.X11.Types` to get the definition of `xK_Super`. It will also be confusing at best, especially if you're also using the Super key as a modifier.

You, sir, are a gentleman and a scholar. I wanted my Super Key to act as a traditional "windows" or rofi menu button.

Thank you for your help, this worked, I added **import Graphics.X11.Types** to the top, and then I used **xK_Super_L** to bind the dmenu key I setup. Everything works great!
