### ISSUE TITLE
Xmonad Prompt auto creating .xmonad folder inside $HOME. Conflicts with my config inside $HOME/.config/xmonad

### ISSUE THREAD

**Issue by rhysday** [xmonad/xmonad#319]
### Problem Description

When using Xmonad prompts it automatically creates a .xmonad folder inside $HOME which conflicts with my config inside $HOME/.config/xmonad. It only started doing this after a fresh reinstall of Arch.

My configuration file worked perfectly before.

**Comment by geekosaur** [comment]
Were you by any chance running xmonad from git before? This has been fixed in git xmonad, which is nearing release.

**Comment by rhysday** [comment]
Installed Xmonad from pacman. Should I use xmonad-git from the AUR? I remember I had problems with the git version. Haskell packages were messing up or something. Was beyond my scope to try and get working.

**Comment by rhysday** [comment]
My whole config breaks with xmonad-git. Guess I will need to figure it out and change everything

**Comment by geekosaur** [comment]
https://github.com/xmonad/xmonad-contrib/blob/master/CHANGES.md may be of interest.

**Comment by rhysday** [comment]
Ah when I installed xmonad-git I didn't install the git version of xmonad-contrib. Now everything is fine and I shall close this. Thank you
