### ISSUE TITLE
MonadFail instance

### ISSUE THREAD

**Issue by Icelandjack** [xmonad/xmonad#32]
See 1.5 Adapting old code in https://wiki.haskell.org/MonadFail_Proposal

**Comment by byorgey** [comment]
@Icelandjack can you clarify exactly what you are proposing here?  We don't currently have any implementations of `fail` to adapt.  Are you suggesting to add an instance of `MonadFail` for the `X` monad?  If so, what should it do?  And what would it be used for?

**Comment by pjones** [comment]
Closing as unresponsive.

**Comment by geekosaur** [comment]
fwiw this *may* become relevant (you will be using it any time you use a pattern match in do notation, and currently we get the default which is `error` --- this affects, for example, things like `Just _nbc <- ...` in core). But this has not landed and might yet change, so it's actually a bit early to try to adapt.

**Comment by dimpase** [comment]
It apparently is a problem now, with ghc 8.8.5 on Gentoo Linux I get
```
[ 94 of 268] Compiling XMonad.Util.Invisible ( XMonad/Util/Invisible.hs, dist/build/XMonad/Util/Invisible.o )

XMonad/Util/Invisible.hs:36:23: error:
    • Could not deduce (MonadFail (Invisible m))
        arising from a use of ‘fail’
      from the context: Monad m
        bound by the instance declaration
        at XMonad/Util/Invisible.hs:35:10-53
    • In the expression: fail "Read Invisible"
      In the expression: (fail "Read Invisible", s)
      In the expression: [(fail "Read Invisible", s)]
   |
36 |     readsPrec _ s = [(fail "Read Invisible", s)]
   |                       ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by MichielDerhaeg** [comment]
@dimpase This problem is related to xmonad-contrib.
It looks like this is fixed already: https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/src/XMonad.Util.Invisible.html#Invisible

**Comment by dimpase** [comment]
@MichielDerhaeg - thanks, I've alerted Gentoo people to upgrade (they are still on xmonad-contrib 0.15)
