### ISSUE TITLE
firefox crashes xmonad display?

### ISSUE THREAD

**Issue by ixzh** [xmonad/xmonad#321]
### Problem Description

I use xmonad based on voidlinux xfce, and enabled hardware acceleration for Firefox. The video acceleration is working, but firefox crashes quite often. when it crashes, sometimes other existing windows also get affected (pixelate?) like the screenshot of alacritty below. yet new windows display correctly.

![image](https://user-images.githubusercontent.com/14981695/129276451-9a6a9854-fa83-4d08-ab26-3f742e50265b.png)

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

my config file is [here](https://github.com/xmonad/xmonad-contrib/issues/565#issuecomment-873424923)

OS: voidlinux xfce
Graphic card: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
va driver:  libva-intel-driver with environment variable LIBVA_DRIVER_NAME=i965.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
What other windows does this happen with? Alacritty is something of a special case since it also uses hardware acceleration, and DRI might be being left in an odd state.

**Comment by ixzh** [comment]
> What other windows does this happen with? Alacritty is something of a special case since it also uses hardware acceleration, and DRI might be being left in an odd state.

Hi, polybar also gets pixelated,...I have to relaunch it.  Again I think the tile is inaccurate as xmoand is not crashed, but I need to recompile to refresh the display.

**Comment by liskin** [comment]
Does recompilation alone help? I don't see how xmonad could have anything to do with this. Perhaps restarting xmonad restarts the compositor in your case? Or you log off and thus restart X? Anyway, this looks more like a bug in Mesa or the i915 driver in the kernel.

**Comment by geekosaur** [comment]
Hm, if recompile/relaunch works then mod-n might also work?

For what it's worth, I use hardware acceleration with Chrome and it appears to be stable if memory-leaky.

**Comment by ixzh** [comment]
> Hm, if recompile/relaunch works then mod-n might also work?
> 
> For what it's worth, I use hardware acceleration with Chrome and it appears to be stable if memory-leaky.

I heard chrome got no hardware acceleration? How to enable it?

**Comment by ixzh** [comment]
> Does recompilation alone help? I don't see how xmonad could have anything to do with this. Perhaps restarting xmonad restarts the compositor in your case? Or you log off and thus restart X? Anyway, this looks more like a bug in Mesa or the i915 driver in the kernel.

yes, xmonad is functioning as new windows display correctly. it's not xmonad related :(

**Comment by geekosaur** [comment]
Hardware acceleration is hidden under Advanced / System.

**Comment by ixzh** [comment]
> Hardware acceleration is hidden under Advanced / System.

hi i'm on voidlinux and can only install chromium, the settings seems not to work as youtube playing 1080 video takes 50-80% CPU. in firefox it is about 10-20% CPU usage, so I guess video acceleration is not working with these settings in chromium?

![image](https://user-images.githubusercontent.com/14981695/129283391-7f0b9e62-4bb0-4770-9730-a3eacda16d9a.png)

**Comment by ixzh** [comment]
I close the issue as it is not xmonad related :(

**Comment by geekosaur** [comment]
It is possible that chromium is detecting whatever version of driver is causing the crash and refusing to use it.

**Comment by liskin** [comment]
Hardware acceleration doesn't mean video decoding acceleration, I'm afraid.

To enable video decoding acceleration, one has to jump through many more hoops: https://github.com/liskin/dotfiles/blob/9e6404a4914aad38afe14e82ac5669a41bb80fdb/bin/google-chrome#L14-L19 + correct vaapi libs. And they keep changing the command-line flags from version to version.

(But we really are getting off-topic here.)

**Comment by ixzh** [comment]
> Hardware acceleration doesn't mean video decoding acceleration, I'm afraid.
> 
> To enable video decoding acceleration, one has to jump through many more hoops: https://github.com/liskin/dotfiles/blob/9e6404a4914aad38afe14e82ac5669a41hbb80fdb/bin/google-chrome#L14-L19 + correct vaapi libs. And they keep changing the command-line flags from version to version.
> 
> (But we really are getting off-topic here.)

haha thanks for the tip on all the chromium flags! i will try out:)

**Comment by ixzh** [comment]
> Hardware acceleration doesn't mean video decoding acceleration, I'm afraid.

is video decoding  a case of hardware acceleration? can you explain a bit

**Comment by liskin** [comment]
I just meant that that particular toggle in Chrome Settings / Advanced / System isn't concerned with video decoding acceleration.
