### ISSUE TITLE
Failed to compile when using symlinked `stack.yaml`

### ISSUE THREAD

**Issue by MuhammedZakir** [xmonad/xmonad#322]
### Problem Description

Failed to compile when using **symlinked** `stack.yaml`.

Error shown is:
```
Errors detected while compiling xmonad config: /home/name/.config/xmonad/xmonad.hs
$ stack build --silent

Please check the file for errors.
```

P.S. IMHO, the above message should mention the path of error file.

### Steps to Reproduce

This is my setup:

* ls -l ~/.config/xmonad/
```
drwxr-xr-x 3 name name 4096 Aug 17 11:06 old
lrwxrwxrwx 1 name name   46 Aug 17 19:58 stack.yaml -> /home/name/dev/haskell/xmonad/stack.yaml
-rw-r--r-- 2 name name 3125 Jul 28 11:08 xmonad.hs
```

* ls -l ~/dev/haskell/xmonad/
```
-rwxrwxr-- 1 name name 2250 Aug 17 20:18 stack.yaml
-rw------- 1 name name  539 Aug 17 20:18 stack.yaml.lock
drwxr-xr-x 9 name name 4096 Aug 17 20:34 xmonad
drwxr-xr-x 8 name name 4096 Aug 17 20:33 xmonad-contrib
-rw-r--r-- 2 name name 3125 Jul 28 11:08 xmonad-old.hs
```

I am able to solve this if I symlink `xmonad` and `xmonad-contrib` to `~/.config/xmonad/` (but that isn't needed?).

### Configuration File

Nil.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration (latest commit at the time of posting)
    - [x] With `xmonad` version (git): be1d2269cec3f62f2fc6d3aab3151473cb07d2dc
    - [x] With `xmonad-contrib` version (git): a9ad56be11eac5a0fb97d3e016ea410da952db6d

**Comment by MuhammedZakir** [comment]
Unrelated: I get these warning for xmessage.

```
Warning: locale not supported by C library, locale unchanged
Warning: Missing charsets in String to FontSet conversion
Warning: Cannot convert string "-*-fixed-medium-r-normal-*-18-*-*-*-*-*-*-*,-*-fixed-*-*-*-*-18-*-*-*-*-*-*-*,-*-*-*-*-*-*-18-*-*-*-*-*-*-*" to type FontSet
```

**Comment by TheMC47** [comment]
> I am able to solve this if I symlink `xmonad` and `xmonad-contrib` to `~/.config/xmonad/` (but that isn't needed?).

It seems that this is something we can't control and that it's related to how stack finds the needed packages. I might be wrong, I don't know that much about stack

**Comment by liskin** [comment]
Oh, right, that stack invocation needs the - -stack-yaml flag as well. I forgot that, I'm an idiot. Thanks for catching this.

I'll be out of any computer with a keyboard for a week but the fix should be easy and I should be able to review it and merge it, if you manage to open a PR.

**Comment by liskin** [comment]
Oh and the locale warning is something we might actually need to worry about. :-/

**Comment by MuhammedZakir** [comment]
Adding `--stack-yaml` works. I have opened a PR with that fix.

---

In the error message, the "file" in `Please check the file for errors` is ambigous. Does it mean error log, or XMonad config? If it's error log, then it's path should also be shown. If it's config, then the message should be changed.

---

> Oh and the locale warning is something we might actually need to worry about. :-/

This is the output of `locale -a` on mine
```
C
en_IN
en_IN.utf8
en_US.utf8
POSIX
```

**Comment by liskin** [comment]
Thanks again for catching the locale warnings—they were a serious issue indeed: https://github.com/xmonad/xmonad/commit/30719202b9daa80fe1ab37293a4615b93cb042d9
