### ISSUE TITLE
error page opens at startup, but nothing is written

### ISSUE THREAD

**Issue by errordotfiles** [xmonad/xmonad#324]
hello, every time I open xmonad, it also opens an error page, but 'inside there is nothing written.
![cos](https://user-images.githubusercontent.com/82203506/129933509-0faed2ab-89d3-428b-b974-272bf54ae509.png)

**Comment by TheMC47** [comment]
How can someone possibly figure out what's going wrong, just from that picture? You need to help us help you

> ### Steps to Reproduce
> 
> Give detailed step-by-step instructions on how to reproduce the problem.
> 
> ### Configuration File
> 
> Please include the smallest _full_ configuration file that reproduces
> the problem you are experiencing:
> 
> ```haskell
> module Main (main) where
> 
> import XMonad
> 
> main :: IO ()
> main = xmonad def
> ```
> 
> ### Checklist
> 
>   - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
> 
>   - I tested my configuration
>     - [ ] With `xmonad` version XXX (commit XXX if using git)
>     - [ ] With `xmonad-contrib` version XXX (commit XXX if using git)
>

**Comment by slotThe** [comment]
Can you try `xmonad --recompile` in a terminal and see if there is any
output?

**Comment by MuhammedZakir** [comment]
This happens when there are compilation errors. Probably because they are passed as plain string and not escaped?

**Comment by liskin** [comment]
@errordotfiles did you perhaps see any "Warning: Non-character code(s) in source." errors in .xsession-errors or wherever your xmonad error output goes?
