### ISSUE TITLE
Recent broadcastMessage change breaks Tabbed

### ISSUE THREAD

**Issue by l29ah** [xmonad/xmonad#329]
### Problem Description

When clicking on tabs with a mouse, the tabbar misbehaves and sometimes focuses the previously-focused tab back shortly after the click.
183e14725faff625e7dd94983362659809e40d51 is the first bad commit
@wygulmage 

### Steps to Reproduce

Have a XMonad.Layout.Tabbed layout, click on the tabs.

### Configuration File

```haskell
import XMonad
import XMonad.Layout.Tabbed

main = xmonad $ def { layoutHook = tabbedBottomAlways shrinkText def }
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [ ] With `xmonad` version XXX (commit XXX if using git)
    - [x] With `xmonad-contrib` version 0c6fdf4

**Comment by liskin** [comment]
Uh, this is probably what https://github.com/xmonad/xmonad/commit/11d76e284c474faabd43f276d057ffbbc29dd7a1 was meant to prevent. Now that I think about it, there is indeed still a difference between the old impl and the new one: the old, being n², did update the X monad state after processing each workspace, so the next workspace's handleMessage would immediately see the results of the previous actions. That's just a quick guess though, will need to investigate this further.

Anyway, good catch, thanks!

**Comment by liskin** [comment]
Oh, it's not just that the X monad state was updated after each workspace handles the message, more importantly any changes to the WindowSet made during handling of the message were not thrown away, which it now is. Hm, so I guess we're just reverting #291.

**Comment by slotThe** [comment]
> Oh, it's not just that the X monad state was updated after each workspace handles the message, more importantly any changes to the WindowSet made during handling of the message were not thrown away, which it now is. Hm, so I guess we're just reverting #291.

Sounds like it... :/  We better put a note somewhere this time _why_ things are done the way they are
