### ISSUE TITLE
Questions about development workflow with Cabal and NIx

### ISSUE THREAD

**Issue by solomon-b** [xmonad/xmonad#332]
I wasn't sure where to ask this question so I settled on writing it as an issue. I use Nixos and have setup a cabal project very similar to @IvanMalison that uses the XMonad flake for running my personal xmonad setup.

For working on xmonad, I use the Nix Flake to setup up a dev environment and I use cabal for building during development. This works great and is my typical Haskell workflow. 

However where it starts to fall apart is when when trying to test my changes. I end up having to push my changes to my personal fork of xmonad, update the flake lock on my local system's flake, and then rebuild my local system. This means rebuilding `xmonad` and my personal xmonad project from scratch every single time I want to test a change. 

To make matters worse, if I use the `--restart` flag with my personal xmonad project after a rebuild, it appears to restart the old artifact rather then the newly built one. This means I actually have to logout and login to my machine in order to test any changes I make to xmonad.

This has become a really terrible workflow and I suspect I am going about this the wrong way.

So my questions are:

1) Is it possible to at the very least make restart xmonad with a new build artifact without logging out? 
2) Is it possible on nixos to use cabal build artifacts instead of artifacts from the nix store to launch xmonad? I would only want this during my development cycle and then to be able to go back to an ordinary nix artifact when using my computer otherwise.
3) Is there some other better solutions I am not thinking of?

**Comment by colonelpanic8** [comment]
> For working on xmonad, I use the Nix Flake to setup up a dev environment and I use cabal for building during development. This works great and is my typical Haskell workflow.

Wait so here you are talking about working on the xmonad library itself, not your personal config, correct?

> 1. Is it possible to at the very least make restart xmonad with a new build artifact without logging out?

Yes. This is what I was doing until recently. Basically, what you'll need to do is add this function:

``` haskell
restartEventHook e@ClientMessageEvent { ev_message_type = mt } = do
  a <- getAtom "XMONAD_RESTART"
  if mt == a
    then XMonad.Operations.restart "imalison-xmonad" True >> return (All True)
    else return $ All True
restartEventHook _ = return $ All True
```

to your event hook.

You'll also want to avoid all the command line handling logic used in the xmonad function and use launch instead of that like
``` haskell
dirs <- getDirectories
(`launch` dirs)
```



> * Is it possible on nixos to use cabal build artifacts instead of artifacts from the nix store to launch xmonad? I would only want this during my development cycle and then to be able to go back to an ordinary nix artifact when using my computer otherwise.
> * Is there some other better solutions I am not thinking of?

Yes, this is essentially what #330 offers. Basically you need to make a nix flake specifically for xmonad. with that pr integrated, xmonad will know how to recompile using a flake.



> I end up having to push my changes to my personal fork of xmonad, update the flake lock on my local system's flake

I think with what I have suggested, at least the push part can be skipped. Another option would be to use the already existing custom build script support. This would allow you to use an arbitrary script to generate the binary to use for xmonad.

**Comment by solomon-b** [comment]
> Wait so here you are talking about working on the xmonad library itself, not your personal config, correct?

Yes that is correct, although similar issues present themselves when working on a personal config.

> Yes. This is what I was doing until recently. Basically, what you'll need to do is add this function:

How do I trigger a restart when using this event hook? I currently do it with:
```
      spawn "xmonad-solomon --restart"
```
Would that still work or is there another way to trigger a restart?

> Yes, this is essentially what #330 offers. Basically you need to make a nix flake specifically for xmonad. with that pr integrated, xmonad will know how to recompile using a flake.

I am using a nix flake for my [personal config](https://github.com/ssbothwell/nixos-config/blob/main/flakes/xmonad/flake.nix). Is this what you mean here?

Will #330 allow me to rebuild my personal xmonad config without having to do a `nixos-rebuild switch`?

> I think with what I have suggested, at least the push part can be skipped. Another option would be to use the already existing custom build script support. This would allow you to use an arbitrary script to generate the binary to use for xmonad.

If I'm understanding you correctly, it sounds like there are a couple options to improve the story on relaunching xmonad after a build, but that I will still have to push my changes of xmonad and xmonad-contrib to github before being able to build them locally with my personal config for testing.

How are you suggesting to skip the push?

Also `nix build` takes way longer then cabal because it can't do incremental builds. Obviously it has other benefits, otherwise  I wouldn't be using nix. However, in a development cycle it would be really amazing if we could use cabal build artifacts to build an xmonad config and launch it. Maybe the custom build script support you mentioned would allow for that?

**Comment by colonelpanic8** [comment]
> Will #330 allow me to rebuild my personal xmonad config without having to do a `nixos-rebuild switch`?

yes

> but that I will still have to push my changes of xmonad and xmonad-contrib to github before being able to build them locally with my personal config for testing.

no, so first of all, there are ways to overcome needing to push. I use git submodules for xmonad and xmonad-contrib and then point the flake at them like so: https://github.com/IvanMalison/dotfiles/blob/32a736621f956844b21e604a2ad3789b6b09c7c1/dotfiles/config/xmonad/flake.nix#L5

Second of all, you can make your particular restart handling do just about whatever you want.



> However, in a development cycle it would be really amazing if we could use cabal build artifacts to build an xmonad config and launch it. Maybe the custom build script support you mentioned would allow for that?

Right I get what you are saying here. If you use my first suggestion you can easily do this, so long as there is some way to make the cabal artifact be whatever your xmonad binary name is on the path that xmonad was started with.

More generaly, I think something like `XMonad.Operations.restart "imalison-xmonad"` is what needs to be called in order to have xmonad restart itself in place.

**Comment by solomon-b** [comment]
Thanks, this is all really helpful.

> no, so first of all, there are ways to overcome needing to push. I use git submodules for xmonad and xmonad-contrib and then point the flake at them like so: https://github.com/IvanMalison/dotfiles/blob/32a736621f956844b21e604a2ad3789b6b09c7c1/dotfiles/config/xmonad/flake.nix#L5

Can you specify branches with that `path:` syntax? I like to use feature branches for tracking what i'm working on.

> Right I get what you are saying here. If you use my first suggestion you can easily do this, so long as there is some way to make the cabal artifact be whatever your xmonad binary name is on the path that xmonad was started with.

This sounds like an ideal solution, but I'll try merging #330 into my local `xmonad` for now. Any ideas when we can get that merged into `master`?

> More generaly, I think something like XMonad.Operations.restart "imalison-xmonad" is what needs to be called in order to have xmonad restart itself in place.

I don't know much about `ClientMessageEvent`. How do you fire those events?

**Comment by geekosaur** [comment]
On Mon, Sep 27, 2021 at 5:08 AM Solomon Bothwell ***@***.***>
wrote:

> know much about ClientMessageEvent. How do you fire those events?
>
>
That's what `xmonad --restart` does.

-- 
brandon s allbery kf8nh
***@***.***

**Comment by colonelpanic8** [comment]
> Can you specify branches with that path: syntax? I like to use feature branches for tracking what i'm working on.

There's no need. You can just checkout the branch and rebuild. There is no need to commit, as well.
