### ISSUE TITLE
Please update Hackage package.

### ISSUE THREAD

**Issue by alissa-tung** [xmonad/xmonad#338]
In this line [there](https://hackage.haskell.org/package/xmonad-0.15/docs/src/XMonad.Main.html#local-6989586621679086676) contains an error syntax for `as-pattern` and it was already been fixed, which caused GHC 9.0.1 build to fail when using `xmonad` as a Cabal dependency.

**Comment by geekosaur** [comment]
We have a release scheduled for the end of the month, and are in the process of some pre-release cleanups currently.

**Comment by alissa-tung** [comment]
Okay, sorry. I am wondering if is there a way to patch it at build time, or whether is convenience to merely update a bug fix?

**Comment by geekosaur** [comment]
We generally recommend to run from git, since cabal has no ready way to apply patches to a package it downloads from hackage.

**Comment by alissa-tung** [comment]
> We generally recommend to run from git, since cabal has no ready way to apply patches to a package it downloads from hackage.

thx for helping
