### ISSUE TITLE
Emacs window clips to half its size in xmonad

### ISSUE THREAD

**Issue by cgogolin** [xmonad/xmonad#34]
I am not sure if this is an xmonad or an emacs bug, but as it is really disruptive for my workflow I appreciate any help.

After starting Emacs in xmonad (v0.11, Debian testing package version 0.11.1-4) on some workspace with emacs -Q, switching to another work space, and then switching back to Emacs, the Emacs window becomes "cropped". It then still occupies the same space as a window in the window manager and the menu bar still extends to the full width of the window, but emacs only draws its "content" in the upper left quarter of the available space and all emacs windows are resized as if the whole
window had been resized.

The problem is 100% reproducible and happens independently of the used xmonad layout and even in floating mode. Sometimes more than one switch to another work space is required to trigger the behavior. When the window size changes (by switching to a different layout for example) Emacs again draws in the whole available space.

I am happy to provide additional details if you tell me what to do.

**Comment by geekosaur** [comment]
That's going to be a problem with emacs, I'm afraid. Or with a library it's using; I have actually seen the reverse issue (window contents too large until I force a relayout) in some Chrome releases, suggesting a bug in some Gtk+ versions where some (canvas?) windows are not properly sized.

**Comment by cgogolin** [comment]
Ok, thanks. Does anyone know how I can gather more information on this, so that I can file a useful bugreport against emacs/gtk? Can you reproduce this behavior with your xmonad setup?

**Comment by ghost** [comment]
I'm using xmonad and Emacs on Debian unstable, and I cannot reproduce the problem.

Could it be X-driver-related?

**Comment by cgogolin** [comment]
Maybe. I am on an intel system. Stupid question: Is there an easy way to replace the currently running xmonad session with one that uses the standard config?

**Comment by cgogolin** [comment]
Heureka! It is a GTK bug: To reproduce the problem try running Emacs as with `export GDK_SCALE=2; export GDK_DPI_SCALE=0.5; emacs`. I am doing these exports in my `.xinitrc`, as my screen resolution is very high. Please feel free to close this issue. Specifically running Emacs as `export GDK_SCALE=1; export GDK_DPI_SCALE=1; emacs` works around the problem.
