### ISSUE TITLE
Mod4+Hjkl

### ISSUE THREAD

**Issue by etherbiswas** [xmonad/xmonad#353]
I am sorry I am a noob, 
I want vim like window focusing functionality but can seem to find an option for focus left an right i had used i3 and that was the default behavior i dont know where to get support so i came here. Sorry! Please help if you can. Thank you!

**Comment by geekosaur** [comment]
You're looking for https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Layout-WindowNavigation.html in `xmonad-contrib`. There are close to 300 contrib modules at this point; you can find almost anything you want there.

**Comment by etherbiswas** [comment]
Damn bruh, looks like its true you guys are really responsive. Thanks a lot for helping 🙂👍

**Comment by slotThe** [comment]
There is also X.A.Navigation2D[1], which may or may not work better with
your specific setup (and has a few options to fine tune moving behaviour)

[1]: https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Actions-Navigation2D.html

**Comment by etherbiswas** [comment]
I am about to do a clean arch install, i dont think i will be "experimental" probably gonna try the first solution! Thanks a lot, really appreciate everyone's help.

**Comment by etherbiswas** [comment]
Hello

**Comment by etherbiswas** [comment]
I tried the directional navigation thing as expected i am having problems

**Comment by geekosaur** [comment]
What kind of problems? Can you attach your config and whatever error messages you are getting? (Use &lt;pre&gt; around them to keep Github from mangling them.)

**Comment by etherbiswas** [comment]
<pre>main = xmonad $ navigation2D def
                             (xK_Up, xK_Left, xK_Down, xK_Right)
                             [(mod4Mask,               windowGo  ),
                              (mod4Mask .|. shiftMask, windowSwap)]
                             False
              $ def
-- Directional navigation of windows
   , ((modm,                 xK_l), windowGo R False)
   , ((modm,                 xK_h ), windowGo L False)
   , ((modm,                 xK_k   ), windowGo U False)
   , ((modm,                 xK_j ), windowGo</pre>

**Comment by etherbiswas** [comment]
Do you think there is a problem in this or i am doing something completely wrong?
I am sorry if this is stupid!
What happens is if i press Mod+h or l it resizes rather than the new expected behavior

**Comment by geekosaur** [comment]
The `Directional navigation of windows` and following lines would go inside a `keys` definition appended to the second `def`. This would look something like:

<pre>
              $ def { keys (XConfig {modMask = modm}) = M.fromList [
                  ((modm,                 xK_l), windowGo R False)
                , ((modm,                 xK_h ), windowGo L False)
                , ((modm,                 xK_k   ), windowGo U False)
                , ((modm,                 xK_j ), windowGo D False)
                ]
              }
</pre>

(I also corrected the definition for M-j, as it appears to have been cut off.)

I am surprised you didn't get an error popup from trying to compile this with mod-q.

**Comment by etherbiswas** [comment]
All i saw was use spaces and not tabs

**Comment by geekosaur** [comment]
Mmm, actually I did that wrong I think, it'd wipe out all the other keydefs :(

**Comment by geekosaur** [comment]
I'm guessing you're running 0.15 then, where we had the error/warning handling wrong. You may want to use `xmonad --recompile` in a terminal window instead, then `xmonad --restart` once it compiles. But *don't* use what I suggested above because it's not quite right; it will compile but leave you without the standard key definitions.

**Comment by etherbiswas** [comment]
thats what i will try

**Comment by etherbiswas** [comment]
can i have your xmonad.hs?

**Comment by etherbiswas** [comment]
i just copied it mine from distro tubes becuz i dont know any haskell

**Comment by etherbiswas** [comment]
XMonad will use ghc to recompile, because "/home/ether/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/ether/.xmonad/xmonad.hs

xmonad.hs:70:15: error:
    parse error on input ‘$’
    Perhaps you intended to use TemplateHaskell
   |
70 |               $ def { keys (XConfig {modMask = modm}) = M.fromList [
   |               ^

Please check the file for errors.

xmonad: xmessage: executeFile: does not exist (No such file or directory)

**Comment by geekosaur** [comment]
<pre>
main = xmonad $ navigation2D def
                             (xK_Up, xK_Left, xK_Down, xK_Right)
                             [(mod4Mask,               windowGo  ),
                              (mod4Mask .|. shiftMask, windowSwap)]
                             False
              $ def { keys conf@(XConfig {modMask = modm}) = M.fromList [
                  ((modm,                 xK_l), windowGo R False)
                , ((modm,                 xK_h ), windowGo L False)
                , ((modm,                 xK_k   ), windowGo U False)
                , ((modm,                 xK_j ), windowGo D False)
                ] <+> keys conf
              }
</pre>

**Comment by etherbiswas** [comment]
XMonad will use ghc to recompile, because "/home/ether/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/ether/.xmonad/xmonad.hs

xmonad.hs:78:28: error: parse error on input ‘(’
   |
78 |               $ def { keys (XConfig {modMask = modm}) = M.fromList [
   |                            ^

Please check the file for errors.

xmonad: xmessage: executeFile: does not exist (No such file or directory)

**Comment by etherbiswas** [comment]
same error slightly differnet

**Comment by geekosaur** [comment]
My own `xmonad.hs` is pretty complicated and would probably scare you away. :) Also it doesn't use any of the window navigation imports, since I generally run Tabbed and only temporarily have multiple windows.

**Comment by etherbiswas** [comment]
why?

**Comment by etherbiswas** [comment]
does that mean this isnt for me, i mean i love tilling
the point of using a tilling window manger is to tile if i cant even do that what am i supposed to do? are you saying i am too dumb to get this to work? i guess i will have to use dwm then?

**Comment by geekosaur** [comment]
No, I'm just saying I have a very complicated `xmonad.hs`. https://github.com/geekosaur/xmonad.hs/blob/pyanfar/xmonad.hs is a slightly out of date version of it; I need to commit my current one on a new branch.

**Comment by etherbiswas** [comment]
bruh?

**Comment by etherbiswas** [comment]
i should probably use urs cus dts is huge!

**Comment by Ahanaf-Ether** [comment]
<pre>XMonad will use ghc to recompile, because "/home/ether/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/ether/.xmonad/xmonad.hs

xmonad.hs:78:28: error: parse error on input ‘(’
   |
78 |               $ def { keys (XConfig {modMask = modm}) = M.fromList [
   |                            ^

Please check the file for errors.

xmonad: xmessage: executeFile: does not exist (No such file or directory)</pre>

**Comment by etherbiswas** [comment]
hey can you add the tilling fucntionality so i can just copy urs, please?

**Comment by etherbiswas** [comment]
how do i check xmonad version? xmonad --version?

**Comment by geekosaur** [comment]
I believe I said multiple times you should *not* try to build what I posted before.

<pre>
import XMonad
import XMonad.Actions.Navigation2D
import qualified Data.Map as M

main = xmonad $ navigation2D def
                             (xK_Up, xK_Left, xK_Down, xK_Right)
                             [(mod4Mask,               windowGo  ),
                              (mod4Mask .|. shiftMask, windowSwap)]
                             False
              $ def { keys = \conf@(XConfig {modMask = modm}) -> M.fromList [
                  ((modm,                 xK_l), windowGo R False)
                , ((modm,                 xK_h ), windowGo L False)
                , ((modm,                 xK_k   ), windowGo U False)
                , ((modm,                 xK_j ), windowGo D False)
                ] <+> keys conf conf
              }
</pre>

This is tested locally and compiles. You do need to make sure you have both `xmonad` and `xmonad-contrib` installed, though.

**Comment by etherbiswas** [comment]
xmonad 0.15

**Comment by etherbiswas** [comment]
i do have xmonad-contrib

**Comment by geekosaur** [comment]
The point of xmonad is you can customize it to your own tastes. I have rather particular tastes (and use xmonad hooked into the MATE desktop environment); you should really configure your own to your tastes.

**Comment by etherbiswas** [comment]
ok, mate-de? is that still maintained?

**Comment by etherbiswas** [comment]
i mean for hybrid desktop i would use kde though its bloated

**Comment by etherbiswas** [comment]
alright thanks, i dont think xmonad is for noobs like me i am going with dwm because it is easy to patch

**Comment by etherbiswas** [comment]
I got it to work!!

**Comment by etherbiswas** [comment]
I changed my mind xmonad seems awesome, but can    
Plz help me with one more thing?

**Comment by etherbiswas** [comment]
<pre>import XMonad
import XMonad.Actions.Navigation2D
import qualified Data.Map as M

main = xmonad $ navigation2D def
                             (xK_Up, xK_Left, xK_Down, xK_Right)
                             [(mod4Mask,               windowGo  ),
                              (mod4Mask .|. shiftMask, windowSwap)]
                             False
              $ def { keys = \conf@(XConfig {modMask = modm}) -> M.fromList [
                  ((modm,                 xK_l), windowGo R False)
                , ((modm,                 xK_h ), windowGo L False)
                , ((modm,                 xK_k   ), windowGo U False)
                , ((modm,                 xK_j ), windowGo D False)
                ] <+> keys conf conf
              }
-- i used this but to dont know how to add:
--{
import XMonad

main = xmonad defaultConfig
        { modMask = mod4Mask -- Use Super instead of Alt
        , terminal = "alacrity"
        -- more changes
        }
}--</pre>

**Comment by etherbiswas** [comment]
How do i combine the two cant have 2 main variables?

**Comment by geekosaur** [comment]
<pre>
import XMonad
import XMonad.Actions.Navigation2D
import qualified Data.Map as M

main = xmonad $ navigation2D def
                             (xK_Up, xK_Left, xK_Down, xK_Right)
                             [(mod4Mask,               windowGo  ),
                              (mod4Mask .|. shiftMask, windowSwap)]
                             False
              $ def {
                  modMask = mod4Mask
                , terminal = "alacritty"
                -- more changes here
                , keys = \conf@(XConfig {modMask = modm}) -> M.fromList [
                    ((modm,                 xK_l), windowGo R False)
                  , ((modm,                 xK_h ), windowGo L False)
                  , ((modm,                 xK_k   ), windowGo U False)
                  , ((modm,                 xK_j ), windowGo D False)
                  ] <+> keys conf conf
              }
</pre>

**Comment by etherbiswas** [comment]
Lgtm will try it tmrw, Good Night!

**Comment by etherbiswas** [comment]
alright looks like it doesnt work! why is it so hard to get left and right fucntionality?

**Comment by geekosaur** [comment]
What is "doesn't work" here?

**Comment by etherbiswas** [comment]
Turns out the module isn't very "useable" its not suppose to function the way i want it to, so i guess we would have to stick with up and down navigations.

**Comment by geekosaur** [comment]
This might be why several of us suggested X.L.WindowNavigation first. :) It's come up a bit recently and we're fairly sure it behaves as intended.

**Comment by etherbiswas** [comment]
Have you tried it?

**Comment by etherbiswas** [comment]
https://youtu.be/70IxjLEmomg
Your right, this guy seems to be using the same module.

**Comment by geekosaur** [comment]
I haven't, as I <a href="https://github.com/xmonad/xmonad/issues/353#issuecomment-981753096">said earlier</a> because I mostly use Tabbed and there's nowhere to navigate to. We had a discussion <a href="https://ircbrowse.tomsmeding.com/browse/lcxmonad?id=36582#trid36582">on IRC</a> about it recently, though, including at least one person who does use it.

**Comment by etherbiswas** [comment]
The issue can be resolved using the X.L.WindowNavigation module, but i suggest giving bspwm a try as directional tilling isn't really for xmonad.

**Comment by geekosaur** [comment]
There's also X.L.BinarySpacePartition. :)
