### ISSUE TITLE
Are we running X.O.windows too often during moves/resizes?

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad#358]
### Problem Description

A user reporting the usual hang when using `DynamicLog` without xmobar's `StdinReader` noted in passing something worrisome:

    If I resize a window it freezes up after about three seconds.

This suggests to me that we run `X.O.windows` and thereby `logHook` on every mouse motion during a move or resize operation. Should this be reduced to once when initiating the drag (when the window is floated if necessary) and once at the very end? There is already a flag for this in `XState`, so it shouldn't be difficult to suppress `X.O.windows` aside from possibly that first post-float run.

**Comment by slotThe** [comment]
> Should this be reduced to once when initiating the drag (when the window is floated if necessary) and once at the very end?

I think so.  The problem seems to be with [mouseMoveWindow](https://github.com/xmonad/xmonad/blob/master/src/XMonad/Operations.hs#L683) (and `mouseResizeWindow`).  The function that's called every time we receive a `MotionEvent` contains a call to `float`, which invokes `windows`.  However, I don't see a reason why we have to do this every time—presumably, a single call to `float` at the beginning of `mouseMoveWindow` and `mouseResizeWindow` (i.e., before the call to `mouseDrag`) should suffice

EDIT: Oh, apparently this serves a [real purpose](https://github.com/xmonad/xmonad/commit/4565e2c90ef522d23d3afc2cf95b9f0b423d8de4)

**Comment by geekosaur** [comment]
@liskin pointed me to https://github.com/xmonad/xmonad/commit/4565e2c90ef522d23d3afc2cf95b9f0b423d8de4 which makes it clear it's deliberate. We're now both wondering if there's a quieter way to do this, since it seems excessive just to update the window position.

**Comment by liskin** [comment]
I'd almost argue that xmonad freezing in 3 seconds in way better (easier to diagnose) than xmonad freezing in 3 days, which is what might happen had it not been for these "excessive" `X.O.windows` invocations. So I wouldn't consider that freeze a good argument for trying to "fix" this.

There may be other arguments, like doing `X.O.windows` on every mouse movement being slow (it's not noticeably slow in my setup, but I can image it might be in other setups). If that happens to be a real problem for real users, then we might want to deal with it. The main idea of https://github.com/xmonad/xmonad/commit/4565e2c90ef522d23d3afc2cf95b9f0b423d8de4 is "We need to make sure that the StackSet contains the right position for the window at all times while dragging.", and we can probably achieve that by invoking `X.O.float` at start/end of drag and just update the float location using `X.O.modifyWindowSet` during dragging (possibly doing another `X.O.float` when the window disappears from floats—unlikely, but user configs can do all sorts of stuff).

But I wouldn't go implementing that if nobody is actually having problems with this.

**Comment by slotThe** [comment]
I will close this for now, as I agree with @liskin's analysis of the situation.  Should we get another report of this anytime soon then we can reconsider, I suppose
