### ISSUE TITLE
Extending Window Identification in ManageHook

### ISSUE THREAD

**Issue by subbyte** [xmonad/xmonad#360]
### Problem Description

Concrete problem: `ManageHook` (using `className`) does not capture a VirtualBox client window (any virtual machine window) due to the delay of `WM_NAME`: `VirtualBox Machine` assignment ([VirtualBox Ticket #18042](https://www.virtualbox.org/ticket/18042)). This VirtualBox bug presents XMonad from floating or non-bordering any VirtualBox client.

Note that the VirtualBox main application does not have this issue, which has the `WM_NAME`: `VirtualBox Manager` set correctly at the window initialization time.

### Steps to Reproduce

- XMonad >= 0.15
- VirtualBox >= 5.2.8

Start a VM with `VBoxManage startvm vmname`.

### Configuration File

```haskell
myManageHook :: ManageHook
myManageHook = composeAll
    [ className =? "VirtualBox Machine" --> doFloat
    ]
```
### Thoughts Towards a Solution

The concrete problem mentioned above is not a XMonad issue at all, but a VirtualBox issue. However, after 3 years this is still not fixed in VirtualBox, and I am thinking to make some extended logic in XMonad to make it work.

1. Introduce a delayed operation for hooks like `doFloat` to deal with the delayed `WM_NAME` setting of some applications like VirtualBox.
2. Introduce other hooks or window identifiers like _process name_, or _parent process name_.

Any idea which way is preferred and any guidance of implementing it?

**Comment by geekosaur** [comment]
We already have https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Hooks-DynamicProperty.html for clients like this, and https://github.com/xmonad/xmonad-contrib/issues/588 for discussion of possible future directions in supporting such broken clients.

**Comment by subbyte** [comment]
wow, thanks for the information! Looks like exactly what I need.
