### ISSUE TITLE
Bug when switching workspaces with xmonad on latest git commits

### ISSUE THREAD

**Issue by tomjpalamattam** [xmonad/xmonad#361]
### Problem Description

After logging into xmonad, if i switch to a different workspace other than workspace  1 , i cant get back to workspace 1. the keyboard shortcut was unresponsive and clicking with mouse on workspace 1  (UnsafeStdinReader) was also not responding.
### Steps to Reproduce

1. compiled latest git version of xmonad and xmonad-contrib with stack. Also xmobar compiled using cabal.
2. Log into xmonad
3. switch to another workspace (say workspace 2)
4. Try to switchback to workspace 1
5. workspace 1 is unresponsive and cannot be accessed by keyboard shortcut or mouse click
6. I am able to switch to every other workspace other than workspace 1.
7. I was able to reproduce this bug on linux mint and Arch
8. changing the line from
myWorkspaces = ["1","2","3","4","5","6","7", "8", "9"] ++ ["NSP"]

to

myWorkspaces = ["1","2","3","4","5","6","7", "8", "9"]

fixed the issue.

(bug caused by scratchpads? )

9. This issue doesn't exist on 0.17.0 or any previous versions.

### Configuration File

    scratchpads = [

        NS "obs" "obs" (className =? "obs") nonFloating
     ]

    myWorkspaces = ["1","2","3","4","5","6","7", "8", "9"] ++ ["NSP"]
    windowCount = gets $ Just . show . length . W.integrate' . W.stack . W.workspace . W.current . windowset
    myWorkspaceIndices = M.fromList $ zipWith (,) myWorkspaces [1..] -- (,) == \x y -> (x,y)

    myPlacement                = inBounds (underMouse (0.5,0.5))

    mylogHook h = dynamicLogWithPP $ xmobarPP
                            {  ppOutput = hPutStrLn h
                            , ppCurrent = xmobarColor myppCurrent "" . wrap "[" "]" -- Current workspace in xmobar
                            , ppVisible = xmobarColor "#98be65" "" . clickable              -- Visible but not current workspace
                            , ppHidden = xmobarColor "#82AAFF" "" . wrap "*" "" . clickable -- Hidden workspaces
                            , ppHiddenNoWindows = xmobarColor "#c792ea" ""  . clickable     -- Hidden workspaces (no windows)
                            , ppTitle = xmobarColor  myppTitle "" . shorten 80     -- Title of active window in xmobar
                            , ppSep =  "<fc=#586E75> | </fc>"                     -- Separators in xmobar
                            , ppUrgent = xmobarColor  myppUrgent "" . wrap "!" "!"  -- Urgent workspace
                            , ppExtras  = [windowCount]                           -- # of windows current workspace
                            , ppOrder  = \(ws:l:t:ex) -> [ws,l]++ex++[t]
                            }

    main = do
        xmproc <- spawnPipe "xmobar"
        xmonad $ withUrgencyHook LibNotifyUrgencyHook $ ewmh desktopConfig
            { manageHook = manageDocks <+> myManageHook <+> manageHook desktopConfig <+> placeHook myPlacement <+> floatNextHook <+> namedScratchpadManageHook scratchpads
            -- manageHook = insertPosition Master Newer <+> doCenterFloat <+> manageDocks <+> myManageHook <+> manageHook desktopConfig
            , startupHook        = myStartupHook
            , layoutHook         = myLayout
            , handleEventHook    = handleEventHook desktopConfig
            , workspaces         = myWorkspaces
            , borderWidth        = myBorderWidth
            , terminal           = myTerminal
            , mouseBindings      = myMouseBindings
            , modMask            = myModMask
            , normalBorderColor  = myNormalBorderColor
            , focusedBorderColor = myFocusedBorderColor
            , logHook = mylogHook xmproc >> updatePointer (0.25, 0.25) (0.25, 0.25)
              }
              `additionalKeysP` myKeys

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [X] With `xmonad` version 0.17.0.9 (i am using git version with latest commits as on 5-01-2022. is there anything else i should provide?)
    - [X] With `xmonad-contrib` (xmonad-contrib with latest git commits as on  as on 5-01-2022 )

Thanks again for this wonderful project and your hardwork...

**Comment by slotThe** [comment]
Could you post your full config?  For example, the `myKeys` function is missing

**Comment by tomjpalamattam** [comment]
Here you go

https://github.com/tomjpalamattam/dotfiles/blob/main/.xmonad/xmonad.hs

**Comment by tomjpalamattam** [comment]
> Could you post your full config? For example, the `myKeys` function is missing

Here you go,

https://github.com/tomjpalamattam/dotfiles/blob/main/.xmonad/xmonad.hs

**Comment by slotThe** [comment]
Ah, I see what's happening.  When you are [setting your workspace keybindings](https://github.com/tomjpalamattam/dotfiles/blob/main/.xmonad/xmonad.hs#L262) you write

    | (i, k) <- zip (myWorkspaces) (map show [1 :: Int ..])

which (since you have ten workspaces) would come out to

    [("1","1"),("2","2"),("3","3"),("4","4"),("5","5"),("6","6"),("7","7"),("8","8"),("9","9"),("NSP","10")]

Now, `10` isn't a key and this transfers to `M-10` (as a key to go to the `NSP` workspace).  It seems that the old EZConfig parser accounted for this but I forgot about that when I rewrote it to use X.U.Parser in https://github.com/xmonad/xmonad-contrib/commit/8abeb81fd0693bd4ee914b522c0a2a2cfcfaf0dd.  A simple `<* eol` at the end of `readKeySequence` should suffice to fix this.  I've pushed a fix to the `xmonad-contrib` repo if you want to give it a try!

**Comment by tomjpalamattam** [comment]
> Ah, I see what's happening. When you are [setting your workspace keybindings](https://github.com/tomjpalamattam/dotfiles/blob/main/.xmonad/xmonad.hs#L262) you write
> 
> ```
> | (i, k) <- zip (myWorkspaces) (map show [1 :: Int ..])
> ```
> 
> which (since you have ten workspaces) would come out to
> 
> ```
> [("1","1"),("2","2"),("3","3"),("4","4"),("5","5"),("6","6"),("7","7"),("8","8"),("9","9"),("NSP","10")]
> ```
> 
> Now, `10` isn't a key and this transfers to `M-10` (as a key to go to the `NSP` workspace). It seems that the old EZConfig parser accounted for this but I forgot about that when I rewrote it to use X.U.Parser in [xmonad/xmonad-contrib@8abeb81](https://github.com/xmonad/xmonad-contrib/commit/8abeb81fd0693bd4ee914b522c0a2a2cfcfaf0dd). A simple `<* eol` at the end of `readKeySequence` should suffice to fix this. I've pushed a fix to the `xmonad-contrib` repo if you want to give it a try!

That was quick!. The fix worked with the same config. Thank you very much

**Comment by geekosaur** [comment]
This makes me wonder what happens if someone actually wants that: in `X.U.EZConfig` syntax, `M-10` means `M-1` is bound to a `SubMap` containing a definition for `0`. (Also, what does it do when `M-1` is also separately bound, as here. The old definition IIRC didn't handle this either; it'd just overwrite the original keybinding.)

**Comment by slotThe** [comment]
> This makes me wonder what happens if someone actually wants that: in
> `X.U.EZConfig` syntax, `M-10` means `M-1` is bound to a `SubMap`
> containing a definition for `0`.

This already works, one just has to write `M-1 0` instead of `M-10`
(which I find quite reasonable).

> (Also, what does it do when `M-1` is also separately bound, as
> here. The old definition IIRC didn't handle this either; it'd just
> overwrite the original keybinding.)

Yeah at the moment we're just overwriting everything.  If we did the
parsing at compile time we could mention this to the user somehow but
since we're doing it at runtime I'm not sure what would be best.
