### ISSUE TITLE
Mouse hovering don't change focus across monitors when using kde plasma wallpaper.

### ISSUE THREAD

**Issue by hyc3573** [xmonad/xmonad#364]
### Problem Description

If I move mouse from one screen to other empty screen, XMonad doesn't seem to recognize it. I have to press keybind to change focus or move window there to properly focus it.

### Steps to Reproduce

Arch linux, kde, using Cabal-static from aur, all up to date, dual monitor.
use minimal kde configuration as seen on wiki.
1. move mouse from current screen to other screen.

### Configuration File

Please include the smallest _full_ configuration file that reproduces
the problem you are experiencing:

```haskell
module Main (main) where

main :: IO ()
main = xmonad kdeconfig
```

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [X] With `xmonad` version 0.17.0
    - [X] With `xmonad-contrib` version 0.17.0

**Comment by hyc3573** [comment]
All I can find is It should been fixed by #88

**Comment by liskin** [comment]
Can you please try to run `xwininfo` in a terminal and click on the wallpaper on the empty screen? I suspect that KDE Plasma might be creating an extra window over the root window, and `xwininfo` would confirm that.

Here, `xwininfo` outputs: `xwininfo: Window id: 0x7be (the root window) (has no name)`, the important part being **the root window**. If you get something else, this would confirm my suspicion. (And I have no idea yet how we'd fix that.)

**Comment by hyc3573** [comment]
It doesn't say it's root window. Thanks for replying.
