### ISSUE TITLE
Error Xmonad

### ISSUE THREAD

**Issue by HanaO00** [xmonad/xmonad#37]
Hello, i have these errors in my xmonad.errors, can you help me please ?

xmonad.hs:33:10: Warning:
    In the use of ‘defaultPP’ (imported from XMonad.Hooks.DynamicLog):
    Deprecated: "Use def (from Data.Default, and re-exported by XMonad.Hooks.DynamicLog) instead."

xmonad.hs:54:11: Warning:
    In the use of ‘defaultPP’ (imported from XMonad.Hooks.DynamicLog):
    Deprecated: "Use def (from Data.Default, and re-exported by XMonad.Hooks.DynamicLog) instead."

xmonad.hs:88:9: Warning: Tab character

xmonad.hs:100:14: Warning:
    In the use of ‘defaultConfig’
    (imported from XMonad, but defined in XMonad.Config):
    Deprecated: "Use def (from Data.Default, and re-exported by XMonad and XMonad.Config) instead."

xmonad.hs:101:60: Warning:
    In the use of ‘defaultConfig’
    (imported from XMonad, but defined in XMonad.Config):
    Deprecated: "Use def (from Data.Default, and re-exported by XMonad and XMonad.Config) instead."

**Comment by geekosaur** [comment]
As the messages say, they are warnings ("Warning:") not errors. And they tell you what to do about them, although I generally ignore these because I don't actually think the Data.Default mechanisms are a good idea.

Were there also actual errors, or are you just worried about the warnings?

**Comment by HanaO00** [comment]
I'm lost because when i launch xmonad, xmonad doesn't work

**Comment by geekosaur** [comment]
Are you sure? xmonad is a window manager, not a desktop environment; when you start it, you will have a blank screen. Press mod-return (for whatever your mod key is, it defaults to Alt but is commonly changed to mod4/Super/"Windows key") to see if it will open an xterm. (And make sure xterm is installed, which it might not be on modern Linuxes that assume that everyone runs Gnome.)

**Comment by geekosaur** [comment]
Also note that you can't just run xmonad from a terminal and expect it to start up and take over. (This is at least partly a bug, although some other common window managers also do not speak the window manager handoff protocol.) You need to arrange for xmonad to be the session window manager, which from a command line login would be "startx $(which xmonad)" and from a GUI login requires you to create a session file (see https://wiki.haskell.org/Xmonad/Basic_Desktop_Environment_Integration for details).

**Comment by pjones** [comment]
@HanaO00 Since you haven't replied to @geekosaur's attempts to help you I'm am closing this issue as unresponsive.  If you want help configuring or using xmonad please ask on the mailing list or on IRC.
