### ISSUE TITLE
if use picom,xmonad does not display emacs border correctly after emacs update.（Update: emacs upstream fixed)

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad#372]
### Problem Description

I use emacs master branch, related commit: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b944841173f12134e4c68d269d5b82b1820b2a40 
old emacs version  in xmonad:
![oldemacs](https://user-images.githubusercontent.com/96685074/151813915-9123edda-6158-40b6-b3b0-472ba56cbac7.png)
new emacs version in xmonad:
![newemacs](https://user-images.githubusercontent.com/96685074/151814030-96c8f728-31d4-480f-b420-64666dde61a7.png)
new emacs version in other window manager:
![qqtile](https://user-images.githubusercontent.com/96685074/151814094-5bc7fd20-5610-4f98-9bb8-abf248c68706.png)

if i start picom without picom.conf, I see that the emacs border is a transparent color.
![picom](https://user-images.githubusercontent.com/96685074/151815158-be64fdf5-52a7-418e-adfd-8cca57c9ea49.png)

### Steps to Reproduce

Build emacs master branch, start picom without config file, you can see emacs border is a transparent color.

### Configuration File

Please include the smallest _full_ configuration file that reproduces
the problem you are experiencing:

```haskell
import XMonad
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.StatusBar
import XMonad.Hooks.StatusBar.PP
import XMonad.Util.EZConfig (additionalKeysP)
import XMonad.Util.Loggers
import XMonad.Layout.BinarySpacePartition
import XMonad.Layout.Spacing
import XMonad.Layout.NoBorders    
import XMonad.Hooks.EwmhDesktops
import XMonad.Util.SpawnOnce
import XMonad.StackSet as W
import XMonad.ManageHook
import XMonad.Util.NamedScratchpad
import XMonad.Layout.Renamed
import XMonad.Hooks.ManageHelpers
-- Fix Spotify Float
import XMonad.Hooks.DynamicProperty

main :: IO ()
main =
  xmonad
    . ewmhFullscreen
    . ewmh
    . withEasySB (statusBarProp "xmobar" (pure myXmobarPP)) defToggleStrutsKey
    $ myConfig

myConfig =
  def
    { modMask             = mod4Mask
      ,startupHook        = myStartupHook
      ,borderWidth        = 3
      ,focusedBorderColor = "#F08080"
      ,manageHook         = myManageHook
      ,layoutHook         = myLayout
      -- Fix Spotify Float
      ,handleEventHook    = dynamicPropertyChange "WM_NAME" (title =? "Spotify" --> doCenterFloat)
    }
    `additionalKeysP` [ ("<Print>", spawn "flameshot gui"),
                        ("M-<Space>", spawn "rofi -show drun -theme .rofi.rasi"),
                        ("M-<Return>", spawn "alacritty"),
                        ("M-S-q", kill),
                        ("M-e", spawn "emacsclient -c"),
                        ("M-S-r", spawn "theme.sh cycle"),
                        ("M-C-<Space>", namedScratchpadAction scratchpads "term"),
                        ("M-t", namedScratchpadAction scratchpads "todo"),
                        ("M-m", namedScratchpadAction scratchpads "music")
                      ]

-- $ means merge, ||| means multi layouts
myLayout = renamed [Replace "BSP"] $ smartBorders $ spacingWithEdge 7 $ emptyBSP

myXmobarPP :: PP
myXmobarPP = def
    { ppSep             = magenta " • "
    , ppTitleSanitize   = xmobarStrip
    , ppCurrent         = wrap " " "" . xmobarBorder "Top" "#8be9fd" 2
    , ppHidden          = red . wrap " " ""
    , ppHiddenNoWindows = lowWhite . wrap " " ""
    , ppUrgent          = red . wrap (yellow "!") (yellow "!")
    , ppOrder           = \[ws, l, _, wins] -> [ws, l, wins]
    , ppExtras          = [logTitles formatFocused formatUnfocused]
    }
  where
    formatFocused   = wrap (red    "[") (red    "]") . magenta . ppWindow
    formatUnfocused = wrap (lowWhite "[") (lowWhite "]") . blue    . ppWindow
    ppWindow :: String -> String
    ppWindow = xmobarRaw . (\w -> if null w then "untitled" else w) . shorten 30
    blue, lowWhite, magenta, red, white, yellow :: String -> String
    magenta  = xmobarColor "#ff79c6" ""
    blue     = xmobarColor "#bd93f9" ""
    white    = xmobarColor "#f8f8f2" ""
    yellow   = xmobarColor "#f1fa8c" ""
    red      = xmobarColor "#ff5555" ""
    lowWhite = xmobarColor "#bbbbbb" ""

myStartupHook :: X ()
myStartupHook = do
  spawn "pkill trayer"
  spawn "pkill .xkeysnail-wrap"
  spawn ("sleep 2 && xkeysnail -q ~/.config/xkeysnail/config.py")
  spawnOnce "feh --bg-fill ~/Downloads/wall.png"
  spawnOnce "systemctl --user restart picom.service"
  spawn ("sleep 2 && trayer --edge bottom --align right --widthtype request --SetDockType true --SetPartialStrut true --expand true --transparent true --alpha 0 --tint 0x282c34 --height 25 --iconspacing 6 --distance 4 --padding 7 --margin 15")
  spawn ("sleep 3 && systemctl --user restart fcitx5-daemon.service")
  spawnOnce ("systemctl --user restart emacs.service")
  spawnOnce "dunst"

myManageHook :: ManageHook
myManageHook = composeAll
    [ title =? "todo" --> doCenterFloat
    , title =? "term" --> doCenterFloat
    , isDialog        --> doCenterFloat
    ] <+> namedScratchpadManageHook scratchpads

scratchpads =
  [ NS "term" "alacritty --title=term" (title =? "term") defaultFloating,
    NS "music" "spotify" (title =? "Spotify") defaultFloating,
    NS "todo" "emacs --title todo --eval '(org-agenda-show-all-todo)' --eval '(delete-other-windows)'" (title =? "todo") defaultFloating
  ]
  where
    role = stringProperty "WM_WINDOW_ROLE"

```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17 (commit XXX if using git)
    - [x] With `xmonad-contrib` version 0.17 (commit XXX if using git)

**Comment by geekosaur** [comment]
Does this still happen if you extend your border color with an alpha channel? That is, change `"#F08080"` to `"#F08080FF"`?

**Comment by liskin** [comment]
> Does this still happen if you extend your border color with an alpha channel? That is, change `"#F08080"` to `"#F08080FF"`?

I can also reproduce the issue with floating Chrome windows, getting similar results to the last screenshot, and adding `FF` to the border color doesn't help. If you look closely at the last screenshot, you'll notice it's not really a transparency issue, but more like a different color blending mode—addition/subtraction rather than the normal alpha blending. Haven't had time to investigate any furthe,r, unfortunately.

**Comment by geekosaur** [comment]
Chrome also? That's interesting because I run Chrome (unless you mean dev channel) and have never seen transparent or blended borders, whereas it was fairly obvious on terminals until the fix that went into 0.17.

**Comment by liskin** [comment]
It's a recent thing (it's been weeks, maybe two or three months tops since I first noticed it) but I'm on a stable channel. I think I've seen it with another gtk app but can't really reproduce it with anything else right now. Certainly not with a terminal, but I run the good old urxvt :-)

**Comment by geekosaur** [comment]
Interesting. Still not seeing it (since I use gmail it was particularly easy to check :)

Does it also happen with compton? I haven't seen a reason to upgrade to picom, I just run compton out of Ubuntu packages.

**Comment by liskin** [comment]
What I have here is still called compton but it's certainly newer than what's in the Debian compton package. It's something between picom 7.3 and 7.4. I can check whether I can reproduce it with a different version, but I definitely won't get to it today. Maybe tomorrow.

(And in my case, rather than not having a reason to upgrade, I specifically have a very strong reason not to upgrade: https://github.com/yshui/picom/issues/381#issuecomment-956359184 and I find it impossible to understand how anyone could run the current code and not go insane.)

**Comment by slotThe** [comment]
On Mon, Jan 31 2022 06:54, NIXFOREVERNIX wrote:
> Build emacs master branch, start picom without config file, you can
> see emacs border is a transparent color.

What are your ./configure options?  I.e., did you compile with PGTK and,
if not, what X toolkit?  I'm running on commit
6cea4d1fdbdcfd6810bfea70ba58d7a45f2d2384 with the lucid toolkit and I
can't reproduce the behaviour (i.e., just running `compton` gives me a
solid border around Emacs)

**Comment by ghost** [comment]
@geekosaur Unfortunately, when i use #F08080FF ,alacritty, & firefox has also turned into a transparent border, only older versions of emacs are normal (picom without picom.conf also has the same effect)

But I'm happy that I can see the border after enabling my picom.conf.

when i use #F08080FF:
![1](https://user-images.githubusercontent.com/96685074/151857644-6638adec-fbea-4515-b929-293053e48fe3.png)
![1](https://user-images.githubusercontent.com/96685074/151857750-5c968650-7257-42c4-8ec0-a3a05f6e0643.png)
![1](https://user-images.githubusercontent.com/96685074/151857999-88786788-93f1-4dfc-a9ac-aa3b395edd5d.png)

when i use #F08080:
![1](https://user-images.githubusercontent.com/96685074/151858946-26e60cd4-3366-48fa-9e7b-86bebd0ac211.png)

**Comment by ghost** [comment]
@liskin Sorry I want to use the new feature of picom: rounded corners.
I use https://github.com/ibhagwan/picom latest commit, but when i use https://github.com/yshui/picom latest commit it can also reproduce the problem

**Comment by ghost** [comment]
Today i test latest commit(558c4dafa309445cd8ffc568303e2189f4effc03), fixed.
![final](https://user-images.githubusercontent.com/96685074/151922704-d16cd07e-6eb8-45b4-b9d6-677a51390631.png)

But @liskin  can also reproduce the issue with floating Chrome windows, And other window manager did not have new emacs version border transparency problems before.
So I think xmonad may still have problems, should I close or keep this issue ？

**Comment by liskin** [comment]
I'd leave it open for a bit, there's definitely something wrong somewhere on our side as well.

**Comment by geekosaur** [comment]
What's the other window manager? We may want to compare their colormap handling or etc.

**Comment by geekosaur** [comment]
Also I still can't reproduce it with Chrome either floated or tiled locally, so this is apparently one of those complex interactions that's going to require some work to sort out. @liskin, can you point me to a picom commit, or should I just try `754531e^`?

**Comment by ghost** [comment]
@liskin OK, I will keep the issue open

@geekosaur  I just randomly tried [qtile](https://github.com/qtile/qtile) (in xorg)

**Comment by ghost** [comment]
> ### Steps to Reproduce
> 
> Build emacs master branch, start picom without config file, you can see emacs border is a transparent color.

Emacs master branch latest commit(30ebb54410d18a4f782fe39d21c1941f9852ec8f), if you use ./configure --with-x,This issue can no longer be reproduced.
You can use ./configure --with-pgtk The issue still exists.

**Comment by ghost** [comment]
@geekosaur If you are emacs user, you just can use emacs master branch ./configure --with-x (commit: b944841173f12134e4c68d269d5b82b1820b2a40) and picom next branch(commit: 3b9af145f0275edf6c54286e5f26e8b269835a6b) reproduce the issue.
![1](https://user-images.githubusercontent.com/96685074/151957370-259612e3-267b-4865-a6bf-dcea335f1e91.png)

**Comment by geekosaur** [comment]
I'd rather not deal with replacing a full emacs installation if I can help it, and so if I can repro with Chrome that's preferable. Picom should be more self-contained; I used to do my own compton builds before that made it into Debian/Ubuntu/Mint packages.

**Comment by ghost** [comment]
@geekosaur google-chrome 97  Reproduced
![chrome](https://user-images.githubusercontent.com/96685074/151964367-5f071538-6eeb-4f5d-9f6c-b8300db76f9c.png)

**Comment by slotThe** [comment]
I guess this is something GTK3 related then (--with-x defaults to using
GTK, while the PGTK branch is purely GTK3 based).  This also explains
why I couldn't reproduce this since I always build with the lucid
toolkit.

**Comment by ghost** [comment]
@slotThe Yes, I use --with-x or --with-pgtk.

**Comment by liskin** [comment]
> Also I still can't reproduce it with Chrome either floated or tiled locally, so this is apparently one of those complex interactions that's going to require some work to sort out. @liskin, can you point me to a picom commit, or should I just try `754531e^`?

I can reproduce it with the compton package from Debian testing/unstable, which is presumably the same as what you run, so it's probably not a compton/picom regression.

**Comment by geekosaur** [comment]
Testing claims to have 1-1 while Ubuntu 20.04 has 0.1~beta2+20150922-1. I'll poke.

**Comment by geekosaur** [comment]
Yes, the "compton" that is in testing and unstable is picom-1, whereas the one I got from Ubuntu dates from 2015. I have built it locally and will test shortly.

**Comment by geekosaur** [comment]
So I killed my running compton, ran the new one, and … no difference. What's your `compton.conf`?

**Comment by geekosaur** [comment]
For reference, I ran `./compton -cCfGb --backend=glx` and my `compton.conf` is:
<pre>
inactive-dim = 0.4;
frame-opacity = 1;
detect-transient = true;
use-ewmh-active-win = true;
mark-wmwin-focused = true;
# nb. faster on real h/w but KILLS vmware
glx-swap-method = 1;
# not perfect, but good enough (really want different dimming on unfocused-in-same-group)
detect-client-leader = true;
clear-shadow = true;
glx-no-stencil = true;
shadow-exclude = [
  "_NET_WM_STATE@:a *= '_NET_WM_STATE_FULLSCREEN'"
 ,"class_g = 'Mate-notification-daemon'"
];
fade-exclude = [
  "_NET_WM_STATE@:a *= '_NET_WM_STATE_FULLSCREEN'"
 ,"class_g = 'Mate-notification-daemon'"
];
focus-exclude = [
  "_NET_WM_STATE@:a *= '_NET_WM_STATE_FULLSCREEN'"
 ,"class_g = 'Mate-notification-daemon'"
];

wintypes:
{
  tooltip = {fade = false; shadow = true; opacity = 1; focus = true; };
  splash = {fade = false; shadow = true; opacity = 1; focus = true; };
  menu = {fade = false; shadow = true; opacity = 1; focus = true; };
  notify = {fade = false; shadow = false; opacity = 1; focus = true; };
};
</pre>

**Comment by liskin** [comment]
Turns out I was just running old xmonad without https://github.com/xmonad/xmonad/commit/bb448cc293033df5b54ce961716bcd07f0e14e98, and so was probably @NIXFOREVERNIX as the issue says they're on 0.17. Should've checked this first, sorry @geekosaur for the confusion.

After updating, this is now fixed. Perhaps we should start planning to release 0.17.1 … :-)

**Comment by geekosaur** [comment]
That would in fact explain it, I run HEAD and update it at least weekly.

**Comment by ghost** [comment]
Yes, I use xmonad 0.17 stable, I will try master branch , Thanks @liskin @geekosaur
