### ISSUE TITLE
More aggressively suggest `ghcup` in INSTALL.md

### ISSUE THREAD

**Issue by slotThe** [xmonad/xmonad#373]
We are currently suggesting to use ghcup in INSTALL [here](https://github.com/xmonad/xmonad/blob/master/INSTALL.md?plain=1#L138) and [here](https://github.com/xmonad/xmonad/blob/master/INSTALL.md?plain=1#L224).  However, this is done mainly for completeness and I doubt anyone would actually look at ghcup based on those two short sentences.  For distributions where installing statically linked Haskell binaries is semi non-trivial (*cough*), however, using ghcup might be by far the easiest option, instead of installing some statically linked stack binary.  I think we should push for that more (I personally have never used ghcup, so I doubt I'm a good person to write that part of the docs)

**Comment by harjotgill** [comment]
I just spend an hour dealing with compilation errors with stack and cabal methods. The GHCup method is indeed the quickest/easiest way to get started right now.

**Comment by slotThe** [comment]
On Wed, Apr 13 2022 18:03, Harjot Gill wrote:
> I just spend an hour dealing with compilation errors with stack and
> cabal methods. The GHCup method is indeed the quickest/easiest way to
> get started right now.

As always: contributions very welcome!
