### ISSUE TITLE
Mouse teleporting on fullscreen games or resizing tiled windows

### ISSUE THREAD

**Issue by wetrustinprize** [xmonad/xmonad#377]
### Problem Description

Mouse teleporting on focusing/unfocosing (with mouse) in fullscreen games that locks mouse movement.

Also, the mouse teleports when resizing tiled windows.

### Steps to Reproduce

Hold right mouse button and resize a window, the mouse will teleport to a specific position on the screen (or even on the other screen if using multiple monitors).

Move the mouse inside a fullscreen game window, if the game has the mouse locked (when the game has camera movement that hides the mouse) the mouse will teleport like when resizing tiled windows.

Also, the mouse _can_ teleport when leaves the game window, if the game display a cursor (like in a MOBA or in a menu) it only teleports when leaving, when entering the window there is no problem.

### Configuration File

```haskell
myMouseBindings (XConfig {XMonad.modMask = modm}) =
  M.fromList $
    [ ( (modm, button1),
        \w ->
          focus w >> mouseMoveWindow w
            >> windows W.shiftMaster
      ),
      ((modm, button2), \w -> focus w >> windows W.shiftMaster),
      ( (modm, button3),
        \w ->
          focus w >> mouseResizeWindow w
            >> windows W.shiftMaster
      )
    ]
```

```haskell
xmonad $ docks $ ewmhFullscreen $ ewmh def { ... }
```

Full `xmonad.hs` can be found [here](https://github.com/wetrustinprize/dotfiles/blob/main/dotfiles/xmonad/xmonad.hs).

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0.9
    - [x] With `xmonad-contrib` version 0.16

**Comment by slotThe** [comment]
I'm having trouble figuring out exactly what problem you are having—the mouse teleporting to the bottom right of the window when resizing is normal (since that's where we are resizing fromg).  Would you care to post a minimal "working" configuration with a step-by-step reproducer?

>     * I tested my configuration
>
>       * [x]  With `xmonad` version 0.17.0.9
>       * [x]  With `xmonad-contrib` version 0.16

Is this correct?  I'm very certain that `xmonad-contrib` 0.16 does not even compile against the `master` branch of `xmonad`

**Comment by wetrustinprize** [comment]
Hi!

Sorry, that was a typo, the correct version of `xmonad-contrib` I'm using is v0.17.0.r89.

## Reproducing

1. Hold Super + Right mouse button
2. Move the mouse
3. The mouse will teleport

Here's a video with the bug happening:

https://user-images.githubusercontent.com/38386927/155036133-118c282c-fac5-42f8-8da6-acd94b3f3494.mp4

_here is possible to see that the mouse stays in the bottom right corner of the window until I move it, then the mouse teleports_

## Minimal configuration

```haskell
import XMonad
import XMonad.Config.Desktop

import qualified Data.Map as M
import qualified XMonad.StackSet as W

myMouseBindings (XConfig {XMonad.modMask = modm}) =
  M.fromList $
    [ ( (modm, button1),
        \w ->
          focus w >> mouseMoveWindow w
            >> windows W.shiftMaster
      ),
      ((modm, button2), \w -> focus w >> windows W.shiftMaster),
      ( (modm, button3),
        \w ->
          focus w >> mouseResizeWindow w
            >> windows W.shiftMaster
      )
    ]

main = xmonad desktopConfig
    { terminal    = "xterm"
    , modMask     = mod4Mask
    , mouseBindings = myMouseBindings
    }
```

Thanks!

**Comment by slotThe** [comment]
I still can't seem to reproduce this; everything works as expected on my end: 

https://user-images.githubusercontent.com/50166980/155088419-69c48bb8-0e4d-466e-9c36-58308fad93dc.mov

When moving the mouse, the lower right corner of the floating window moves to where the mouse is and from there on out it's "normal" resizing

**Comment by wetrustinprize** [comment]
Oh, that's weird.

I really don't know why I'm having this bug, I'll try today other USB mices (maybe this could be the problem?). I really can't figure out what is causing this problem.

**Comment by geekosaur** [comment]
If you're seeing it on resizing tiled windows then possibly you could test with a tiled `xev` and pastebin the log somewhere we can examine it.

**Comment by wetrustinprize** [comment]
Here's the xev log @geekosaur: [gist](https://gist.github.com/wetrustinprize/1c0f106935731a22681688d3d540450a)

**Comment by wetrustinprize** [comment]
Update: I tried with a different mouse and it stoped that teleporting behaviour.

I think the problem is with how my Linux is handling my mouse (Razer Deathadder 3.5g).

**Comment by wetrustinprize** [comment]
Should we close this issue? I think that the behaviour my Razer mouse is having is not directly related to xmonad.

**Comment by slotThe** [comment]
> Should we close this issue? I think that the behaviour my Razer mouse is having is not directly related to xmonad.

Sounds like it to me; thanks for the follow-up!
