### ISSUE TITLE
[Extream noob warning :-)] avoidStruts not working to display xmobar on top of screen

### ISSUE THREAD

**Issue by DokStook** [xmonad/xmonad#379]
### Problem Description

I decided to try to make my own xmonad rice (my first rice ever) and my experience was not that good in the last hour and a half. After watching one of DistroTube's videos about xmonad  [this](https://www.youtube.com/watch?v=3noK4GTmyMw) I wanted to try setting up xmonad myself and I followed the basic steps he did on the video. After adding avoidStruts to my configuration and restarting xmonad nothing happened. I have tried parts from other people's configs, this was not working either. Also there are different opened and closed issues that say that I should add or change something but I don't understand what to add or change. 

Thanks in advance! 

### Steps  to Reproduce

1. Copy the darcs template config
2. Add avoidStruts (and other stuff that I don't think will effect the xmobar apearing) to the confing
3. Restart
4. Nothing happens

### Configuration File

[here](https://git.techsaviours.org/berates_dropper/xmonad_conf)

**Comment by geekosaur** [comment]
You need to change line 256 to

    xmonad $ docks default

You probably also want to add EWMH support, which means adding

    import XMonad.Hooks.EwmhDesktops

up around line 8 or 9, and using instead of the above

    xmonad $ docks . ewmh $ default

**Comment by DokStook** [comment]
Hello, 
Thanks for your fast reply!

Here is what I get when I try to recompile xmonad
`
xmonad.hs:256:16: error: parse error on input ‘default’
    |
256 | xmonad $ docks default
    |                ^^^^^^^`

**Comment by geekosaur** [comment]
Right, sorry, you called it `defaults` (and I should have caught that; `default` is indeed a keyword).

    xmonad $ docks . ewmh $ defaults

**Comment by DokStook** [comment]
I don't understand what you are telling me to do.

**Comment by geekosaur** [comment]
That line replaces line 256 of your `xmonad.hs`. You also want to add

    import XMonad.Hooks.EwmhDesktops

around line 9, as I previously mentioned.

**Comment by DokStook** [comment]
That error is happening after the additional changes

**Comment by DokStook** [comment]
I have updated the repo with the changes

**Comment by geekosaur** [comment]
Youur `xmonad.hs` should look like https://paste.tomsmeding.com/uCw5Bl1S after the changes. In particular, you didn't change `default` to `defaults` as I told you above.

**Comment by DokStook** [comment]
Hmm I tried that. I don't know why it didn't work. 

Anyways. Thank you mate!
