### ISSUE TITLE
CS:GO crashes when I set the display mode to Fullscreen or Fullscreen Windowed

### ISSUE THREAD

**Issue by DokStook** [xmonad/xmonad#380]
### Problem Description

Hello,

As I mentioned in the title I cannot play CS:GO in any streched resolution. When I try to switch to one of the mentioned display modes the game crashes and I cannot relaunch it. I am kind of newbie when it comes to coding and I don't know what else to add (logs or something else) so please be kind :-) .

Thanks in advance!

### Steps to Reproduce

1. Launch the game
2. Go to settings 
3. Go to "Video" tab
4. Change display mode to either Fullscreen or Fullscreen Windowed
5. CRASH!!

### Configuration File

https://git.techsaviours.org/berates_dropper/xmonad_conf/src/branch/master/xmonad.hs

### Additional info

For anyone wondering [here is the reddit thread](https://www.reddit.com/r/xmonad/comments/tdecv1/csgo_crashes_when_i_set_the_display_mode_to/)

**Comment by TheMC47** [comment]
For starters, you're calling the xmonad function twice (lines 281 and 282). the `fullscreenEventHook` isn't getting applied, so move it to `defaults` or to `myEventHook` and remove the lines from 282 to 284. Did you try enabling `ewmh`? Import `XMonad.Hooks.EwmhDesktops` and apply it as so:

```haskell
      xmonad =<< statusBar myBar myPP toggleStrutsKey (ewmh defaults)
```

**Comment by DokStook** [comment]
So it should look something like this
`xmonad =<< statusBar myBar myPP toggleStrutsKey defaults { handleEventHook =
           handleEventHook def <+> fullscreenEventHook }` ?

**Comment by TheMC47** [comment]
That would almost* work, but since you're defining `myEventHook`, just do `myEventHook = fullscreenEventHook` in line 243

*: `xmonad =<< statusBar myBar myPP toggleStrutsKey $ defaults { handleEventHook = handleEventHook def <+> fullscreenEventHook }`

**Comment by DokStook** [comment]
Hmm, still doesn't work. I have pushed the new updates to the repo. Check them. I want to be sure that I have done it right

**Comment by TheMC47** [comment]
> Did you try enabling ewmh? Import XMonad.Hooks.EwmhDesktops and apply it as so:
>
>     xmonad =<< statusBar myBar myPP toggleStrutsKey (ewmh defaults)


Please apply ewmh

**Comment by DokStook** [comment]
Thank you, really really much. I thought that the `(ewmh defauls)` is where to put the hooks. It worked

**Comment by TheMC47** [comment]
Glad it worked
