### ISSUE TITLE
Last system update broke xmonad

### ISSUE THREAD

**Issue by DokStook** [xmonad/xmonad#381]
### Problem Description

Earlier today I upgraded my system. After the upgrade I restarted and tried to log back in. When I logged back in it just put me back into the login screen.

### Steps to Reproduce

1. sudo pacman -Syyu
2. reboot
3. login
4. The situation above

[### Configuration File](https://git.techsaviours.org/berates_dropper/xmonad_conf/src/branch/master/xmonad.hs)

Thanks in advance!

**Comment by TheMC47** [comment]
Try to login into another session or a non-graphical session, and run xmonad --recompile

**Comment by DokStook** [comment]
Thanks, it worked!
