### ISSUE TITLE
Need help with My bar :(

### ISSUE THREAD

**Issue by etherbiswas** [xmonad/xmonad#382]
I am confused trying to add a way to to see my current layout in polybar. Does someone know how i could possibly display the current layout? I am using the [xworkspaces](https://github.com/polybar/polybar/wiki/Module:-xworkspaces ) module in my polybar [config](https://github.com/Ahanaf-Ether/polybar).
here is my xmonad [config](https://github.com/Ahanaf-Ether/xmonad);
Pull requests welcome :)
 
Thanks in advance!

**Comment by etherbiswas** [comment]
How do i set [this](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Hooks-StatusBar.html) up?

**Comment by geekosaur** [comment]
There's a [tutorial](https://xmonad.org/TUTORIAL.html), but I don't think it will help here. The fundamental problem is that polybar uses EWMH to get its information, but EWMH has no knowledge of layouts.

I'm also wondering what you're doing with the DBus config, since it only works with `xmonad-log-applet` and that doesn't work with polybar to my knowledge, only with XFCE / MATE / Gnome panels.

**Comment by slotThe** [comment]
On Sat, Mar 26 2022 08:00, brandon s allbery kf8nh wrote:
> There's a [tutorial](https://xmonad.org/TUTORIAL.html), but I don't
> think it will help here. The fundamental problem is that polybar uses
> EWMH to get its information, but EWMH has no knowledge of layouts.

AFAIR polybar also supports reading input via pipes (though not from
stdin for some reason); that might still work

> I'm also wondering what you're doing with the DBus config, since it
> only works with `xmonad-log-applet` and that doesn't work with polybar
> to my knowledge, only with XFCE / MATE / Gnome panels.

xmonad-log[1] specifically mentions polybar, actually.  It might be the
best solution for that bar specifically

[1]: https://github.com/xintron/xmonad-log

**Comment by etherbiswas** [comment]
how do i pipe it to polybar? as far as i read the documentation doesn't really go about explaining how i would go about doing so. :(

**Comment by etherbiswas** [comment]
PS; Xmonad-log isn't working anymore! Its kinda bloated and old.
Polybar does read "Standard Input and Output". Is there a way to maybe workaround its? 
<pre>import qualified Data.Map</pre> 
Similar Config;
https://github.com/stites/configs-mirror/blob/master/programs/xmonad/xmonad-with-polybar.hs

**Comment by slotThe** [comment]
> PS; Xmonad-log isn't working anymore! Its kinda bloated and old.

What?  It's like 50 lines of code.  There's also the popular [xmonad-dbus](https://github.com/troydm/xmonad-dbus) (which is basically just `xmonad-log` rewritten in Haskell because we can).  A lot of people in the community use these to communicate with polybar—I'm sure we would have heard about it if they were broken.  I will note that `xmonad-dbus` also contains an example how to configure all of this.

> Similar Config; https://github.com/stites/configs-mirror/blob/master/programs/xmonad/xmonad-with-polybar.hs

The `eventLogHookForPolyBar` is what you're looking for.  You can see that two files are created (`/tmp/.xmonad-title-log` and `/tmp/.xmonad-workspace-log`) which are presumably read from polybar

**Comment by etherbiswas** [comment]
> > PS; Xmonad-log isn't working anymore! Its kinda bloated and old.
> 
> What? It's like 50 lines of code. There's also the popular [xmonad-dbus](https://github.com/troydm/xmonad-dbus) (which is basically just `xmonad-log` rewritten in Haskell because we can). A lot of people in the community use these to communicate with polybar—I'm sure we would have heard about it if they were broken. I will note that `xmonad-dbus` also contains an example how to configure all of this.
> 
> > Similar Config; https://github.com/stites/configs-mirror/blob/master/programs/xmonad/xmonad-with-polybar.hs
> 
> The `eventLogHookForPolyBar` is what you're looking for. You can see that two files are created (`/tmp/.xmonad-title-log` and `/tmp/.xmonad-workspace-log`) which are presumably read from polybar

Thanks! I will try it, note:
Already tried the similar config it uses;
${pkgs.coreutils}/bin/tail -F /tmp/.xmonad-title-log but my shell outputs an error!

**Comment by etherbiswas** [comment]
As for xmonad-dbus, if it doesn't get dated, i will surely use it! 😁

**Comment by geekosaur** [comment]
`${pkgs.coreutils}` is an invalid shell variable… and looks like something from Nix. I'd just remove that part.

**Comment by etherbiswas** [comment]
how do i echo it then?

**Comment by etherbiswas** [comment]
tail -F?

**Comment by etherbiswas** [comment]
no output!

**Comment by etherbiswas** [comment]
> `${pkgs.coreutils}` is an invalid shell variable… and looks like something from Nix. I'd just remove that part.

YEp, tail -- help;
GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/tail>
or available locally via: info '(coreutils) tail invocation'

**Comment by etherbiswas** [comment]
myabe its to execute tail itself in nixos?

**Comment by geekosaur** [comment]
Yes, it should just be `tail -F /tmp/.xmonad-title-log`. Make sure you're using the specified `eventLogHookForPolyBar` and that you have chained it into your `handleEventHook` using `<+>`.

**Comment by etherbiswas** [comment]
IT WORKS!!

**Comment by etherbiswas** [comment]
THANK YOU !!! but; it does not display the layout!

**Comment by etherbiswas** [comment]
which was the issue :(

**Comment by geekosaur** [comment]
But now we have polybar working, so now it becomes a matter of adjusting `eventLogHookForPolybar` to add the layout. It could either make it part of the title, or part of the workspaces, or we could add a third output pipe for the layout and you would need to adjust polybar to match.

**Comment by etherbiswas** [comment]
<pre>  eventLogHookForPolyBar = do
    winset <- gets windowset
    title <- maybe (return "") (fmap show . getName) . W.peek $ winset
    let currWs = W.currentTag winset
    let wss = map W.tag $ W.workspaces winset

    io $ appendFile "/tmp/.xmonad-title-log" (title ++ "\n")
    io $ appendFile "/tmp/.xmonad-workspace-log" (wsStr currWs wss ++ "\n")

    where
      fmt currWs ws
            | currWs == ws = "[" ++ ws ++ "]"
            | otherwise    = " " ++ ws ++ " "
      wsStr currWs wss = join $ map (fmt currWs) $ sortBy (compare `on` (!! 0)) wss

type (:+) f g = Choose f g
infixr 5 :+</pre>

**Comment by etherbiswas** [comment]
What do i modify?

**Comment by etherbiswas** [comment]
I dont need the workspaces since i have xworkspaces working (single monitor setup)

**Comment by etherbiswas** [comment]
We need to create <pre>Layout <-</pre>

**Comment by etherbiswas** [comment]
> But now we have polybar working, so now it becomes a matter of adjusting `eventLogHookForPolybar` to add the layout. It could either make it part of the title, or part of the workspaces, or we could add a third output pipe for the layout and you would need to adjust polybar to match.

That would be awesome 🙂

**Comment by geekosaur** [comment]
Roughly, something like
```
let layout = description . W.layout . W.workspace . W.current $ winset
io $ appendFile "/tmp/.xmonad-layout-log" (layout ++ "\n")
```

then modify the polybar config to read that file as well. You could also remove the `let currWs …` and `let wss …`, the `where` clause, and the append to `.xmonad-workspace-log` since you're getting that from EWMH.  The result would look something like
```
eventLogHookForPolyBar = do
  winset <- gets windowset
  title <- maybe (return "") (fmap show . getName) . W.peek $ winset
  let layout = description . W.layout . W.workspace . W.current $ winset

  io $ appendFile "/tmp/.xmonad-title-log" (title ++ "\n")
  io $ appendFile "/tmp/.xmonad-layout-log" (layout ++ "\n")
```

**Comment by Ahanaf-Ether** [comment]
> Roughly, something like
> 
> ```
> let layout = description . W.layout . W.workspace . W.current $ winset
> io $ appendFile "/tmp/.xmonad-layout-log" (layout ++ "\n")
> ```
> 
> then modify the polybar config to read that file as well. You could also remove the `let currWs …` and `let wss …`, the `where` clause, and the append to `.xmonad-workspace-log` since you're getting that from EWMH. The result would look something like
> 
> ```
> eventLogHookForPolyBar = do
>   winset <- gets windowset
>   title <- maybe (return "") (fmap show . getName) . W.peek $ winset
>   let layout = description . W.layout . W.workspace . W.current $ winset
> 
>   io $ appendFile "/tmp/.xmonad-title-log" (title ++ "\n")
>   io $ appendFile "/tmp/.xmonad-layout-log" (layout ++ "\n")
> ```

no layout log!

**Comment by etherbiswas** [comment]
maybe something to do with <pre>forM_</pre>
where M is qualifed as <pre>import qualified Data.Map as M</pre>
this is confusing as in the config also;
<pre>import Control.Monad (forM_, join)</pre>

**Comment by Ahanaf-Ether** [comment]
it makes the log file but it contains nothing :(

**Comment by etherbiswas** [comment]
line 57 of the similar [config](https://github.com/stites/configs-mirror/blob/master/programs/xmonad/xmonad-with-polybar.hs) <pre>forM_ [".xmonad-workspace-log", ".xmonad-title-log"] $ \file -> safeSpawn "mkfifo" ["/tmp/" ++ file]</pre>
I have replaced workspace with layout. It wont work though

**Comment by etherbiswas** [comment]
You Guys are awesome! it works :) but.. there is some wierd dependency on the title, i am using the xwindow module for polybar. Adding a second title is uselss :( is, there a way to remove the title dependency?

**Comment by etherbiswas** [comment]
Yay i figure it out! 
<pre>
eventLogHookForPolyBar = do
  winset <- gets windowset
  title <- maybe (return "") (fmap show . getName) . W.peek $ winset
  let layout = description . W.layout . W.workspace . W.current $ winset

  io $ appendFile "/tmp/.xmonad-layout-log" (layout ++ "\n")
</pre>
and for the second part;
<pre>
forM_ [".xmonad-layout-log"] $ \file -> safeSpawn "mkfifo" ["/tmp/" ++ file]
</pre>

**Comment by etherbiswas** [comment]
Thats all cool, i need one more thing though :( 
The number of clients on a workspace and the number of floats.
There a [video](https://www.youtube.com/watch?v=jCzuMHU3Qtw&t=457s) by DistroTube(aka D.T or Derek Taylor) in which he has a similar setup on his "xmobar". I want basically a way to display that without using xmobar. I don't mind using xmobar, but using a sperate volume application and a seperate trayer isn't convenient. I also found the bar to be less extensible.(don't take my opinion though i am not great with Haskell becuz its a purely functional language(i prefer oop)
PS: i already have my polybar config :)

**Comment by etherbiswas** [comment]
There are mulitple ways to slove this :) The most awesome way imo is; 
> 
> eventLogHookForPolyBar = do
>   winset <- gets windowset
>   title <- maybe (return "") (fmap show . getName) . W.peek $ winset
>   let layout = description . W.layout . W.workspace . W.current $ winset
> 
>   io $ appendFile "/tmp/.xmonad-layout-log" (layout ++ "\n")
> and for the second part;
> 
> forM_ [".xmonad-layout-log"] $ \file -> safeSpawn "mkfifo" ["/tmp/" ++ file]

Because, xmobar requires you to pipe the workspaces in your xmobar. Or setup a log hook anyways!
