### ISSUE TITLE
Display amount of clients in the bar :(

### ISSUE THREAD

**Issue by etherbiswas** [xmonad/xmonad#383]
Thats all cool, i need one more thing though :( 
The number of clients on a workspace and the number of floats.
There a [video](https://www.youtube.com/watch?v=jCzuMHU3Qtw&t=457s) by DistroTube(aka D.T or Derek Taylor) in which he has a similar setup on his "xmobar". I want basically a way to display that without using xmobar. I don't mind using xmobar, but using a sperate volume application and a seperate trayer isn't convenient. I also found the bar to be less extensible.(don't take my opinion though i am not great with Haskell becuz its a purely functional language(i prefer oop)
PS: i already have my polybar config :)

_Originally posted by @Ahanaf-Ether in https://github.com/xmonad/xmonad/issues/382#issuecomment-1079882488_

**Comment by liskin** [comment]
Can we please stop using issues as a chat? Either turn this into a GH discussion, or---preferably---use an actual chat (we have IRC and Matrix). Thx!

**Comment by etherbiswas** [comment]
> Can we please stop using issues as a chat? Either turn this into a GH discussion, or---preferably---use an actual chat (we have IRC and Matrix). Thx!

Should i close the issue and ask the irc?

**Comment by etherbiswas** [comment]
Can i have the link or smth for the irc?

**Comment by liskin** [comment]
https://xmonad.org/community.html

The xmonad reddit is active too and people ask these kinds of questions there often, if you prefer that.
