### ISSUE TITLE
Dmenu opening on wrong window

### ISSUE THREAD

**Issue by twiclo** [xmonad/xmonad#384]
I have 3 monitors. While having my left monitor selected I hit Mod+r to select my right monitor. I then launch dmenu and it appears on the center monitor

I spoke with geekosaur in the IRC who tested it a bit and this is what he found:

```
geekosaur | that may be something dmenu is doing, then
   twiclo | This didn't happen on i3
   twiclo | I would just think that since there's nothing to actually select on the monitor that it's not "selected" according to dmenu
geekosaur | how is dmenu being run to display windows? dmenu_run shows programs; dmenu by itself takes a list of menu items on its stdin and doesn't know about windows
geekosaur | (I installed dmenu locally and so far can't reproduce your issue)
geekosaur | huh. just repro-d it
geekosaur | what's interesting is I used XMonad.Prompt.Shell to run it and that showed upon the correct monitor
geekosaur | also dmenu doesn't go through the window manager so we shouldn't have any control over where it shows up
geekosaur | _NET_CURRENT_DESKTOP is correct
   twiclo | Okay so you're saying if I run it through Shell I should be fine? Odd but it works
geekosaur | no, that's how I'm reproducing it, not using a keybind. and the Shell prompt shows up in the right place but dmenu doesn't
   twiclo | Weird
geekosaur | I'm running out of time to look into this, I'm about to be kicked out of my apt. for a few hours (bedbug spraying, again)
   twiclo | Geekosaur I'll submit an issue. Thanks for looking into it
   fizzie | I've noticed that too. And that moving the mouse to the "empty" monitor makes the prompt appear on that.
   fizzie | Never been sufficiently irritated by it to follow up on why, just been thinking "oh, I guess that's how it works".
```

**Comment by slotThe** [comment]
Mh, I can't reproduce this; at least with two monitors :/

**Comment by geekosaur** [comment]
As mentioned in the IRC snippet, I'm reproducing it locally (as is fizzie). The key seems to be that dmenu comes up on the screen with the mouse, not the focused screen, as fizzie said.

**Comment by slotThe** [comment]
Aha!  The pointer position is key here (I still had `updatePointer` on in my earlier testing).  This seems to be something that dmenu does [quite intentionally](https://git.suckless.org/dmenu/file/dmenu.c.html#l656).  It's looking at the focused window to decide which monitor to position itself on and, if there is no focused window, falls back to the cursor position

**Comment by geekosaur** [comment]
I had suspected something like that, again per the IRC log (mentioned on the first line, even). Dunno why it doesn't happen with i3; maybe it warps the cursor to the selected screen.

**Comment by liskin** [comment]
Isn't i3 reparenting? Perhaps they have a window for each screen, and then subwindows for the layout frames, even if empty. We don't have that. (This is really a wild guess, I've only seen i3 in images.)

**Comment by slotThe** [comment]
Don't think there is much we can do here?

**Comment by NMerkley** [comment]
Just FYI, I was able to work around this in my config with the following keybind for opening dmenu:
```
, ((modMask, xK_p), do
    (S monitor) <- gets (W.screen . W.current . windowset)
    spawn $ "dmenu_run -m " ++ show monitor)
```

**Comment by lucaraymaekers** [comment]
That gives me an error that the last statement must be an expression, I am sure I typed it the same

**Comment by geekosaur** [comment]
Looks to me like the last statement is an expression. Check your indentation; it is significant.

**Comment by lucaraymaekers** [comment]
This is what I currently have, I am sorry to trouble you once again.
So when I (re)start xmonad, I get: <br>"parse error (possibly indentation or mismatched brackets",<br>but I only use spaces. So I don't see what's wrong
```  
  -- launch dmenu
    , ((modm,               xK_p     ), do
        (S monitor_ Z- gets (W.screen . W.current . windowset)
        spawn $ "dmenu_run -m " ++ show monitor)
```
also an arrow, points at the s of spawn, it should be on that line?

**Comment by lucaraymaekers** [comment]
Nevermind... It worked like a charm! :)) Also forgive me, I am new to everything including github.
