### ISSUE TITLE
HLS Wrapper fails with Xmonad

### ISSUE THREAD

**Issue by jordan-josephs** [xmonad/xmonad#385]
Hi all,

I recently setup HLS with Emacs lsp on my arch linux install. I wanted to set this up to get more information when messing around with my xmonad config. But with following the instructions for setting up HLS w/ emacs, emacs seems to load everything fine but nothing ever shows up (ie. LSP information like lens). I ran haskell-language-server-wrapper in my xmonad config directory and it failed with error in the picture attached. I don't know if this is a HLS issue or an XMonad issue or a me issue. If someone has any insight that would be amazing.

Error Message :
https://imgur.com/CKwQU2k

I have posted this on the HLS github but I am curious if this is an arch xmonad issue?

**Comment by geekosaur** [comment]
That is a *bizarre* failure. I'd be tempted to suspect Arch first given the various things they do to Haskell linking, but this is weird even for them. It smacks of the kind of weirdness you might see if also using Nix, and system and Nix objects somehow got muddled together. (It shouldn't even be possible if using only system objects.)

**Comment by jordan-josephs** [comment]
See and thats the crazy thing because I installed xmonad with stack and installed stack with their own installation script. So how could it have a dependency to an arch package.

**Comment by geekosaur** [comment]
All C libraries, and xmonad uses many, come from Arch packages. And this error in particular involves a core system library (libpthread).

**Comment by jordan-josephs** [comment]
Ah I see. So there really isn't anything I can do? Short of maybe reinstalling arch?

**Comment by geekosaur** [comment]
I have no idea. Like I said, that's a *bizarre* error. The only thing I can think of is that HLS is statically linked to the wrong glibc version… but static linking to glibc is something that should basically never happen, because this is the least of the errors it can cause.

**Comment by geekosaur** [comment]
Come to think of it, how did you install HLS? Did it come from ghcup? It might be worth finding out if it can easily be recompiled on your system (this would be a ghcup question).

**Comment by jordan-josephs** [comment]
I installed HLS via the AUR package haskell-language-server-static

**Comment by geekosaur** [comment]
That makes it even worse… *really* should not happen in that case; libpthread shouldn't even be dynamically loaded in that case, I think. I'd like to hear what the HLS folks have to say about this one.

**Comment by jordan-josephs** [comment]
I have already create the same issue over there. Waiting for some information.

**Comment by TheMC47** [comment]
Can you link your stack.yaml (and maybe hie.yaml)? It works on [my setup](https://github.com/TheMC47/dotfiles/tree/master/xmonad/.xmonad)

**Comment by jordan-josephs** [comment]
@TheMC47  Sure thing

stack.yaml - https://termbin.com/w9ub

hie.yaml - https://termbin.com/tbt1 -- auto generated using gen-hie

I would like to add that since this post I have uninstalled everything related to stack and ghc then reinstalled it using GHCup, and I am still getting this error. I have tried a VM using the linux kernel and lts kernel both with the same error. So I am starting to think this is a me issue.

**Comment by TheMC47** [comment]
Can you maybe use a different resolver? Maybe the GHC version you're using isn't working with the HLS server.

I strongly believe this has nothing to do with xmonad, so maybe open an issue somewhere else where people who know more can help you better than we can

**Comment by jordan-josephs** [comment]
@TheMC47  I do have one open on the HLS github. Unfortunately haven't had much luck other than being pointed that is an arch issue or to just ghcup.

**Comment by jordan-josephs** [comment]
I tried editing the resolve line in stack.yaml but it still used 9.0.2? I am pretty new to stack and haskell.

**Comment by TheMC47** [comment]
Can you try using the one I have in my stack.yaml? It definitely works with HLS

**Comment by geekosaur** [comment]
I guess we're not the only ones frustrated with Arch's handling of Haskell-related issues. 😃 But as I commented earlier, this is extreme even for Arch. I'd be inclined to agree with trying ghcup, but you said you already tried that. I'm lost at this point, I'm afraid.

All I can think of is search your system (see the `find` command) for extra copies of HLS or of `libpthread.so`.

**Comment by jordan-josephs** [comment]
@TheMC47  I tried your stack.yaml but now HLS cannot find any installation candidates. HLS is installed with ghcup.

@geekosaur  I have always been really annoyed with Arch's handling of Haskell. It makes it so difficult for someone new and trying to learn to setup a dev environment.

**Comment by jordan-josephs** [comment]
OKAY so it FINALLY worked. I changed the resolver to  lts18.28 and it worked. I appreciate everyones help and advice. Lets hope I dont run into any issues soon haha.
