### ISSUE TITLE
Float EAC Windows when launching games

### ISSUE THREAD

**Issue by jordan-josephs** [xmonad/xmonad#386]
This isn't an issue with XMonad but just a question. I was wondering if there exists a way to float those pesky EAC windows that pop up when I launch games from Steam. Xprop returns no useful information to use other than PID. I have in my manageHook isFullScreen --> doFullFloat but the problem is those windows dont want fullscreen that only draw a small rectangle which then XMonad tiles it. If anyone could give me a suggestion that would be awesome!

**Comment by geekosaur** [comment]
You might be able to match it by size, which you can get by using `xwininfo` on it.

**Comment by jordan-josephs** [comment]
I thought about that to but I can't get accurate info to apply to the window.

**Comment by geekosaur** [comment]
You mean it changes each time, or you don't know how to get that information in a `manageHook`?

**Comment by jordan-josephs** [comment]
I don't know how to get that information in a manageHook. Sorry I didn't specify.

**Comment by geekosaur** [comment]
It's something like:
```haskell
ask >>= \w ->
liftX (asks display) >>= \d ->
liftIO (getWindowAttributes d w) >>=
\(WindowAttributes {wa_x = x, wa_y = y, wa_width = w, wa_height = h}) ->
  if w == someWidth && h == someHeight
    then doFloat
    else idHook
```
This requires an extra import:
```haskell
import Graphics.X11.Xlib.Extras
```

**Comment by jordan-josephs** [comment]
I tried that and it didn't work. The window still tiled like before.

**Comment by jordan-josephs** [comment]
myManageHook :: XMonad.Query (Data.Monoid.Endo WindowSet)
myManageHook = composeAll
     [ className =? "confirm"         --> doFloat
     , className =? "file_progress"   --> doFloat
     , className =? "dialog"          --> doFloat
     , className =? "download"        --> doFloat
     , className =? "error"           --> doFloat
     , className =? "Gimp"            --> doFloat
     , className =? "net-runelite-launcher-Launcher"         --> doFloat
     , className =? "Signal"       --> doFloat
     , className =? "Minecraft* 1.18.1" --> doFloat
     , className =? "gitkraken"       --> doFloat
     , isFullscreen -->  doFullFloat
     ] <+> namedScratchpadManageHook myScratchPads <+> myCustomManageHook

myCustomManageHook :: ManageHook
myCustomManageHook = composeAll [ask >>= \w ->
                                 liftX (asks display) >>= \d ->
                                 liftIO (getWindowAttributes d w) >>=
                                \(WindowAttributes {wa_x = x, wa_y = y, wa_width = w, wa_height = h}) ->
                                if w == 800 && h == 450
                                 then doFloat
                                else idHook
                                ]

This is how I added that code. I just want to make sure I added it correctly. I am relatively new to haskell.

**Comment by geekosaur** [comment]
Sorry for the delay.

If you'd added it incorrectly then it should produce a compile error, not fail to work. I am wondering if it needs to have the border (not) accounted for, although the numbers seem suspiciously round for that. You may need to subtract or add 2× the border width from both `w` and `h`, since this happens with the window's original size not accounting for the border.

**Comment by slotThe** [comment]
I will assume that this is fixed
