### ISSUE TITLE
internal error: evacuate: strange closure type 4721 (Xmonad with 9.2.2 on ubuntu)

### ISSUE THREAD

**Issue by Abastro** [xmonad/xmonad#389]
### Problem Description

When I set up a simple test xmonad instance on GHC 9.2.2, it crashes often (usually when I press a key).

I got the following in the error log (took time to catch this one).

```
xmonad-x86_64-linux: internal error: evacuate: strange closure type 4721
    (GHC version 9.2.2 for x86_64_unknown_linux)
    Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

(Xmonad is quite a complex project to report a bug on GHC though)

### Steps to Reproduce

Quite unpredictable, but usually when:
1. Run xmonad with a desktop file in /usr/share/xsessions on ubuntu
2. Press Super+D or Super+Q to have xmonad do some "action"
3. Crashes occasionally

### Configuration File

```haskell
module Main where

import XMonad
import XMonad.Config.Desktop
import XMonad.Config.Gnome
import XMonad.Hooks.EwmhDesktops
import XMonad.Hooks.SetWMName
import XMonad.Util.EZConfig
import XMonad.Util.Run

main :: IO ()
main = do
  --dirs <- getDirectories
  --let xmDir = cfgDir dirs
  spawn "feh --bg-scale $HOME/Pictures/Universe/Andromeda_Galaxy.jpg"

  xmonad . ewmhFullscreen $
    desktopConfig
      { modMask = mod4Mask,
        startupHook = startupHook desktopConfig <> do
          setWMName "LG3D"
          gnomeRegister, -- Registers xmonad with gnome
        terminal = "gnome-terminal"
        --manageHook =  isDialog --> doFloat
      }
      `additionalKeysP` [("M-d", safeSpawnProg "nautilus")]

```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0
    - [x] With `xmonad-contrib` version 0.17.0

**Comment by geekosaur** [comment]
For the record, we're trying it with a minimal config (`main = xmonad def`) to see if it still happens. I can't say I expect much to change, though.

Also for the record, I ran most of a day with [my config](https://github.com/geekosaur/xmonad.hs/blob/skkukuk/xmonad.hs) under 9.2.2 and couldn't reproduce it.

About the only significant difference is `gnomeRegister`, but that would be really weird as that uses `dbus-send`. I use actual DBus (for [xmonad-log-applet](https://github.com/jgoerzen/xmonad-log-applet)), which I would expect to be far more likely to lead to such crashes.

**Comment by Abastro** [comment]
Tried with both `xmonad def` and `xmonad desktopConfig`. It is harder to crash with `xmonad def`, while with `xmonad desktopConfig` simply clicking make it crash.
Also, it crashes more often when using custom XMONAD_CONFIG_DIR etc. and a custom build script. Build script itself works fine (it logs so).

**Comment by geekosaur** [comment]
One thing that sticks out to me is all of this involves X11 properties: `desktopConfig` is `ewmh . docks $ def` (`ewmh` sets a bunch of EWMH properties in every run of the `logHook`, and `docks` reads strut properties in the `manageHook`) and `xmonad --restart` sets a root window property to tell the running `xmonad` to restart itself. But that property doesn't change just because you set `XMONAD_CONFIG_DIR`. (Then again, this could all be just because we exercise the heap more and are more likely to run into corruption as a result.)

And none of this explains why my own config didn't trigger it despite using even more X11 properties.

**Comment by geekosaur** [comment]
I've been running `main = xmonad desktopConfig` in a Xephyr for several hours now, no crashes.
*(edited: whoops, not that config!)*

**Comment by geekosaur** [comment]
@Abastro just noted that they build with `-dynamic`. If the crash goes away without it, we probably do have a GHC bug.

**Comment by geekosaur** [comment]
I left it running overnight after rebuilding with `-dynamic` and still no crash.

**Comment by portnov** [comment]
In my experience with different Haskell programs, I've seen similar message only in two types of cases:
* hardware problem with RAM (but in such situations you usually see almost all programs crashing randomly);
* GHC bug.

**Comment by geekosaur** [comment]
We've seen similar bugs with buggy FFI bindings, which can indeed corrupt the heap. And we've had such bugs in the X11 bindings in the past.  But the fact that I can't reproduce it is suspicious; were it a GHC or FFI bug you'd think I could repro it fairly easily.

**Comment by geekosaur** [comment]
Also they have been working on dynamic linking recently, but I don't know how much of that made 9.2.2 and I think it's supposed to be limited to Windows.

**Comment by Abastro** [comment]
Just tried testing using config inside `~/.xmonad` with build script inside it. No crash there.

**Comment by geekosaur** [comment]
To be more specific, apparently using `$XMONAD_CONFIG_DIR` is necessary to provoke the crashes. Which doesn't make a lot of sense. Sadly I won't be able to debug this today, I'll be away at a family event for most of the day.

**Comment by geekosaur** [comment]
Tried it, with only `$XMONAD_CONFIG_DIR` and with all three, *still* can't reproduce.

**Comment by LSLeary** [comment]
Recently, maybe a day or two after I got my big old config working again, I started getting crashes from segfaults with my GHC 9.2.2 compiled xmonad. Before then, I'd been using a simple config for over a week without any problems.

It might be unrelated to this issue, as I've seen no mention of strange closures, nor am I using `$XMONAD_CONFIG_DIR`.

I don't know my way around coredumps, but I searched through the textual portions of the last three, and most of it seemed to concern fonts (which my big layout does use in the form of window decorations).

From my system logs:

Segfault 1:
```
Apr 27 16:54:53 nazuna kernel: show_signal_msg: 8 callbacks suppressed
Apr 27 16:54:53 nazuna kernel: xmonad-x86_64-l[1178]: segfault at 1a44d ip 0000000000504c60 sp 00007ffe51bfbd98 error 4 in xmonad-x86_64-linux[400000+2be000]
Apr 27 16:54:53 nazuna kernel: Code: 55 f8 48 89 45 00 48 83 c5 e8 f6 c3 07 75 13 ff 23 90 05 00 00 00 00 00 00 00 1e 00 00 00 00 00 00 00 48 c7 45 f8 98 4c 50 00 <48> 8b 43 07 48 8b 5b 0f 48 89 d9 48 8b 5d 20 48 89 4d 00 48 89 45
Apr 27 16:54:53 nazuna systemd[1]: Created slice Slice /system/systemd-coredump.
Apr 27 16:54:53 nazuna systemd[1]: Started Process Core Dump (PID 1475/UID 0).
Apr 27 16:54:53 nazuna systemd-coredump[1476]: Process 1178 (xmonad-x86_64-l) of user 1000 dumped core.
                                               
                                               Found module /home/leary/.cache/xmonad/xmonad-x86_64-linux without build-id.
                                               Found module linux-vdso.so.1 with build-id: 4c8457eb017b4283755d13aacf5d33cf35cd845d
                                               Found module libXdmcp.so.6 without build-id.
                                               Found module libXau.so.6 without build-id.
                                               Found module libexpat.so.1 without build-id.
                                               Found module ld-linux-x86-64.so.2 with build-id: 30c57076927b082f79b8e0307c2ade477e78866b
                                               Found module libxcb.so.1 without build-id.
                                               Found module libXrender.so.1 without build-id.
                                               Found module libpthread.so.0 with build-id: 7e1bb32908f70cf0fc00d66c983160c7b115f188
                                               Found module libz.so.1 without build-id.
                                               Found module libpng16.so.16 without build-id.
                                               Found module libbz2.so.1 without build-id.
                                               Found module libfontconfig.so.1 without build-id.
                                               Found module libffi.so.8 without build-id.
                                               Found module libdl.so.2 with build-id: c06f3da244980c9a6e8e2a1e4d8990a085103471
                                               Found module librt.so.1 with build-id: f610c78fef64474570c8ba2b5c00427c340d1e84
                                               Found module libm.so.6 with build-id: bb1ad44ec0afbc9acf56402168c25a629dfd7adb
                                               Found module libc.so.6 with build-id: b2073195a02092e5988e0c88ddbe22da749f69ac
                                               Found module libgmp.so.10 without build-id.
                                               Found module libXrandr.so.2 without build-id.
                                               Found module libX11.so.6 without build-id.
                                               Found module libXext.so.6 without build-id.
                                               Found module libXinerama.so.1 without build-id.
                                               Found module libXss.so.1 without build-id.
                                               Found module libfreetype.so.6 without build-id.
                                               Found module libXft.so.2 without build-id.
                                               Stack trace of thread 1178:
                                               #0  0x0000000000504c60 n/a (/home/leary/.cache/xmonad/xmonad-x86_64-linux + 0x104c60)
Apr 27 16:54:53 nazuna xsession[1152]: /nix/store/kzv9619lc09mjwmmav176a2cc52hqkkz-xsession: line 20:  1178 Segmentation fault      (core dumped) systemd-cat -t xmonad -- /nix/store/ksbq19myj21iscy85v7y6cf7ss09spp5-xmonad-with-packages-9.2.2/bin/xmonad
Apr 27 16:54:53 nazuna systemd[1]: systemd-coredump@0-1475-0.service: Deactivated successfully.
```

Segfault 2:
```
Apr 27 16:55:31 nazuna kernel: xmonad-x86_64-l[1710]: segfault at 21 ip 00007f268d39e8bc sp 00007ffc61034440 error 4 in libX11.so.6.4.0[7f268d38c000+8c000]
Apr 27 16:55:31 nazuna kernel: Code: 64 48 8b 04 25 28 00 00 00 48 89 44 24 48 31 c0 48 8d 05 2f 97 08 00 48 85 f6 4c 0f 44 e0 48 8b 87 68 09 00 00 48 85 c0 74 02 <ff> 10 48 8d 4c 24 18 4c 8d 4c 24 14 44 89 ea 4c 89 e6 4c 8d 44 24
Apr 27 16:55:31 nazuna systemd[1]: Started Process Core Dump (PID 1840/UID 0).
Apr 27 16:55:31 nazuna systemd-coredump[1841]: Process 1710 (xmonad-x86_64-l) of user 1000 dumped core.
                                               
                                               Found module /home/leary/.cache/xmonad/xmonad-x86_64-linux without build-id.
                                               Found module linux-vdso.so.1 with build-id: 4c8457eb017b4283755d13aacf5d33cf35cd845d
                                               Found module libXdmcp.so.6 without build-id.
                                               Found module libXau.so.6 without build-id.
                                               Found module libexpat.so.1 without build-id.
                                               Found module ld-linux-x86-64.so.2 with build-id: 30c57076927b082f79b8e0307c2ade477e78866b
                                               Found module libxcb.so.1 without build-id.
                                               Found module libXrender.so.1 without build-id.
                                               Found module libpthread.so.0 with build-id: 7e1bb32908f70cf0fc00d66c983160c7b115f188
                                               Found module libz.so.1 without build-id.
                                               Found module libpng16.so.16 without build-id.
                                               Found module libbz2.so.1 without build-id.
                                               Found module libfontconfig.so.1 without build-id.
                                               Found module libffi.so.8 without build-id.
                                               Found module libdl.so.2 with build-id: c06f3da244980c9a6e8e2a1e4d8990a085103471
                                               Found module librt.so.1 with build-id: f610c78fef64474570c8ba2b5c00427c340d1e84
                                               Found module libm.so.6 with build-id: bb1ad44ec0afbc9acf56402168c25a629dfd7adb
                                               Found module libc.so.6 with build-id: b2073195a02092e5988e0c88ddbe22da749f69ac
                                               Found module libgmp.so.10 without build-id.
                                               Found module libXrandr.so.2 without build-id.
                                               Found module libX11.so.6 without build-id.
                                               Found module libXext.so.6 without build-id.
                                               Found module libXinerama.so.1 without build-id.
                                               Found module libXss.so.1 without build-id.
                                               Found module libfreetype.so.6 without build-id.
                                               Found module libXft.so.2 without build-id.
                                               Stack trace of thread 1710:
                                               #0  0x00007f268d39e8bc XInternAtom (libX11.so.6 + 0x308bc)
                                               #1  0x00000000004d0dd3 n/a (/home/leary/.cache/xmonad/xmonad-x86_64-linux + 0xd0dd3)
Apr 27 16:55:31 nazuna systemd[1]: systemd-coredump@1-1840-0.service: Deactivated successfully.
```

Segfault 3:
```
Apr 27 17:04:58 nazuna kernel: xmonad-x86_64-l[3864]: segfault at ffffffffffffffe9 ip 0000000000672fc8 sp 00007fff52106e98 error 5 in xmonad-x86_64-linux[400000+2be000]
Apr 27 17:04:58 nazuna kernel: Code: 31 d2 eb 0f 48 8b 33 48 89 74 d5 00 48 83 c3 08 48 ff c2 48 39 c2 72 ec 48 8b 59 10 48 89 d8 48 83 e0 f8 48 8b 00 48 83 c0 d8 <48> 63 48 10 48 85 c9 74 3c 48 83 f9 01 74 36 48 83 f9 02 74 0e 48
Apr 27 17:04:58 nazuna systemd[1]: Started Process Core Dump (PID 3938/UID 0).
Apr 27 17:04:58 nazuna systemd-coredump[3939]: Process 3864 (xmonad-x86_64-l) of user 1000 dumped core.
                                               
                                               Found module /home/leary/.cache/xmonad/xmonad-x86_64-linux without build-id.
                                               Found module linux-vdso.so.1 with build-id: 4c8457eb017b4283755d13aacf5d33cf35cd845d
                                               Found module libXdmcp.so.6 without build-id.
                                               Found module libXau.so.6 without build-id.
                                               Found module libexpat.so.1 without build-id.
                                               Found module ld-linux-x86-64.so.2 with build-id: 30c57076927b082f79b8e0307c2ade477e78866b
                                               Found module libxcb.so.1 without build-id.
                                               Found module libXrender.so.1 without build-id.
                                               Found module libpthread.so.0 with build-id: 7e1bb32908f70cf0fc00d66c983160c7b115f188
                                               Found module libz.so.1 without build-id.
                                               Found module libpng16.so.16 without build-id.
                                               Found module libbz2.so.1 without build-id.
                                               Found module libfontconfig.so.1 without build-id.
                                               Found module libffi.so.8 without build-id.
                                               Found module libdl.so.2 with build-id: c06f3da244980c9a6e8e2a1e4d8990a085103471
                                               Found module librt.so.1 with build-id: f610c78fef64474570c8ba2b5c00427c340d1e84
                                               Found module libm.so.6 with build-id: bb1ad44ec0afbc9acf56402168c25a629dfd7adb
                                               Found module libc.so.6 with build-id: b2073195a02092e5988e0c88ddbe22da749f69ac
                                               Found module libgmp.so.10 without build-id.
                                               Found module libXrandr.so.2 without build-id.
                                               Found module libX11.so.6 without build-id.
                                               Found module libXext.so.6 without build-id.
                                               Found module libXinerama.so.1 without build-id.
                                               Found module libXss.so.1 without build-id.
                                               Found module libfreetype.so.6 without build-id.
                                               Found module libXft.so.2 without build-id.
                                               Stack trace of thread 3864:
                                               #0  0x0000000000672fc8 n/a (/home/leary/.cache/xmonad/xmonad-x86_64-linux + 0x272fc8)
Apr 27 17:04:58 nazuna xsession[3852]: /nix/store/kzv9619lc09mjwmmav176a2cc52hqkkz-xsession: line 20:  3864 Segmentation fault      (core dumped) systemd-cat -t xmonad -- /nix/store/ksbq19myj21iscy85v7y6cf7ss09spp5-xmonad-with-packages-9.2.2/bin/xmonad
Apr 27 17:04:58 nazuna systemd[1]: systemd-coredump@2-3938-0.service: Deactivated successfully.
```

**Comment by geekosaur** [comment]
That's worrisome because a crash in (say) font code would have shown a proper stack trace until it reached the xmonad executable. (The fact that libXft.so.2 is shown last doesn't mean it was where it crashed, it just means it's the last library the linker attached to the executable at compile time.)

I'm tempted to suggest you try compiling with -dynamic just to see if it crashes in one of the Haskell libraries.

**Comment by geekosaur** [comment]
Has this been submitted upstream to ghc yet? If nothing else, they should have better ideas for trying to track it down.

**Comment by Abastro** [comment]
No, I was waiting for it to be reproduced by someone else.

**Comment by tbidne** [comment]
I've been seeing segfaults similar to what @LSLeary posted every now and then (GHC 9.2.2). I do not recall segfaults with GHC 8.10.7.

```sh
Jun 02 13:34:46 nixos xsession[8127]: /nix/store/mx243ajjsak10wbv782fwvz01jj9yk80-xsession: line 21:  8152 Segmentation fault      (core dumped) systemd-cat -t xmonad -- /nix/store/cihviqq6mlkjihk442ga8mli3jyd6hy8-xmonad/bin/xmonad
Jun 02 13:34:46 nixos systemd[1]: systemd-coredump@1-10817-0.service: Deactivated successfully.
Jun 02 13:34:46 nixos systemd-coredump[10818]: Process 8152 (xmonad) of user 1000 dumped core.
                                               
                                               Module linux-vdso.so.1 with build-id 95945c6f4f0a2d417f23f38a4d5cb85d7df2f0ad
                                               Module libXdmcp.so.6 without build-id.
                                               Module libXau.so.6 without build-id.
                                               Module libexpat.so.1 without build-id.
                                               Module ld-linux-x86-64.so.2 with build-id 2d4e3d041d24aa7a72377e8cc41e9336abd77ffb
                                               Module libxcb.so.1 without build-id.
                                               Module libXrender.so.1 without build-id.
                                               Module libpthread.so.0 with build-id bff749b993405063a72406b65328ce34b1d20b2b
                                               Module libpng16.so.16 without build-id.
                                               Module libbz2.so.1 without build-id.
                                               Module libfontconfig.so.1 without build-id.
                                               Module libffi.so.8 without build-id.
                                               Module libdl.so.2 with build-id a4bfa88c56b19d9a13f5191cfe661e9b9f32140a
                                               Module librt.so.1 with build-id 81dcc5b293a378ea5ee6ff8ba1e67b8f55381439
                                               Module libm.so.6 with build-id ab70ae196025b3056f0fc0ed85a43390cda0ea4a
                                               Module libc.so.6 with build-id c512f38583c48b03cc0011d4583d15cea2e94d03
                                               Module libgmp.so.10 without build-id.
                                               Module libXrandr.so.2 without build-id.
                                               Module libX11.so.6 without build-id.
                                               Module libXext.so.6 without build-id.
                                               Module libXinerama.so.1 without build-id.
                                               Module libXss.so.1 without build-id.
                                               Module libfreetype.so.6 without build-id.
                                               Module libXft.so.2 without build-id.
                                               Module libz.so.1 without build-id.
                                               Module xmonad without build-id.
                                               Stack trace of thread 8152:
                                               #0  0x0000000000689225 scavenge_mutable_list (xmonad + 0x289225)
                                               #1  0x0000000000689424 scavenge_capability_mut_lists (xmonad + 0x289424)
                                               #2  0x00000000006845c5 GarbageCollect (xmonad + 0x2845c5)
                                               #3  0x000000000067c1ab scheduleDoGC.constprop.0.isra.0 (xmonad + 0x27c1ab)
                                               #4  0x000000000067cc86 scheduleWaitThread (xmonad + 0x27cc86)
                                               #5  0x000000000067ae2f hs_main (xmonad + 0x27ae2f)
                                               #6  0x000000000041bb8c main (xmonad + 0x1bb8c)
                                               #7  0x00007f6bf7ce7237 __libc_start_call_main (libc.so.6 + 0x29237)
                                               #8  0x00007f6bf7ce72f5 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x292f5)
                                               #9  0x000000000040fb51 _start (xmonad + 0xfb51)
                                               ELF object binary architecture: AMD x86-64
Jun 02 13:34:46 nixos systemd[1]: Started Process Core Dump (PID 10817/UID 0).
Jun 02 13:34:46 nixos kernel: Code: 84 ba 01 00 00 4c 89 e7 e8 48 fa ff ff 84 c0 0f 85 ee 00 00 00 48 8b 04 24 49 83 c6 08 4c 39 70 08 0f 86 1b 01 00 00 4d 8b 26 <49> 8b 04 24 8b 40 f8 83 f8 2c 75 9f 0f b6 05 8d 7f 09 00 c6 05 86
Jun 02 13:34:46 nixos kernel: xmonad[8152]: segfault at 1c ip 0000000000689225 sp 00007fff2e9f7760 error 4 in xmonad[400000+2dd000]
Jun 02 13:33:55 nixos xmonad[8152]: Enum.toEnum{Word8}: tag (9679) is outside of bounds (0,255)
Jun 02 13:33:11 nixos xmonad[8152]: Enum.toEnum{Word8}: tag (9679) is outside of bounds (0,255)
```

I believe the `toEnum` warnings are possibly a red-herring as they do not always accompany the segfault, but I included them in case it means something to anyone.

Judging by the logs, fonts do seem suspicious. My config is [here](https://github.com/tbidne/nix-config/blob/main/system/config.hs), not that I expect it offers much insight.

**Comment by dunrix** [comment]
I can confirm similar behavior, sudden random crash of entire session when xmonad was compiled with GHC 9.1.x or 9.2.x .

As a long time xmonad user (5+ years), never experienced such issue, it always did felt rock-stable.

relevant lines from xsession error log:

> xmonad: X11 error: BadAtom (invalid Atom parameter), request code=18, error code=5
> xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":0"
> X connection to :0 broken (explicit kill or server shutdown).

Inspired by @tbidne, I've tinkered with font settings, both for xmonad(-contrib) features and xmobar.

It seemingly (so far) improved stability:
 - changing font identifier format from "xft:\<font name\>:size=\<font size\>" to "xft:\<font name\>-\<font size\>"
 - replacing (my favorite) font Terminus with other like Noto Sans Mono

It seems like changes in GHC code exposed some not yet manifested bug in C bindings (resource leak?) which xmonad depends upon, like *X11-xft*.

bottom note: I can reproduce xmonad/X11 session crash more reliably when invoking `XMonad.Prompt.Shell.shellPrompt` after `xmonad --restart` with original font settings.

**Comment by geekosaur** [comment]
Yes, that seems to narrow it down to a possible pointer issue in X11-xft. Which gives me somewhere to look, at least.

Out of curiosity, can you try running xmonad with `xmonad +RTS -c` and see how it affects things? This uses a different garbage collector, not that I expect it to change things appreciably, but it might rule out problems with GC itself (note that the original report had this happening with a nearly-bare config that certainly didn't use X11-xft, although it may have been linked against it at least).

**Comment by geekosaur** [comment]
The other problem being that I ran for a while on 9.2.2 with my config, which does use XFT, and saw no crashes. Whatever this is, it's trying really hard to not be obvious. :(

**Comment by slotThe** [comment]
On Wed, Jun 15 2022 12:19, dunrix wrote:
> I can confirm similar behavior, sudden random crash of entire session
> when xmonad was compiled with GHC 9.1.x or 9.2.x .

Is this also with the new 9.2.3?  I was hoping it would "fix itself"
with that version.

> bottom note: I can reproduce xmonad/X11 session crash more reliably
> when invoking `XMonad.Prompt.Shell.shellPrompt` after `xmonad
> --restart` with original font settings.

How reliable is that?  Reliable enough so that you could post a recipe
here?  Once we can actually reproduce the bug then it might be time to
bisect GHC (which is going to be really fun!)

**Comment by geekosaur** [comment]
Sadly that would probably still leave us with https://github.com/xmonad/xmonad/issues/389#issuecomment-1100195901. And I still have my doubts that this is GHC's fault, given the amount of X11-related FFI we do.

**Comment by dunrix** [comment]
@geekosaur 
> Out of curiosity, can you try running xmonad with `xmonad +RTS -c` and see how it affects things?

Thanks for your reply.
I did tried run xmonad with suggested runtime option, however it seems had no difference, as xmonad did crashed after several minutes, with the original config.

**Comment by dunrix** [comment]
> Is this also with the new 9.2.3? I was hoping it would "fix itself" with that version.

@slotThe I did hoped too, unfortunately the issue persists even with the latest version.

> How reliable is that?  Reliable enough so that you could post a recipe
here?  Once we can actually reproduce the bug then it might be time to
bisect GHC (which is going to be really fun!)

I do not keep a statistic but session usually crashes in about less then five attempts of xmonad --recompile && xmonad --restart, shellPrompt spawn cycle.

I'll try to create and test on some simplest possible xmonad config with most defaults and post steps here after I will become more confident about it.

**Comment by Abastro** [comment]
GHC issue posted: https://gitlab.haskell.org/ghc/ghc/-/issues/21708

Suggested diagnostics were:
- recompile with debug information enabled (using cabal's  --enable-debug-info=3 flag)
- recompile against the debug RTS (using GHC's -debug flag; e.g. ghc-options: -debug in your .cabal file)
- run your program with +RTS -DS
- gather core dump (or even better, an [rr trace](https://rr-project.org/))

I'd try a test with GHC 9.2.2 with these options later when I got some time.

**Comment by geekosaur** [comment]
Catching up here:

* using the non-moving GC had no effect
* @bgamari and I have been debugging on https://gitlab.haskell.org/ghc/ghc/-/issues/21708. Turns out that
  * it reproduces readily with `-threaded +RTS -N2` and up, but not with `-N1` (default)
  * `XNextEvent` is smashing the heap in that configuration
  * @bgamari reports 9.2's generated code looks correct, but it otherwise looks as if `keepAlive#` is not being applied correctly

**Comment by geekosaur** [comment]
I'll add that `allocaXEvent` appears to be correct, which seems to put the ball firmly in GHC's court.

**Comment by geekosaur** [comment]
```
[27 19:48:45] <bgamari> geekosaur, the "Mess" abbreviation of Message in xmonad leads to some rather humorous names
[27 19:49:37] <geekosaur> heh
[27 19:50:36] <bgamari> in other news, there is at least one assertion failure in xmonad-contrib when compiled with a DEBUG compiler
[27 19:50:49] <bgamari> unfortunately I suspect it's unrelated to the crash
[27 19:51:01] <bgamari> but nevertheless, it's at least a thread to pull
[27 19:51:16] <bgamari> otherwise I spent quite a while starting at the execution state last week
[27 19:51:52] <bgamari> and it appears that a ByteArray# is somehow becoming unreachable despite there being a keepAlive# on it
[27 19:52:05] <bgamari> don't yet know why
[27 19:52:05] <geekosaur> lovely
```

**Comment by geekosaur** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/21708#note_440043 has a reproducer; we do in fact have a compiler bug, triggered by the `forever` which causes Cmm to think it's unreachable because it never returns. It's a pity GitHub and Gitlab don't play well together.

**Comment by geekosaur** [comment]
#404 is an attempted workaround by avoiding `forever` and hopefully being complex enough that it doesn't also trigger the Cmm optimizer bug. Would anyone like to see if it works for them?

**Comment by tbidne** [comment]
@geekosaur Thanks for the quick turnaround! I have rebuilt my system on your branch. Unfortunately I only saw the issue sporadically, so the best I can do is wait for errors. But I was seeing the crash every few days or so, so if I don't see anything for, say, a week, I'd take that as a good sign.

For other nix users, [this](https://github.com/tbidne/nix-config/commit/5ba3b5be92861ea213b57e9086621fd9e86bf395) is what I did to use the fork (scroll down to `flake.nix` for the important bits).

**Comment by saep** [comment]
The Branch https://github.com/xmonad/xmonad/pull/404@geekosaur works for me. My XMonad configuration always crashed shortly after starting it when compiled with GHC version 9.2.2. I've switched to that GHC version today.

**Comment by slotThe** [comment]
This is now also fixed with GHC 9.2.4: https://discourse.haskell.org/t/ghc-9-2-4-released/4851

Guess xmonad can still be useful for the Haskell ecosystem as a whole!

**Comment by tbidne** [comment]
Thanks everyone for the hard work!

**Comment by Abastro** [comment]
Just upgraded to GHC 9.2.4, going to check if the fixed bug was the culprit for me.
