### ISSUE TITLE
Firefox window freezing when mouse not moving in some situations

### ISSUE THREAD

**Issue by acarrico** [xmonad/xmonad#39]
This firefox bug occurs in xmonad:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1280284

Feel free to close this issue if xmonad isn't at fault.

**Comment by acarrico** [comment]
Firefox 47 does seem to work in xfce 4.12, which would point to an xmonad issue.

**Comment by geekosaur** [comment]
Window managers control window placement policy, They are not involved in application screen updates; that's solely between the rendering application and the X server, and xmonad can't even tell what's going on.

I am inclined to think that this sounds like a video driver issue (X11 pushes a lot of this stuff down into the video driver for historical reasons), but would need a lot more information before committing to an explanation. Also, if it's Flash video then it could be an event handling or timer event problem in Flash.

**Comment by acarrico** [comment]
That seems reasonable, except that the issues manifests reliably in  xmonad, but not in xfce4. The original person who opened the bug mentioned non-gnome desktop environment as well. I've also noticed xmonad (apparently) "swallowing" the first keystroke sometimes, at the terminal for example. I wonder if it is an input issue, rather than a display issue?

**Comment by acarrico** [comment]
I don't have flash installed, and in any case it happens all over Firefox, even in the profile manager dialog before the browser comes up, but I agree with your hunch that it has something to do with event handling. I don't know that speculaction point more toward a FF, or WM bug (or both).

**Comment by Delapouite** [comment]
According to arch guys, it seems more related to `xf86-video-intel` drivers : https://bbs.archlinux.org/viewtopic.php?id=213533&p=2

**Comment by geekosaur** [comment]
The link with xmonad is usually that xmonad (and dwm) uses X11 APIs that are very rarely tested in video driver backends, such as server side window borders, and regularly triggers bugs in those backends as a result. These bugs can sometimes be quite unintuitive (we've seen some really bizarre bugs that ultimately went away upon upgrading or downgrading the video driver). Apps can also contribute to this if they e.g. assume that a focus change is always signaled by crossing a frame window (as a nonreparenting window manager, we don't have frame windows; this is also why Java and Mono canvas widgets are always a bit deranged in xmonad, although Java at least provides ugly workarounds).

**Comment by acarrico** [comment]
I tried "uxa" acceleration, and that solves it. Wow, one hour from opening the bug to a fix, and it wasn't even in xmonad. Nice work.

**Comment by acarrico** [comment]
Removing the xf86-video-intel driver also fixes the problem. Thanks again.
