### ISSUE TITLE
Xmonad Freezes whilst Resizing Windows 

### ISSUE THREAD

**Issue by Scherso** [xmonad/xmonad#394]
### Problem Description

While resizing a window, using my mod-key and left click, after a couple resizes I am locked to a window. Xmonad’s default keybindings stop working, and using my mouse to click any contents of the window I am in also does not work. 

- While frozen, the cursor displayed on my screen also is displayed as a cursor that would appear while you are resizing a window. 

This is most likely a user issue, I came to Xmonad with little Haskell experience, so if someone could point out what I am doing wrong, that would be very much appreciated.

### Steps to Reproduce

Download Xmonad through Arch Linux’s pac-man package manager, `sudo pacman -S xmonad`
Install `xmonad-contrib-git` from AUR, `yay -S xmonad-contrib-git`

Use my config file, it is in the drop down below. It uses [Xmonad’s default mouse-bindings](https://xmonad.org/images/cheat/xmbindings.png). While using my config, try resizing a window. The issue occurs most often after resizing a window inwards, and following that, resizing the same window outwards. 

<details open>
<summary>You can click here to minimize or expand my config file.</summary>
<br>

```haskell
import XMonad
import XMonad.Hooks.SetWMName
import XMonad.Hooks.EwmhDesktops
import XMonad.Hooks.ManageDocks
import XMonad.Hooks.DynamicLog
import XMonad.Util.EZConfig (additionalKeysP)
import XMonad.Util.Loggers
import XMonad.Util.Run
import XMonad.Util.SpawnOnce
import XMonad.Util.Ungrab
import XMonad.Layout.Spacing
import XMonad.Layout.ThreeColumns
import XMonad.Actions.NoBorders
import qualified Data.Map as M
import qualified XMonad.StackSet as W 

import System.Exit

myModMask :: KeyMask
myModMask = mod1Mask

myTerminal :: String
myTerminal = "alacritty"

myBrowser :: String
myBrowser = "firefox-developer-edition"

myKeys :: [(String, X ())]
myKeys =
  [ 
    -- Spawn a terminal instance.
    ("M-S-<Return>", spawn myTerminal),
    -- Spawn dmenu.
    ("M-p", spawn "dmenu_run"),
    -- Screenshot
    ("M-s", spawn "~/.local/bin/screenshot"),
    -- Toggle borders
    ("M-g", withFocused toggleBorder),

    -- Multimedia Keys
    ("<XF86AudioPlay>", spawn "playerctl play-pause"),
    ("<XF86AudioPrev>", spawn "playerctl previous"),
    ("<XF86AudioNext>", spawn "playerctl next"),
    ("<XF86AudioMute>", spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"),
    ("<XF86AudioLowerVolume>", spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%"),
    ("<XF86AudioRaiseVolume>", spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%"),

    -- Close the focused window.
    ("M-S-c", kill),

  -- Layout Configuration
    -- Switch to the next layout.
    ("M-<Space>", sendMessage NextLayout),
    -- Reset the layout to the workspace default.
    -- ("M-S-<Space>", setLayout $ XMonad.layoutHook conf),
    -- Resize viewed windows to the correct size.
    ("M-n", refresh),
    -- Move focus to the next window.
    ("M-<Tab>", windows W.focusDown),
    -- Move focus to the next window.
    ("M-j", windows W.focusDown),
    -- Move focus to the previous window.
    ("M-k", windows W.focusUp),
    -- Move focus to the master window.
    ("M-m", windows W.focusMaster),
    -- Swap the focused window with the master window.
    ("M-<Return>", windows W.swapMaster),
    -- Swap the focused window with the next window.
    ("M-S-j", windows W.swapDown),
    -- Swap the focused window with the previous window.
    ("M-S-k", windows W.swapUp),
    -- Shrink the master area.
    ("M-h", sendMessage Shrink),
    -- Expand the master area.
    ("M-l", sendMessage Expand),
    -- Re-tile a window.
    ("M-t", withFocused $ windows . W.sink),

  -- Xmonad
    -- Quit Xmonad
    ("M-S-q", io exitSuccess),
    -- Restart Xmonad
    ("M-q", spawn "xmonad --recompile ; killall xmobar ; xmonad --restart")
  ]

myMouseBindings XConfig {XMonad.modMask = modm} = M.fromList
    [ 
      -- Set the window floating mode and move via dragging.
      ((modm, button1), \w -> focus w >> mouseMoveWindow w
                                      >> windows W.shiftMaster),
      -- Raise the window to the top of the stack.
      ((modm, button2), \w -> focus w >> windows W.shiftMaster),
      -- Set the window to floating mode and resize by dragging.
      ((modm, button3), \w -> focus w >> mouseResizeWindow w
                                      >> windows W.shiftMaster)
    ]

myStartupHook :: X ()
myStartupHook = do
  spawnOnce "~/.fehbg"
  spawnOnce "picom"

myManageHook = composeAll
    [
      className =? "Gimp" --> doFloat,
      className =? "Steam" --> doFloat,
      resource =? "desktop_window" --> doIgnore,
      resource =? "kdesktop" --> doIgnore
    ]

myEventHook = mempty 

myGaps = spacingRaw
    False
    (Border 5 5 5 5)
    True
    (Border 5 5 5 5)
    True

myLayout = myGaps $ avoidStruts tiled ||| Mirror tiled ||| Full
  where
    tiled = Tall nmaster delta ratio
    nmaster = 1
    ratio = 1 / 2
    delta = 3 / 100

myXmobarPP :: PP
myXmobarPP = def
    { 
      ppSep = magenta " • ",
      ppTitleSanitize = xmobarStrip,
      ppCurrent = wrap " " "" . xmobarBorder "Top" "#8be9fd" 2,
      ppHidden = white . wrap " " "",
      ppHiddenNoWindows = lowWhite . wrap " " "",
      ppUrgent = red . wrap (yellow "!") (yellow "!"),
      ppOrder = \[ws, l, _, wins] -> [ws, l, wins],
      ppExtras = [logTitles formatFocused formatUnfocused]
    }
  where
    formatFocused = wrap (white "[") (white "]") . magenta . ppWindow
    formatUnfocused = wrap (lowWhite "[") (lowWhite "]") . blue . ppWindow

    -- Windows should have *some* title, which should not not exceed a
    -- sane length.
    ppWindow :: String -> String
    ppWindow = xmobarRaw . (\w -> if null w then "untitled" else w) . shorten 30

    blue, lowWhite, magenta, red, white, yellow :: String -> String
    magenta = xmobarColor "#c678dd" ""
    blue = xmobarColor "#61afef" ""
    white = xmobarColor "#abb2bf" ""
    yellow = xmobarColor "#e5c07b" ""
    red = xmobarColor "#e06c75" ""
    lowWhite = xmobarColor "#abb2bf" ""

myConfig = def
    { 
      modMask = myModMask,
      mouseBindings = myMouseBindings,
      borderWidth = 3,
      normalBorderColor = "#544862",
      focusedBorderColor = "#61AFEF",
      layoutHook = myLayout,
      startupHook = myStartupHook >> setWMName "LG3D",
      manageHook = myManageHook,
      handleEventHook = myEventHook
    } `additionalKeysP` myKeys

main :: IO ()
main = xmonad
    . docks
    . ewmhFullscreen
    . ewmh
    =<< statusBar "xmobar" def toggleStrutsKey myConfig
  where
    toggleStrutsKey :: XConfig Layout -> (KeyMask, KeySym)
    toggleStrutsKey XConfig {modMask = m} = (m, xK_b)
```

</details>

### Checklist

  - [ ✓] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [ ] With `xmonad` version 0.15-183 
    - [ ] With `xmonad-contrib` version v0.17.0

**Comment by geekosaur** [comment]
Is your `xmobar` correctly showing workspace information? If it is not configured with `StdinReader` then `xmonad` will freeze up trying to write to it, and resizing windows will make this happen fairly quickly because the `logHook` is run often during the resize.

Also, while this is not going to break anything as such, your `myLayout` has a couple of problems. It should probably look like
```hs
myLayout = avoidStruts $ myGaps $ tiled ||| Mirror tiled ||| Full
```

**Comment by Scherso** [comment]
Xmobar actually doesn’t correctly show information, you’re right. This is actually really helpful, thank you. 

I’ll test this in the next hour, and give an update when it works. I’ll also fix up `myLayout`

**Comment by geekosaur** [comment]
We're actually recommending a different way to configure status bars these days, since there's no way for us to catch and recover from the pipe-full hang (which I complain about to the ghc devs every so often). But you'll have to upgrade to xmonad 0.17 to use it.

**Comment by Scherso** [comment]
I’ll try compiling from source then, I think the Arch Linux’s package is not quite up to date.

**Comment by geekosaur** [comment]
When you do, you'll want to look at the new [tutorial](https://xmonad.org/TUTORIAL.html) or https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Hooks-StatusBar.html to see how the new stuff works.

**Comment by Scherso** [comment]
I followed that same tutorial on an older version, I can infer that my issue was a result of using an outdated version of Xmonad. I’ll upgrade my version, and change up my config to suit the new changes.

**Comment by geekosaur** [comment]
The tutorial has been completely reworked for 0.17 and should be easier to follow now. And the new StatusBar stuff is easier to use than the original. That said, your real problem currently is probably the lack of `StdinReader` in your `xmobar` config.

**Comment by Scherso** [comment]
Everything is fixed up, I didn't end up using `StdinReader`, I did, however, install xmonad from the AUR using `yay -S xmonad-git`, and from there, I followed your instructions,
> When you do, you'll want to look at the new [tutorial](https://xmonad.org/TUTORIAL.html) or https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Hooks-StatusBar.html to see how the new stuff works.

Thank you so much for the help, geekosaur. I really appreciate it.
