### ISSUE TITLE
Xmonad doesn't appear after logging in (Debian)

### ISSUE THREAD

**Issue by B9I4EveLiSA** [xmonad/xmonad#396]
### Problem Description

Xmonad doesn't appear after logging in. It is not a black screen like should to be! Even the login window doesn't disappear.
It is my first run xmonad, so I haven't any configuration file.
I already installed all needed packages like libghc-xmoand-dev, libghc-xmoand-contrib-dev, etc...

Need I install something else?

Thanks in advance

**Comment by slotThe** [comment]
If you're using a display manager, you may need a `.desktop` file as described [here](https://xmonad.org/INSTALL.html#make-xmonad-your-window-manager)

**Comment by B9I4EveLiSA** [comment]
Alright. Its helped me. Thanks for help!
