### ISSUE TITLE
Xmonad for CentOS

### ISSUE THREAD

**Issue by justrajdeep** [xmonad/xmonad#397]
Hi 

Is `xmonad` available for CentOS?

I was checking https://xmonad.org/download.html but could not find it.

**Comment by geekosaur** [comment]
It looks like EPEL hasn't been updated since xmonad 0.11. We're unaware of any other packages for RHEL or CentOS.

**Comment by slotThe** [comment]
On Wed, May 11 2022 06:38, justrajdeep wrote:
> Is `xmonad` available for CentOS?
>
> I was checking https://xmonad.org/download.html but could not find it.

Regardless of actual availability (it may well be, I haven't checked),
you can always install via stack, which will definitely give you the
newest version:

    https://xmonad.org/INSTALL.html
