### ISSUE TITLE
window border color incorrectly applied with windowNavigation

### ISSUE THREAD

**Issue by clemensschlipfinger** [xmonad/xmonad#398]
### Problem Description

The border color of the not focused windows is black, instead of the color in ```normalBorderColor``` when using windowNavigation.  

https://user-images.githubusercontent.com/71070584/171069515-c457906a-f7a9-4d27-b9b3-59e30e736bc9.mp4

This bug is introduced in dbe9c4f799fd826c199169d012c2d2687b210a7f. The version of ```xmoand-contrib``` is irrelevant.

### Steps to Reproduce

 - use xmonad build  which is not prior dbe9c4f799fd826c199169d012c2d2687b210a7f
 - use the configuration file

### Configuration File

```haskell
import XMonad
import XMonad.Layout.WindowNavigation 

main = xmonad def
        { 
              modMask = mod4Mask -- Use Super instead of Alt
            , terminal = "st"
            , normalBorderColor = "#ffffff"
            , borderWidth = 10
            , layoutHook = configurableNavigation noNavigateBorders ( Tall 1 (3/100) (1/2) )
        }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by geekosaur** [comment]
This is the same as #395.

**Comment by geekosaur** [comment]
https://github.com/xmonad/xmonad-contrib/pull/731
