### ISSUE TITLE
broken packages with Debian install from repo

### ISSUE THREAD

**Issue by ovitus** [xmonad/xmonad#399]
Hi,

I'm seeing broken packages trying to install xmonad on Debian 11 from the repository, I attached the apt output.

[apt_install_xmonad.txt](https://github.com/xmonad/xmonad/files/8873658/apt_install_xmonad.txt)

Kernel info:
Linux debian 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

Thanks,
Andrew

**Comment by geekosaur** [comment]
We don't have any say in how distributions handle their packages. You should file a Debian bug.
