### ISSUE TITLE
xmonad not in $PATH: /sbin:/bin:/usr/local/sbin:/usr/local/bin

### ISSUE THREAD

**Issue by codehia** [xmonad/xmonad#400]
### Problem Description

xmonad not in $PATH: on using `m-q`

### Steps to Reproduce

I installed xmonad on a fresh arch installation using https://xmonad.org/INSTALL.html. on restart when I use `m-q` I run into this issue. 

### Configuration File

Please include the smallest _full_ configuration file that reproduces
the problem you are experiencing:

```haskell
import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0.9
    - [x] With `xmonad-contrib`

**Comment by geekosaur** [comment]
Are you setting `$PATH`? `/usr/local/bin` and `/usr/local/sbin` wouldn't normally be there, and `/usr/bin` (which is where most of the system, including xmonad as installed via `pacman`) is missing.

**Comment by codehia** [comment]
I have set the `$PATH` to include `$HOME/.local/bin` in `.bashrc` file.
```sh
export PATH=$HOME/.local/bin:$PATH
```

**Comment by geekosaur** [comment]
Most systems other than Fedora don't read your `.bashrc` when starting the window system; you'll need to do it explicitly in your `.xinitrc` or use a wrapper script for xmonad which does so.

**Comment by geekosaur** [comment]
In particular, `.bashrc` is not read by noninteractive shells. As a hack, you could put it in `.bash_aliases` instead.

**Comment by codehia** [comment]
Sorry for the late response, I have raised this issue with the login manger I was using. xmonad works as expected with xinit and startx. Thank you @geekosaur for the prompt response and all the help
