### ISSUE TITLE
Left Alt not working as modMask but right Alt is. 

### ISSUE THREAD

**Issue by codehia** [xmonad/xmonad#408]
### Problem Description

The Left Alt is not working as the default ModMask while the right Alt key is, I am using xmonad on my laptop, where both the keys work as ModMasks. 

### Configuration File

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0.9
    - [x] With `xmonad-contrib` version 0.17.0

**Comment by slotThe** [comment]
> The Left Alt is not working as the default ModMask while the right Alt key is, I am using xmonad on my laptop, where both the keys work as ModMasks.

What does `xev` say?  I would be very surprised if something so fundamental suddenly stopped working all of a sudden.  More likely that your laptop is somehow sending the left Alt key as Alt_R or something.

**Comment by codehia** [comment]
@slotThe You're right, this is not an issue with xmonad, `xev` doesn't register the keypress at all, I am trying to figure out a way to enable the Alt_L. Any tips in this regard will be helpful. 
Thanks for the help.

**Comment by slotThe** [comment]
Thanks for getting back, I will close this as not xmonad related then.  Sadly, I have no idea what to do when even xev can't recognise the key (other than checking that it's not completely broken)
