### ISSUE TITLE
Prelude.chr: bad argument : 1157627962

### ISSUE THREAD

**Issue by etherbiswas** [xmonad/xmonad#411]
```
Stack has not been tested with GHC versions above 8.10, and using 9.0.2, this may fail
Stack has not been tested with Cabal versions above 3.2, but version 3.4.1.0 was found, this may fail
xmonad        > configure (lib + exe)
xmonad        > Configuring xmonad-0.17.0.9...
Prelude.chr: bad argument: 1157627962
Progress 1/2
```

Installation attempt:
. Debain Unstable/Sid (Same story with stable and testing)
. Xmonad-0.17
. Stack ( Using cabal throws a similar error)
. `$ ghc --verison` `The Glorious Glasgow Haskell Compilation System, version 9.0.2`
. [Config](https://github.com/etherrorcode404/xmonad)

**Comment by etherbiswas** [comment]
I dont think this has to do with my config, because the error persists with the sample config in the docs. It could be compatibility issue?

**Comment by geekosaur** [comment]
How is your ghc installed? (I presume ghcup, but I know sid is currently upgrading its ghc and dependencies and is currently, well, unstable.)

This error usually indicates an incompatible or out of date Haskell interface file somewhere. You may have to remove `dist-newstyle`.

**Comment by slotThe** [comment]
@etherrorcode404 any updates?
