### ISSUE TITLE
Unable to properly fullscreen Old School Runescape client

### ISSUE THREAD

**Issue by twiclo** [xmonad/xmonad#413]
### Problem Description

There is a custom OSRS client that fullscreens on cinnamon but not on xmonad. Even when ewmhFullscreen enabled

### Steps to Reproduce

1. Download client: https://vidyascape.org/downloads
2. `java -jar vidyascape.jar`
3. Create an email free account
4. Click gear in bottom right corner and hit fullscreen button

### Configuration File

```haskell
module Main (main) where

import XMonad
import XMonad.Hooks.EwmhDesktops

main :: IO ()
main = xmonad $ defaults
  & ewmhFullscreen
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0
    - [ ] With `xmonad-contrib` version XXX (commit XXX if using git)

**Comment by slotThe** [comment]
On Mon, Aug 15 2022 20:16, Tanner Wilcox wrote:
> 2. `java -jar vidyascape.jar`

Perhaps you need `X.U.Hacks.javaHack`?

-- 
Tony Zorman | https://tony-zorman.com/

**Comment by twiclo** [comment]
Just tried it out by setting the env variable that this sets and it works perfectly. Thank you.
