### ISSUE TITLE
Expose more functions in main module

### ISSUE THREAD

**Issue by czaplicki** [xmonad/xmonad#416]
Currently writing a custom launch function, where i want to replicate parts of the original behaviors of the functions `xmonad` and `launch` from the main module. But the following functions aren't exposed, making me re-implement each of them, even though they already exist. Any chans of adding them to the modules expose list?
* sendReset
* sendRestart
* buildLaunch

**Comment by slotThe** [comment]
This may be somewhat of an XY problem; why do you have to write your own custom launch function?

**Comment by czaplicki** [comment]
My goal is to unify the xmonad executable with xmonadctl from xmonad-contribs XMonad.Hooks.ServerMode with enhanced parsing of the command line args and output.

But after spending two days contemplating my XY problem,
I think the only infrastructure I'm missing is a way to specify the usage text printed by --help.
One solution would be to add a field to XConfig of type `String -> X String` or `XConfig l -> String -> String` used to process the usage text before printing it. As this would not only enable additions to the usage text but also reformatting of it (based on the current configuration).

I might have gone off topic for this issue. Should I close this one and open a new one?

ps. Thanks for pointing out it was an XY problem.

**Comment by czaplicki** [comment]
Have been fiddling around some more and to use the `handleExtraArgs` field of `XConf l` is not the solution. Because I need to handle the argument handling before `buildLaunch` is called, so I can send Client messages to the running instance of xmonad, just like `sendRestart` does.

So Tl:dr I’m back at square one. But the true issue is that I need more control over the parsing of the command line arguments. More specifically I need the ability to add documentation to the usage text and the ability to act on the the command line arguments earlier in the initialisation process. And preferably the ability to update  the `Directories` value, so I can add command line options to change those paths.

**Comment by slotThe** [comment]
I mean it's not like we [never expose internals](https://github.com/xmonad/xmonad/pull/405) ever and this sounds like a legitimate use-case.  @czaplicki is it still `sendReset`, `sendRestart`, and `buildLaunch` that you need?

**Comment by czaplicki** [comment]
These are the ones I'll need:
* `sendRestart`
* `sendReplace`
* `buildLaunch`
* `version`
* `compiledWithXinerama`

Though it would probably make more sense if all but `buildLaunch` were exposed through `XMonad.Core` and not `XMonad.Main`. `version` and `compiledWithXinerama` aren't strictly needed, but it would be great to be able to retain the `--verbose-version` flag's functionality.
