### ISSUE TITLE
"Authentication failed" in `pamac-manager`

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad#417]
I took this error in the Pamac manager:

![2022-09-01-133009_2560x1080_scrot](https://user-images.githubusercontent.com/112266845/187893804-3ae71f9b-5cc6-4f84-9243-a221c089ab45.png)

**Comment by slotThe** [comment]
You have to be a little bit more specific than that.  What exactly is the problem?  Are the assertion failures critical or does the program "normally" also generate them?  Does this work with another window manager or desktop environment?  Things like that.

(Authentication failed makes me think that this program requires dbus, or something).

**Comment by geekosaur** [comment]
How did you start xmonad, from startx or a display panager? Is dbus running so pamac-manager can reach the polkit service for authentication? (The warning about notifications suggests it isn't, but also that you need to install something like dunst to handle notifications; this by itself wouldn't cause the authentication error, though.)

**Comment by geekosaur** [comment]
@liskin has also noted in the past that he needed to start `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1` manually. This also needs to start in the context of a dbus session.

**Comment by slotThe** [comment]
@archlinuxlovers any updates?

**Comment by ghost** [comment]
Thanks for answers. I solved the problem. When I installed the lxsession or lxsession-gtk3 package the problem was solved. Thanks guys...

![2022-09-07-105214_2560x1080_scrot](https://user-images.githubusercontent.com/112266845/188821612-89aea109-b156-4938-8b48-0d557bf0abeb.png)
