### ISSUE TITLE
Anyone still working on XMonad?

### ISSUE THREAD

**Issue by ptrxyz** [xmonad/xmonad#43]
See subject, just curious...

**Comment by geekosaur** [comment]
What exactly were you looking for? The mindless "if it's not getting 20 commits a day, it's dead" so popular with a certain subset of (mostly Linux) users who apparently feel insecure if they aren't running the latest bugs?

xmonad core pretty much only changes if new ghc releases introduce incompatibilities. xmonad-contrib gets a bit more activity --- but xmonad is a niche within a niche; it's not going to get updated daily, there just aren't that many people interested in it.

**Comment by ptrxyz** [comment]
Well no. I was just curious if someone takes care of one of the ~20 open issues. I am just a simple user and the stuff I'd actually like to see fixed is beyond my Haskell skills so it would just be nice to know if it makes sense to wait for a fix and if there are actually people kindly dedicating time to them. ;)
I certainly do not expect a new release once a day, but some issues are just lingering around for so long now that one could easily wonder if they'll ever gonna be fixed.

**Comment by kurnevsky** [comment]
Since it is opened - question:
Do you have any plans for new release of X11 library and updating xmonad core for it? Without it I have to maintain my own version of xmonad-contrib because of annoying issue with UpdatePointer (https://github.com/xmonad/xmonad-contrib/pull/17)
