### ISSUE TITLE
Keys not intercepted when Hyper keybind defined

### ISSUE THREAD

**Issue by bradrn** [xmonad/xmonad#438]
### Problem Description

I have my mod key defined as `mod4Mask`, i.e. the left Windows key. Meanwhile, following the [instructions given on ArchWiki](https://wiki.archlinux.org/title/X_keyboard_extension#Caps_hjkl_as_vimlike_arrow_keys), I wanted to define my Hyper+hjkl keys to act as arrows (with my Hyper bound to the menu key and the right Windows key). However, once I did so, XMonad no longer intercepted the mod+hjkl keys — I can see in `xev` that they’re still processed as hjkl with the Mod4 flag set, but if XMonad processes the keys they shouldn’t be reaching `xev` in the first place.

### Steps to Reproduce

In your [XKB](https://wiki.archlinux.org/title/X_keyboard_extension) configuration file (generate with `xkbcomp $DISPLAY .Xkbmap`), make the following changes:

- Add a new `type` for the dual-function arrow keys in the `xkb_types`:
```
type "ALPHABETIC_ARROWS" {
    modifiers= Shift+Lock+Hyper;
    map[Shift]= Level2;
    map[Lock]= Level2;
    map[Hyper]= Level3;
    level_name[Level1]= "Base";
    level_name[Level2]= "Caps";
    level_name[Level3]= "Arrows";
};
```
- Replace existing alphabetic keys with keys of this type, e.g. for `h`:
```
key <AC06> {
    type= "ALPHABETIC_ARROWS",
    symbols[Group1]= [               h,               H,             Left ],
    actions[Group1]= [      NoAction(),      NoAction(), RedirectKey(keycode=<LEFT>, clearmods=Hyper) ]
};
```
- In the `modifier_map` declarations, move Hyper from Mod4 to Mod3 so it doesn’t conflict with the XMonad mod mask, and map some key to `Hyper_L`. (Not sure if this is strictly necessary for reproduction, but there’s not much point in doing the rest without this.)

Now Hyper+h should act like the left arrow key, but mod+h acts as if Mod4+h was inputted without XMonad.

### Configuration File

Minimal configuration exhibiting this problem:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
    { modMask = mod4Mask
    }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.1
    - [x] With `xmonad-contrib` version 0.17.1

**Comment by geekosaur** [comment]
Have you verified that `mod4` shows up correctly with `xmodmap -pm`? This is important because both `xmonad` and `xmodmap` use the pre-Xkb interfaces, and a mistake in configuring Xkb can result in a configuration incompatible with those interfaces.

**Comment by bradrn** [comment]
Just checked it now, and mod4 is listed correctly. Note that the problem doesn’t occur with all keys; just with the ones where I’ve also configured a mod3 binding. The relevant `xmodmap -pke` output looks like:

```
<snip>
keycode  43 = h H h H
keycode  44 = j J j J Down Down
keycode  45 = k K k K
keycode  46 = l L l L
<snip>
```

(Where to aid comparison I’ve set an arrow key binding for mod3+j but not anything else.)

**Comment by geekosaur** [comment]
Sorry for the delay, I've been somewhat ill and am still trying to figure this out.

I notice that on my system, `Hyper_L` is bound to `mod4` by default according to `xmodmap -pm`; this _shouldn't_ affect anything, since we're using the low level passive key grabbing interface, but conceivably might. Can you attach full `xmodmap -pm` and `xmodmap -pke` output so I can compare them?

**Comment by geekosaur** [comment]
Also, when I set `add mod3 = Hyper_L` and `keycode 44 = j J j J Right Right`, things continue to work. This suggests a possible problem with the Xkb definitions.

**Comment by bradrn** [comment]
```
~$ xmodmap -pm
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Alt_L (0xcc),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        Hyper_L (0x86),  ISO_Level5_Shift (0xcb),  Hyper_L (0xcf)
mod4        Super_L (0x85),  Super_L (0xce)
mod5        ISO_Level3_Shift (0x5c)

~$ xmodmap -pke
keycode   8 =
keycode   9 = Escape NoSymbol Escape
keycode  10 = 1 exclam 1 exclam
keycode  11 = 2 at 2 at
keycode  12 = 3 numbersign 3 numbersign
keycode  13 = 4 dollar 4 dollar
keycode  14 = 5 percent 5 percent
keycode  15 = 6 asciicircum 6 asciicircum
keycode  16 = 7 ampersand 7 ampersand
keycode  17 = 8 asterisk 8 asterisk
keycode  18 = 9 parenleft 9 parenleft
keycode  19 = 0 parenright 0 parenright
keycode  20 = minus underscore minus underscore
keycode  21 = equal plus equal plus
keycode  22 = BackSpace BackSpace BackSpace BackSpace
keycode  23 = Tab ISO_Left_Tab Tab ISO_Left_Tab
keycode  24 = q Q q Q
keycode  25 = w W w W
keycode  26 = e E e E
keycode  27 = r R r R
keycode  28 = t T t T
keycode  29 = y Y y Y
keycode  30 = u U u U
keycode  31 = i I i I
keycode  32 = o O o O
keycode  33 = p P p P
keycode  34 = bracketleft braceleft bracketleft braceleft
keycode  35 = bracketright braceright bracketright braceright
keycode  36 = Return NoSymbol Return
keycode  37 = Control_L NoSymbol Control_L
keycode  38 = a A a A
keycode  39 = s S s S
keycode  40 = d D d D
keycode  41 = f F f F
keycode  42 = g G g G
keycode  43 = h H h H
keycode  44 = j J j J
keycode  45 = k K k K
keycode  46 = l L l L
keycode  47 = semicolon colon semicolon colon
keycode  48 = apostrophe quotedbl apostrophe quotedbl
keycode  49 = grave asciitilde grave asciitilde
keycode  50 = Shift_L NoSymbol Shift_L
keycode  51 = backslash bar backslash bar
keycode  52 = z Z z Z
keycode  53 = x X x X
keycode  54 = c C c C
keycode  55 = v V v V
keycode  56 = b B b B
keycode  57 = n N n N
keycode  58 = m M m M
keycode  59 = comma less comma less
keycode  60 = period greater period greater
keycode  61 = slash question slash question
keycode  62 = Shift_R NoSymbol Shift_R
keycode  63 = KP_Multiply KP_Multiply KP_Multiply KP_Multiply KP_Multiply KP_Multiply XF86ClearGrab
keycode  64 = Alt_L Meta_L Alt_L Meta_L
keycode  65 = space NoSymbol space
keycode  66 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift
keycode  67 = F1 F1 F1 F1 F1 F1 XF86Switch_VT_1
keycode  68 = F2 F2 F2 F2 F2 F2 XF86Switch_VT_2
keycode  69 = F3 F3 F3 F3 F3 F3 XF86Switch_VT_3
keycode  70 = F4 F4 F4 F4 F4 F4 XF86Switch_VT_4
keycode  71 = F5 F5 F5 F5 F5 F5 XF86Switch_VT_5
keycode  72 = F6 F6 F6 F6 F6 F6 XF86Switch_VT_6
keycode  73 = F7 F7 F7 F7 F7 F7 XF86Switch_VT_7
keycode  74 = F8 F8 F8 F8 F8 F8 XF86Switch_VT_8
keycode  75 = F9 F9 F9 F9 F9 F9 XF86Switch_VT_9
keycode  76 = F10 F10 F10 F10 F10 F10 XF86Switch_VT_10
keycode  77 = Num_Lock NoSymbol Num_Lock
keycode  78 = Scroll_Lock NoSymbol Scroll_Lock
keycode  79 = KP_Home KP_7 KP_Home KP_7
keycode  80 = KP_Up KP_8 KP_Up KP_8
keycode  81 = KP_Prior KP_9 KP_Prior KP_9
keycode  82 = KP_Subtract KP_Subtract KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode
keycode  83 = KP_Left KP_4 KP_Left KP_4
keycode  84 = KP_Begin KP_5 KP_Begin KP_5
keycode  85 = KP_Right KP_6 KP_Right KP_6
keycode  86 = KP_Add KP_Add KP_Add KP_Add KP_Add KP_Add XF86Next_VMode
keycode  87 = KP_End KP_1 KP_End KP_1
keycode  88 = KP_Down KP_2 KP_Down KP_2
keycode  89 = KP_Next KP_3 KP_Next KP_3
keycode  90 = KP_Insert KP_0 KP_Insert KP_0
keycode  91 = KP_Delete KP_Decimal KP_Delete KP_Decimal
keycode  92 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift
keycode  93 =
keycode  94 = less greater less greater bar brokenbar bar
keycode  95 = F11 F11 F11 F11 F11 F11 XF86Switch_VT_11
keycode  96 = F12 F12 F12 F12 F12 F12 XF86Switch_VT_12
keycode  97 =
keycode  98 = Katakana NoSymbol Katakana
keycode  99 = Hiragana NoSymbol Hiragana
keycode 100 = Henkan_Mode NoSymbol Henkan_Mode
keycode 101 = Hiragana_Katakana NoSymbol Hiragana_Katakana
keycode 102 = Muhenkan NoSymbol Muhenkan
keycode 103 =
keycode 104 = KP_Enter NoSymbol KP_Enter
keycode 105 = Control_R NoSymbol Control_R
keycode 106 = KP_Divide KP_Divide KP_Divide KP_Divide KP_Divide KP_Divide XF86Ungrab
keycode 107 = Print Sys_Req Print Sys_Req
keycode 108 = Alt_R Meta_R Alt_R Meta_R
keycode 109 = Linefeed NoSymbol Linefeed
keycode 110 = Home NoSymbol Home
keycode 111 = Up NoSymbol Up
keycode 112 = Prior NoSymbol Prior
keycode 113 = Left NoSymbol Left
keycode 114 = Right NoSymbol Right
keycode 115 = End NoSymbol End
keycode 116 = Down NoSymbol Down
keycode 117 = Next NoSymbol Next
keycode 118 = Insert NoSymbol Insert
keycode 119 = Delete NoSymbol Delete
keycode 120 =
<after this point it’s all irrelevant, omitting for concision>
```

**Comment by bradrn** [comment]
Also, note that xmodmap predates XKB, and works according to somewhat simpler principles (at least according to the Arch Wiki, which is usually accurate). I wouldn’t expect modifications made with xmodmap to have the same effect as ones defined with XKB.

**Comment by geekosaur** [comment]
Yes, I mentioned that earlier, and that xmodmap uses the same earlier principles and API. I don't think there's a more modern passive key grab API, in particular.

Looking at your `xmodmap` output, I'm not seeing `Hyper_L` anywhere but the modifier map.

**Comment by bradrn** [comment]
> Looking at your xmodmap output, I'm not seeing Hyper_L anywhere but the modifier map.

Ah, yes… I forgot that I’m using a workaround for this issue: instead of binding the Hyper+hjkl key combinations directly using XKB, I can instead use [AutoKey](https://github.com/autokey/autokey) to trigger the arrow keys whenever I enter those key combinations. I’d much prefer to be able to use XKB, though. Give me a moment while I move back to the other XKB config.

**Comment by bradrn** [comment]
OK, this is weird… it seems to have suddenly started working. Closing this issue until I can reproduce it again.
