### ISSUE TITLE
[BUG] Mixed color with focused / unfocused borders

### ISSUE THREAD

**Issue by thealio** [xmonad/xmonad#442]
### Problem Description

Hi,
recently I noticed that xmonad mixed the colors of focused and and unfocused windows parameters. For example , with
```

myDefaults = def {
          normalBorderColor   = "white"
        , focusedBorderColor  = "red" 
```
Some unfocused window's borders are light pink instead of white. This cause problems to recognize the focused window.
I'm not using a compositor.
I expected that the colors of windows' borders matched the colors of my xmonad.hs file.

### Steps to Reproduce

Give detailed step-by-step instructions on how to reproduce the problem.

### Configuration File

My xmonad.hs is massive.
It's based on the default ArcoLinux settings.
The part related to the issue:

```
myDefaults = def {
          normalBorderColor   = "white"
        , focusedBorderColor  = "red"
        , focusFollowsMouse   = True
        , mouseBindings       = myMouseBindings
        , workspaces          = myWorkspaces
        , keys                = myKeys
        , modMask             = myModMask
        , borderWidth         = 3
        , layoutHook          = myLayoutHook
        , startupHook         = myStartupHook
        , manageHook          = myManageHook <+> namedScratchpadManageHook myScratchPads <+> floatNextHook
        , handleEventHook     = minimizeEventHook <+> swallowHook
        }
```

### Checklist

  - [ x ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [ x ] With `xmonad` version 0.17 (latest Arch Linux update)
    - [ x ] With `xmonad-contrib` version 0.17  (latest Arch Linux update)

![Screenshot-2023-03-18-1679173736_screenshot_1916x982](https://user-images.githubusercontent.com/116115143/226140780-f8c470d8-146f-4570-b01c-42fe0bc73080.jpg)

![Screenshot-2023-03-18-1679173813_screenshot_1916x982](https://user-images.githubusercontent.com/116115143/226140788-bb3aef4e-49d9-40b0-9a7c-b2dc0ae8dd47.jpg)

**Comment by liskin** [comment]
There's 0.17.1 in Arch that has a fix for this. What exact version are you running (`xmonad --version`)?

**Comment by geekosaur** [comment]
I think we'd need to see more of your `xmonad.hs`, but: are you using `WindowNavigation`? If so, then that's a feature to show which windows you can navigate to. Look at https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Layout-WindowNavigation.html#t:WNConfig for details.

(I don't think this is the bug @liskin is talking about; that produces black borders.)

**Comment by thealio** [comment]
> I think we'd need to see more of your `xmonad.hs`, but: are you using `WindowNavigation`? If so, then that's a feature to show which windows you can navigate to. Look at https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Layout-WindowNavigation.html#t:WNConfig for details.
> 
> (I don't think this is the bug @liskin is talking about; that produces black borders.)

Yes
it was the behaviour given by `WindowNavigation`
Sorry, my fault
I close the issue
Thank you so much
