### ISSUE TITLE
please make hackage release that's buildable with ghc-9.6.1

### ISSUE THREAD

**Issue by jwaldmann** [xmonad/xmonad#443]
Current hackage release is xmonad-0.17.1, and this can't be built with ghc-9.6.1, because some exports moved (from Prelude oder mtl to Control.Monad). This seems fixed on master, which currently is xmonad-0.17.1.9 (and can be used with `cabal install --allow-newer=base`).

**Comment by slotThe** [comment]
Releasing 0.17.2 for this sounds like a good idea, but I would like to get rid of the need for `--allow-newer=base` first.  I'm currently building 9.6.1 from source (which could take a while :) but as far as I can tell from a distance, `setlocale` seems to be a blocker; see https://gitlab.com/Kritzefitz/haskell-setlocale/-/issues/3

This also prevents the 9.6.1 haskell-ci workflow (related to
https://github.com/xmonad/xmonad-contrib/issues/805) from working at this point

**Comment by slotThe** [comment]
We have [0.17.2](https://hackage.haskell.org/package/xmonad) on Hackage now, closing this
