### ISSUE TITLE
Google Meet window sharing only lists windows from current desktop instead of all

### ISSUE THREAD

**Issue by shubham-cpp** [xmonad/xmonad#447]
### Problem Description
When I'm using Google meet and I select option to share a specific window then I only get options to select windows from current workspace.
Expected behaviour: Show windows from all workspaces.
This behaviour is present on awesome-wm where I get all the windows from all workspaces.

### Steps to Reproduce
1. Open a terminal/file browser on workspace 1
2. Open browser(any) on workspace 2
3. Open meet.google.com and present screen.
4. 
<details>

<summary>Select share a window option. </summary>

![image](https://user-images.githubusercontent.com/31388020/230109179-4db33620-cbb3-4dec-ac8e-a5769b8a0811.png)

</details>

Now this will only show option to share browser window(or any window only on workspace 2).

### Configuration File

Please include the smallest _full_ configuration file that reproduces
the problem you are experiencing:

```haskell
module Main (main) where

import XMonad

main :: IO ()
main = xmonad def
```

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version v0.17.1
    - [x] With `xmonad-contrib` version v0.17.1

**Comment by TheMC47** [comment]
Did you try enabling ewmh? It should solve the problem

**Comment by geekosaur** [comment]
More to the point, without ewmh's window list the only windows it can know about are on the current workspace.

**Comment by shubham-cpp** [comment]
Yes I do have that in my config

```haskell

main :: IO ()
main = do

  dbus <- D.connectSession
    -- Request access to the DBus name
  D.requestName dbus (D.busName_ "org.xmonad.Log")
      [D.nameAllowReplacement, D.nameReplaceExisting, D.nameDoNotQueue]
  xmonad $ docks . ewmhFullscreen . ewmh . pagerHints $ def

```

Full [xmonad.hs](https://github.com/shubham-cpp/dotfiles/blob/main/.config/xmonad/xmonad.hs)

**Comment by geekosaur** [comment]
I just tried it on my two-monitor setup and it only shows the visible windows. This makes me think it only accepts mapped windows, and we don't map windows on invisible workspaces.

**Comment by geekosaur** [comment]
I also think we've been through this before, possibly with Zoom. Lemme dig

**Comment by shubham-cpp** [comment]
> and we don't map windows on invisible workspaces.

So, this is not a bug rather difference in implementation.

Would it be possible if we can list all windows?
If no, we can close this since its implementation limitation by what I understand(I could be wrong)

**Comment by liskin** [comment]
Yeah we've talked about this before. GNOME moves windows off-screen, we unmap them.

**Comment by geekosaur** [comment]
Compositing also affects it; I'm looking at #195 in particular.

**Comment by shubham-cpp** [comment]
I'm using xcompmgr as my compositor. Killing it and restarting xmonad didn't change anything

**Comment by shubham-cpp** [comment]
@liskin is there a hook(like urgency hook,etc) which I can use to map windows which are in different workspaces or different monitors

**Comment by geekosaur** [comment]
I'd expect that to work the other way around, a compositor would keep an off-screen pixmap around that could be shared.

**Comment by geekosaur** [comment]
`XMonad.Operations.windows` controls which windows are mapped. Conceivably a `logHook` could forcibly map a window off-screen, but that might confuse xmonad's internals and you'd lose it every time `windows` ran.

**Comment by geekosaur** [comment]
We might also consider mapping stuff off-screen like GNOME does but that would be a core change which would need to be fairly well tested to make sure it didn't break anything.

**Comment by shubham-cpp** [comment]
Yes hence why I asked if we should close this if this is big one.

**Comment by slotThe** [comment]
Closing this as a duplicate of https://github.com/xmonad/xmonad/issues/412, which asks the same question/proposes the same change. I'm still not sure whether this is something that we want to do at some point. It will break X.L.Stoppable, but them I'm not sure anyone is even using that anyways at this point. 

@shubham-cpp for now perhaps you could try the workaround given in that issue?
