### ISSUE TITLE
Unable to install because of Prelude.chr: bad argument: 3959423081

### ISSUE THREAD

**Issue by yusi1** [xmonad/xmonad#448]
### Problem Description

I am trying to install xmonad & xmonad-contrib on Debian 11 through stack with these docs: https://xmonad.org/INSTALL.html but get this error `Prelude.chr: bad argument: 3959423081`.

### Steps to Reproduce

- Use Debian 11
- Follow the docs to install with stack.
- The error occurs.

### Full Error
```
Stack has not been tested with GHC versions above 8.10, and using 9.2.7, this may fail
Stack has not been tested with Cabal versions above 3.2, but version 3.6.3.0 was found, this may fail
xmonad-contrib> configure (lib)
xmonad-contrib> Configuring xmonad-contrib-0.17.1.9...
Prelude.chr: bad argument: 3959423081
```

**Comment by slotThe** [comment]
Related: #441 

Quoting @geekosaur: 

> How is your ghc installed? (I presume ghcup, but I know sid is currently upgrading its ghc and dependencies and is currently, well, unstable.)
> 
> This error usually indicates an incompatible or out of date Haskell interface file somewhere. You may have to remove `dist-newstyle`.

**Comment by yusi1** [comment]
Sorry but idk what `dist-newstyle` is or how to remove it, how would I go about removing it? Thanks.

EDIT: I installed GHC through stack.

**Comment by geekosaur** [comment]
When you do a build with `cabal` or `stack`, a folder `dist-newstyle` is created to hold the build plans and artifacts. Leftovers in that folder can cause weird errors if they come from different versions or even builds of `ghc`.

If you don't have a `dist-newstyle` folder then you may need to provide more information about what you are doing. It is possible that you need to remove `~/.stack-work` to clean up any garbage.

**Comment by yusi1** [comment]
I can't see a folder called `dist-newstyle` anywhere.
I'm trying to install XMonad with `stack` based on the docs, I just tried removing the `.stack-work` folder and doing `stack install` again in `~/.config/xmonad` but I get the same error.

FYI this is the first time I've tried to build XMonad on this system, so there wasn't any leftovers from any previous builds of XMonad. I installed stack through my distros package.

**Comment by geekosaur** [comment]
That sounds like something may be wrong with the ghc stack installed. You might try using ghcup to install one and set `system-ghc: True` in `stack.yaml`. If that works, you should file a bug against stack.

**Comment by yusi1** [comment]
> That sounds like something may be wrong with the ghc stack installed. You might try using ghcup to install one and set `system-ghc: True` in `stack.yaml`. If that works, you should file a bug against stack.

Yes that worked, I'll open a new bug in the stack repo. Thanks
