### ISSUE TITLE
Some VSTs (I think JUCE based ones? Or something) have broken popups that disappear upon hovering, and mouse clicks don't get registered.

### ISSUE THREAD

**Issue by Bracket-H** [xmonad/xmonad#451]
Here's a video.

https://user-images.githubusercontent.com/93729441/232254658-1f629106-1e6c-468e-8e89-89091461fb3d.mp4

And another one, definetely JUCE.
At the end, I hit enter to select the new patch.

https://user-images.githubusercontent.com/93729441/232254718-a56bce58-b353-435a-a15e-d0edc5ae2c70.mp4

Both are actual native linux VSTs.
In fluxbox, it all works.

I wondered if it's the lack of decoration, so I tried with a no frills deco, but that did not help.
I even updated from xmonad 15 to 17 to see if that changed anything, but it did not.

I use `import XMonad.Hooks.EwmhDesktops` but no real fancy config or anything, still not posting it cause:
it's still very personalized and I don't wanna pick it apart.

Do you even have VSTs to test this with? Well, I guess you could grab at least surge, that's gratis.

Anyway, there's also a chance that you know why this happens.

Oh, right, at 12 seconds in the second video, I actually click on `Artificial 1` with the mouse, but nothing happens, so I wiggle around the patch name in the VST to signify that, but I realize now that that is not too clear.

Mouse input does not work, hitting enter works if I hover over something, sometimes.
Sometimes keyboard input works, arrow keys etc, but seldomly.

And in the first example, it doesn't work at all, and the popups are also much more unstable in the first one. 
The second doesn't immediately close, but it does close eventually.

**Comment by hustin-paul** [comment]
This is happening with the Steam client as well with popups like the top header/title bar (Steam - View - Help - etc).

**Comment by hustin-paul** [comment]
> Oh yeah...been having trouble with the recent steam update, as well. Don't know what's at fault with that one, though. Probably Steam to be honest, but...can't be sure.
> 
> I doubt they make the UI bad on purpose, especially with their new EEE run on Linux/Proton/Steamdeck.

It's probably Steam, I made an [issue report](https://github.com/ValveSoftware/steam-for-linux/issues/9376) for it in beta but now it's in stable. 

It's seems to effect mostly XMonad and Openbox, so I'm wondering if XMonad devs can help Steam devs narrow down why it's happening?

I haven't tested another WM yet.

**Comment by liskin** [comment]
Hm, the latest stable Steam version works fine here. My manageHook is like this:
```
myManageHook :: ManageHook
myManageHook = composeAll
    [ isFullscreen --> doFullFloat
    , placeHook (fixed (0.5, 0.5))
    , floatNextHook
    , className =? "hl_linux" --> doFloat
    , className =? "duke3d" --> doFloat
    , className =? "cantata" --> doFloat
    , appName =? "alarm-clock-applet" --> doFloat
    , appName =? "blueman-manager" --> doFloat
    , appName =? "pavucontrol" --> doFloat
    , appName =? "peek" --> doFloat <> hasBorder False
    , "_NET_WM_WINDOW_TYPE" `isInProperty` "_KDE_NET_WM_WINDOW_TYPE_OVERRIDE" --> doIgnore <> doRaise
    , isDialog --> doFloat
    , transience'
    ]
```

There may be other bits of my config affecting this but seems a bit unlikely.

**Comment by liskin** [comment]
Started happening in my setup as well. Being finally able to reproduce it, I mostly figured this out, and will be submitting a PR to xmonad-contrib shortly.

**Comment by liskin** [comment]
Okay, here's the PR: https://github.com/xmonad/xmonad-contrib/pull/886
The menu fix should just work, but the workaround for Steam flickering/slowdowns needs a slight `xmonad.hs` modification.
Can affected folks please test this?

**Comment by geekosaur** [comment]
Taking shortcuts that are illegal but happen to work with most window managers.

**Comment by liskin** [comment]
> And wow, spooky how it 'happened to you' in the end...what is Steam doing? Slowly infecting things with jank? lol

I haven't used Steam on Linux in months, so quite likely it would have "happened to me" at the same time as it did to others. But I was dealing with other stuff in life, not focusing on xmonad and almost avoiding using my laptop (and the work laptop too, lol). And yeah Steam is just really abusing the X11/ICCCM/EWMH specs, and they've always been, just not as badly as of late.
