### ISSUE TITLE
Modal dialogs make xmonad's cpu usage spike up

### ISSUE THREAD

**Issue by jabuxas** [xmonad/xmonad#452]
### Problem Description

When program sends focus to a modal dialog, the root program has its borders flickering, xmonad cpu usage spikes up, focus follows mouse doesn't really work — I have to mod+m1 to get focus back to dialog.

### Steps to Reproduce

1. Open Prism Launcher app (needs to have a minecraft account)
2. Click to play offline, it will spawn a dialog asking for username.
3. Bug will happen

### Configuration File

```haskell
module Main (main) where

import XMonad
import XMonad.Hooks.EwmhDesktops

main :: IO ()
main = xmonad $ ewmh def
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` commit eeac754ac76dabf115deecb545e52a55f9dbbd02
    - [x] With `xmonad-contrib` commit 673de11ca876a4a58cae3a4d52e36260f66aa6cc
    
 
 Attached video demonstrating it: https://youtu.be/hlJFDnnAQP4

**Comment by slotThe** [comment]
What's a modal dialog? Also, this seems related to the game issues you are experiencing in #450; I propose taking this conversation over there (as I've also never heard of someone experiencing the same issues)

**Comment by geekosaur** [comment]
A modal dialog is one which blocks the main window while active. In this case, the main window sets focus back to the dialog when it receives focus, leading to a focus loop.

Modal dialogs are permitted but rare in the X11 world because they break the asynchronous model. They're more common on Windows which is why they're coming up with Wine games.

**Comment by jabuxas** [comment]
prism launcher specifically though isn't wine nor is minecraft. it is somewhat related to #450, but not really the same, since disabling ewmh fixes this one, while disabling fullscreenSupport and Hacks one fixes the other one.
