### ISSUE TITLE
Cite Conor's Zipper paper properly

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad#461]
### Problem Description

`XMonad.StackSet` mentions Conor McBride's zipper paper but doesn't provide a link to it or even its title ("The Derivative of a Regular Type is its Type of One-Hole Contexts"). Should we correct this, and if so which link should we use? I note that ResearchGate says one should request a copy directly from Conor, but it's also directly available via StrictlyPositive.org and other sites.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by slotThe** [comment]
I mean, `strictlypositive.org` *is* Conor's personal site, so linking to that seems to be the best option (not to mention that ResearchGate is a horrible middle-man that needs to be shunned at every oportunity :)

**Comment by geekosaur** [comment]
I wasn't suggesting to link them, just that they said "must get directly from author".

As to `strictlypositive.org`, I'd missed that that was Conor's site; I thought I'd seen a different one for his stuff. So sure, link it.
