### ISSUE TITLE
Uneven monitor hotplugging

### ISSUE THREAD

**Issue by llllvvuu** [xmonad/xmonad#47]
To reproduce (probably don't need the exact hardware, just the primary monitor at nonzero y offset):
1. Have setup with 1366x768 laptop monitor at (0,256) and 1280x1024 VGA monitor at (1366,0).
2. Have udev rule to run `xrandr --output VGA1 --off` when monitor is disconnected and `xrandr --output LVDS1 --auto --pos "0x256" --output VGA1 --auto --pos "1366x0"` when monitor is connected.
3. Start with monitor plugged in. Spawn and close some windows.
4. Unplug monitor. Spawn and close some windows.

Expected behavior: Windows spawn at (0,256) (filling the laptop screen) when monitor is plugged in, and (0,0) (filling the laptop screen) when monitor is unplugged.

Observed behavior: Windows spawn at (0,256) (filling the laptop screen) when monitor is plugged in, and (0,256) (leaving the top 256 rows blank) when monitor is unplugged. Persists until `xmonad --restart`.

**Comment by pjones** [comment]
@llwu What happens if you reset the layout?

**Comment by pjones** [comment]
@llwu Since you are the person who reported this issue I really need to know if resetting your layout fixes the issue.  We also need a volunteer who can reproduce this issue and then track down the cause.

**Comment by colonelpanic8** [comment]
I can actually reproduce this, but it seems to be a new development (started happening somewhat recently). I'm pretty sure that this did not happen with .12

**Comment by llllvvuu** [comment]
I no longer have this set up. If no one else can cover for me then I will attempt a repro this weekend.

**Comment by liskin** [comment]
Can anyone still reproduce this?

**Comment by slotThe** [comment]
I can't, at least.  Closing for now, feel free to reopen with more information (and a reproducer, if possible!)
