### ISSUE TITLE
Recent env var changes were omitted from the changelog

### ISSUE THREAD

**Issue by LSLeary** [xmonad/xmonad#471]
### Problem Description

The `XMONAD_GHC` and `XMONAD_XMESSAGE` env vars should be listed in the changelog, and probably documented in the man page too.

These changes were introduced in 0.17.1, so the release and its successor both have incomplete changelogs hosted (immutably?) on hackage—I'm not sure what steps should be taken to rectify this.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

**Comment by geekosaur** [comment]
Technically, release 0.17.1.1. Practically, I'm not sure it matters enough.

**Comment by slotThe** [comment]
AFAIR this was discussed on IRC at one point, and we came to the conclusion that these NixOS-specific hacks are probably not worth documenting for the general population (if anyone disagrees then feel free to open a PR and we can discuss this again)
