### ISSUE TITLE
Multiple mouse cursors works buggy

### ISSUE THREAD

**Issue by unclechu** [xmonad/xmonad#49]
When I try to add additional cursor in xmonad-session additional cursor is always blinking and in _Firefox_ input fields I can type only at least 2 chars and no one more, rest of the keys just ignored. I tried it in _Openbox_ and there it works fine, so I guess this is _XMonad_ issue.

How I create additional cursor:

``` bash
xinput list # and find id of my additional mouse (for example 15)
xinput create-master foo
xinput list # and find id of master 'foo' (for example 20)
xinput reattach 15 20 # attach additional mouse to new master
```

``` bash
$ uname -a
Linux unclefarm23 4.7.5-100.fc23.x86_64 #1 SMP Mon Sep 26 19:29:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

``` bash
$ cat /etc/fedora-release 
Fedora release 23 (Twenty Three)
```

**Comment by pjones** [comment]
@unclechu Could this be related to focus-follows-mouse?

Please include your xmonad configuration so we can help.

**Comment by unclechu** [comment]
@pjones I'm not sure, but in my case this feature is disabled, window get focus by mouse only when I click on it.

Here is [my config](https://github.com/unclechu/xmonadrc/tree/71ba05435bf66540d9b910429e32eb5ebd0bd535/project).

**Comment by pjones** [comment]
@unclechu Let's start this again.

I'm not familiar with using `xinput create-master` and `xinput reattach`.  Would you explain your motivation for multiple mouse cursors, and what you are expecting xmonad to do with them.

I'm not convinced this has anything to do with xmonad but maybe you can explain it to me.  Thanks.
