### ISSUE TITLE
xdotool with --window <window_id> not working?

### ISSUE THREAD

**Issue by cortsf** [xmonad/xmonad#510]
### Problem Description
Not sure if this is a problem with xmonad, I'm just trying to figure out why calling xdotool with the `--window` option doesn't seem to work as it used to be on 2022 and early 2023. Now it does nothing, not even an error. Can you check so we can figure if the problem is related to xmonad? Thanks!

xmonad version: 0.17.2
xdotool version: 3.20211022.1

### Steps to Reproduce
1. Open terminal A and B
2. In terminal A call xdotool as in code block below
3. Click on terminal B
4. Check state of terminal B

``` bash
xdotool key --window $(xdotool selectwindow) a
```

**Comment by geekosaur** [comment]
This usually means the application that owns the window ignores events with the `send_event` flag set. For xterm, you can change this on the control-left click menu ("Allow SendEvents") and set the default behavior in `~/.Xresources`; see the xterm manpage for details. You'll have to check the terminal you're using to find out how it deals with `send_event`s and whether it's configurable.  See the `SENDEVENT NOTES` section of the `xdotool` manpage.

**Comment by geekosaur** [comment]
I should add that xmonad has no involvement and no knowledge of what xdotool is doing; xdotool is sending events directly to the selected window.

**Comment by cortsf** [comment]
Indeed, it works with xterm by calling it with `xterm -xrm '*allowSendEvents:true'`. The problem might be with the terminal I use. Thank you!

**Comment by cortsf** [comment]
Closing as completed
