### ISSUE TITLE
Decoration broken by transparency

### ISSUE THREAD

**Issue by Pitometsu** [xmonad/xmonad#6]
With [compton](https://github.com/chjj/compton/issues/172) window decoration broken (gray frame around) by transparency
![transparent](http://i.imgur.com/peuIEoF.png)
![opaque](http://i.imgur.com/D19I4OH.png)

**Comment by Pitometsu** [comment]
[Similar issue](https://github.com/chjj/compton/issues/240#issuecomment-62245919)

**Comment by bb010g** [comment]
This would be fixed by #9.

**Comment by pjones** [comment]
Will be fixed by #59 soon.  Closing this issue as a duplicate.
