### ISSUE TITLE
Tabbed decoration broken with LayoutBuilder

### ISSUE THREAD

**Issue by bmjoan** [xmonad/xmonad#67]
When any of `XMonad.Layout.Tabbed` layouts used in `layoutN`, `layoutAll`, … from `XMonad.Layout.LayoutBuilder`, it would introduce various graphics artifacts present on all workspaces.

For example, with following layout

```
wmii = (layoutN 1 (relBox 0 0 ratio 1) Nothing stabbed) $
            (layoutAll (relBox ratio 0 1 1) stabbed)
        stabbed = tabbedAlways shrinkText defaultTheme
        ratio   = 61/100
```

if you start add clients like 3 or more xterms, content of tab bars starts get garbled. Window names out of position or quite missing, bar from 1st workspace visible on all other workspaces, missing fragments in border around tabs  etc.

Tabbed layouts works well on the same machine, either standalone or combined with different combinators like Combo, DragPane, TwoPane, Master and others. Issue is only in combination with LayoutBuilder.

**Comment by pjones** [comment]
@bmjoan I've seen this issue too but thought it was a problem with the tabbed layout and not LayoutBuilder.

I'm happy take a look at this but please open a issue for the `xmonad-contrib` repository since this isn't related to `xmonad`.  Thanks.

**Comment by bmjoan** [comment]
Oh, this definitely belongs to xmonad-contrib.

I'm sorry for any inconvenience.
