### ISSUE TITLE
XDG compatibility

### ISSUE THREAD

**Issue by zabbal** [xmonad/xmonad#7]
Right now settings and binaries are stored in ~/.xmonad/
It would be great if XDG specification is respected and ~/.config/xmonad/ is used instead. Other generated files (like xmonad.hi) could go to $XDG_CACHE_HOME/xmonad/
See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html for the reference.

**Comment by Delapouite** [comment]
This move has been done by neovim recently. Glad to see this initiative being more widespread.

**Comment by zabbal** [comment]
Note: there's been some patches circulating in https://code.google.com/p/xmonad/issues/detail?id=484 but their current whereabouts is unknown.

**Comment by pjones** [comment]
If someone wants to submit a PR I'd be happy to review it.

And changes should definitely prefer to use `~/.xmonad` if it exists, otherwise it could use the XDG layout.  That would allow for backwards compatibility.

**Comment by zsedem** [comment]
I submitted a pull request on this 
#26

**Comment by pjones** [comment]
This is related to #53 and #54.  Once those issues are resolved I think something like this could be moved into xmonad-contrib.

**Comment by pjones** [comment]
Fixed in #62
