### ISSUE TITLE
default should NOT be to prefer pseudo-XDG

### ISSUE THREAD

**Issue by geekosaur** [xmonad/xmonad#71]
We just had someone get burned by the obvious: if you've ever run *any* XDG-ish program, your existing xmonad config will be ignored after https://github.com/xmonad/xmonad/commit/40fc10b6a5682ce1d6ba7f0679962926ef6cfade. Check `~/.xmonad` first.

**Comment by geekosaur** [comment]
To be specific:

> [16 21:08:46] <troydm> hey all! so I cloned latest xmonad version from repo and installed it and I'm trying to configure but I'm puzzled as I put my xmonad.hs into ~/.xmonad directory but somehow xmonad is looking for it in ~/.config/xmonad directory instead

This should not happen.

@liskin thinks the code should not be doing this. I have not looked because I've had about 6 hours of sleep in the past 72 hours.

**Comment by liskin** [comment]
So we narrowed it down to this:

> 23:19:27 < troydm> Liskni_si: I've tried running xmonad while in KDE desktop, and it tried to compile my 
                   ~/.xmonad/xmonad.hs but since it had errors it created a compilation log in 
                   ~/.config/xmonad/something-something.log

solutions:

> 23:18:51 < dmwit> Perhaps looking for a directory rather than a file is not such great behavior.
> 23:19:02 < geekosaur> probably it should not just check for the directory, but for xmonad.hs in it

**Comment by pjones** [comment]
I'll look into this.

**Comment by geekosaur** [comment]
FWIW, ongy on irc is working on a proper XDG implementation (they already have a local hack for it that needs to be cleaned up and bulletproofed).

> [16 22:22:03] <ongy> I use -outdir $XDG_CACHE_DIR and binary into $XDG_DATA_HOME, so there should be no generated files there
> [16 22:22:35] <ongy> cache into subdir, not quite sure if I default ot subdir with the binary (I check for it and move into it if it exists)
> [16 22:22:37] <geekosaur> wow, doing it correctly. which pretty much every attempt to patch "XDG" into xmonad has refused to do
> [16 22:23:27] * geekosaur does wonder if -hidir does the right thing if pointed at $XDG_CACHE_DIR/xmonad, but probably it does or cabal/stack would have the problem he's envisioning
> [16 22:23:42] <ongy> https://github.com/Ongy/monky/blob/xdg-dirs/bin/Xdg.hs not sure if it's correctly (which is why I haven't merged it yet)
> [16 22:24:56] <ongy> -hidir? I found -outputdir recently, doesn't that combine -odir and -hidir which should both go into a cache?
> [16 22:25:41] <geekosaur> probably, I think -outputdir is newer and I last checked those options in ghc 6.6
> [16 22:25:54] <ongy> ah
> [16 22:26:05] <ongy> I found it when I made the xdg patch, made it a bit nicer
> [16 22:30:25] <ongy> I still have to think a bit about how to handle sytem-dir configs. I'd use them for my setup, same config for multiple users. But writing into system-path binarys will fail
> [16 22:34:24] <geekosaur> with proper XDG you put them in $XDG_CACHE_DIR. it would be reasonable to require XDG for that usage since it can't break existing configs (since system-dir configs aren't currently a thing)
> [16 22:34:32] <geekosaur> not that I am sure they make sense with xmonad
> [16 22:35:39] <ongy> about as much as with monky. I just want them so I have a common config if I multi-user my setup for something
> [16 22:35:58] <geekosaur> the bigger problem is hybrid setups, perhaps. that is, /etc/xmonad/lib /usr/lib/xmonad/lib and user config dir/lib all exist, do you merge them or ignore all but one, and what order or which one?
> [16 22:36:09] <ongy> I put them into XDG_DATA_DIR, made more sense than cache to me
[16 22:36:37] <geekosaur> the .hi, .o, and executable can all be recreated at need from xmonad.hs, so they are cache
> [16 22:39:19] <ongy> https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html says the difference is "non-essential", but ephermeral may make sense aswell...

**Comment by pjones** [comment]
BTW, the way the code is now, if `~/.config/xmonad` doesn't exist then `~/.xmonad` will be used.  The only way it will ever create `~/.config/xmonad` is if `~/.xmonad` doesn't exist.

Any solution is going to have to work with an existing `~/.xmonad` if it exists, otherwise use the XDG Base Directory Specification.  It sounds like the current implementation has a bug.  I'd rather fix that bug than toss it out and replace it with a different implementation that might have other bugs.

**Comment by geekosaur** [comment]
On Mon, Jan 16, 2017 at 11:12 PM, Peter J. Jones <notifications@github.com>
wrote:

> BTW, the way the code is now, if ~/.config/xmonad doesn't exist then
> ~/.xmonad will be used. The only way it will ever create ~/.config/xmonad
> is if ~/.xmonad doesn't exist.
>

Check the log. The user had a compile error with their ~/.xmonad/xmonad.hs
that got logged to ~/.config/xmonad/something.log, apparently creating
~/.config/xmonad in the process; thereafter xmonad did not find their
config because it started looking for ~/.config/xmonad/xmonad.hs.


-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by pjones** [comment]
Which I would consider a bug that we should fix.

**Comment by pjones** [comment]
I couldn't reproduce this issue.  That said, I changed the code anyways.  `~/.xmonad` comes before XDG BDS now.

**Comment by Narthorn** [comment]
I've been bitten by the opposite issue: After copying my `~/.xmonad` setup to XDG base dir `~/.config/xmonad` and removing `~/.xmonad`, I reloaded xmonad once. This worked at first, but on the second reload, this error showed up:

```
Error detected while loading xmonad configuration file: /home/narthorn/.xmonad/xmonad.hs

<no location info>: error: can't find file: xmonad.hs

Please check the file for errors.
```

Apparently on first reload, an `~/.xmonad` dir was created containing `xmonad-x86_64-linux`, `xmonad.errors` and `xmonad.state`. Subsequent reloads found that directory and searched for the config file there instead of in the XDG dir.

Deleting `~/.xmonad` again and manually creating a `.local/share/xmonad` directory fixed it.
