### ISSUE TITLE
Provide a working xmonad+stack project template

### ISSUE THREAD

**Issue by colonelpanic8** [xmonad/xmonad#72]
Now that #62 has been merged, it is possible to configure xmonad so that stack is used whenever the users configuration is compiled.

I think it might be helpful to provide a working .xmonad directory that recompiles xmonad using stack. The main things it would contain would be the build script to configure xmonad to recompile with stack and the stack.yaml file. It might also be worth it to include a sample .cabal file.

I doubt that this repository is the correct place to have someting like this, but it would be simple enough to add a repository to the xmonad repo for this purpose, right?

**Comment by pjones** [comment]
I think we are trying to consolidate things like this into the `xmonad-testing` repository.  That way people can easily play around with a configuration without committing to it.

**Comment by Hrothen** [comment]
I see a couple problems.
1. No one is going to go looking for a sample config in a testing repo, so discoverability is not great.
2. Conceptually a testing repo is a weird place to keep sample code.
3. There is not in fact any such example in `xmonad-testing` currently, nor are there instructions for setting one up. There *is* a PR open for a sample config, but that one doesn't use `stack`, `launch`, or `build`.

**Comment by pjones** [comment]
@Hrothen 

> discoverability is not great.

After the release it will be in the FAQ and the README

> There is not in fact any such example

Please add one and send a PR ;)

**Comment by Hrothen** [comment]
@pjones 

> Please add one and send a PR ;)

I can't, trying to find out how the new features are supposed to support recompiling with stack is how I ended up finding this issue.

**Comment by pjones** [comment]
@Hrothen: Ah, I understand now.  I'll do my best to create something this week or next.

**Comment by pjones** [comment]
Announcements and documentation updates are forthcoming.  For now, I updated the README file in the xmonad-testing repo with instructions on how to use a build script.

https://github.com/xmonad/xmonad-testing

**Comment by hallettj** [comment]
I see that this is closed - but I wanted to mention that I created a [stack project template](https://raw.githubusercontent.com/hallettj/dot-xmonad/master/home/.xmonad/xmonad.hsfiles), and a [blog post](https://sitr.us/2018/05/13/build-xmonad-with-stack.html) that explains how to use it.
