### ISSUE TITLE
Maintainer and Release Documentation

### ISSUE THREAD

**Issue by pjones** [xmonad/xmonad#75]
As previously recommended by @geekosaur, we need a way to keep track of all the accounts and details associated with the XMonad project.  I'm going to build a list of questions that we need to answer.  I think the best place to keep this information would be in a `MAINTAINERS.md` file in this repository.

  * [x] How does a new maintainer get added to Hackage?
  * [x] What are the steps for updating the xmonad.org website?
  * [x] Who owns/runs the xmonad Twitter account?
  * [x] What are the steps for releasing xmonad?
  * [x] OpenPGP keys for the maintainers
  * [x] Contact details for the maintainers, email, github, IRC, Twitter, etc.

@xmonad/core please help me build and answer these questions.  Thank you.

**Comment by aavogt** [comment]
Hackage Maintainer: see http://hackage.haskell.org/package/xmonad/maintain

Website: I believe pushing to xmonad-web repo is all that needs to be done. @davidlazar set it up

Twitter: dons gave me the password

PGP: I don't have one but it seems easy enough to figure out

Release: see https://github.com/xmonad/xmonad/blob/master/TODO . It could be more detailed (`git tag ... ; cabal sdist; cabal upload dist/xmonad-...`; `/msg nickserv ???` `/topic #xmonad ....` )

Contact: vogt . adam @ gmail .com. aavogt/enthropy on freenode but I'm not on much lately

**Comment by geekosaur** [comment]
`/msg chanserv topic #xmonad ....` assuming you are authed with nickserv and have the requisite channel access level. (see `/msg chanserv access #xmonad list`)

**Comment by pjones** [comment]
To close this ticket someone needs to finish this file:

https://github.com/xmonad/xmonad/blob/master/MAINTAINERS.md

It still needs information about where all the parts of xmonad live (web, wiki, etc.), how add someone to hackage, how to add someone to IRC, how to add someone to GitHub, etc.

**Comment by dmwit** [comment]
* Adding someone to Hackage: visit http://hackage.haskell.org/package/xmonad/maintainers/ for a list of people authorized to give permissions to the xmonad package. There is an \[edit\] link there to add more folks. Similarly for the other packages (xmonad-contrib, xmonad-extras, X11, X11-xft).
* Adding someone to IRC: `/msg chanserv access add #xmonad <nick> +ARefiorstv`
* Adding someone to github: add them to an appropriate team, and check that the repo of interest gives that team write access (github docs themselves should have details on each of those steps if they need to be fleshed out further...)

**Comment by dmwit** [comment]
(I've just made sure each repo gives the "Core" team admin access. I admit I'm not 100% sure I understand how teams and access control works here at github -- e.g. why did I have permissions to hand out admin access? I don't know, I certainly wasn't listed in the "Teams and collaborators" section of any of those repos.)

**Comment by liskin** [comment]
https://github.com/xmonad/xmonad/pull/308 ticks the "How does a new maintainer get added to Hackage?" (anyone already there can add anyone else and with the release automation this often isn't even necessary) and "What are the steps for releasing xmonad?" boxes.
