### ISSUE TITLE
Close not working with Skypeforlinux

### ISSUE THREAD

**Issue by dschrempf** [xmonad/xmonad#82]
### Problem Description

Closing or quitting skypeforlinux beta with a shortcut does not work.  I am not familiar with the intrinsics of skypeforlinux but I think that it runs in some kind of sandbox.  I think that this problem is generic for those kind of sandboxes.  Quitting with CTRL-Q works.

Edit: It could also be a consequence of skypeforlinux being executed with `nohup` here on my Arch machine.

**Comment by pjones** [comment]
Are you saying that closing the window with the XMonad `kill` action doesn't actually close the application?  If so, that's really a bug in the application, not XMonad.

**Comment by dschrempf** [comment]
Yes, that's what I am saying.  I will report the problem at Arch AUR first but I expect this is a problem upstream.
