### ISSUE TITLE
spawn not starting interactive process

### ISSUE THREAD

**Issue by rmanne** [xmonad/xmonad#84]
### Problem Description

Problem: spawn is for some reason not working on interactive processes (such as slop, and I remember this happening with scrot's selection mode as well though I don't use it anymore)
Reproduce: use the below configuration. Try `spawn "slop"`, prepare for nothing to happen.
Then, try to `spawn` with the wrapper, as you can see, the prompt shows up.
Now, in the shell script, remove or comment out the sleep. Try to `spawn` with the wrapper again. Prepare for nothing to happen.
The same [lack of thing] happens even if you decrease the sleep amount (eg: `sleep 0.01`)

For slop, this only started happening recently (within the last week), but then again, I've only been using slop for about 2 months. For scrot's selection mode this used to happen quite often, not sure why. I'm not sure if this is a bug with xmonad or X11 or slop. It's seemingly impossible to debug because spawn doesn't throw any errors either (catch appears to do nothing).

Note, this is also a problem with runProcessWithInput (which presumably works the same way as spawn).

### Configuration File

Minimal configuration (it's VERY minimal, as you can see, it hardly has any key bindings).

my `slopwrapper` file
```bash
#!/bin/bash
sleep 0.1
slop
```

```haskell
import XMonad
import qualified Data.Map as Map

slop = spawn "slop"
wrappedSlop = spawn "/rmanne/.bin/slopwrapper"

myKeys conf@(XConfig { XMonad.modMask = modm }) = Map.fromList $
    [ ((modm              , xK_d), slop)
    , ((modm .|. shiftMask, xK_d), wrappedSlop)
    ]

main = xmonad def { terminal = "urxvtc", keys = myKeys }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment]
Use `XMonad.Util.Ungrab.unGrab` in the key action. This is necessary because dropping the grab before running the action would cause submaps (multiple-key actions) to behave erratically, with some keypresses going to the focused window instead.

Possibly a note about this needs to be added to the documentation for `spawn`.

**Comment by rmanne** [comment]
So that did not actually do the trick for me, but it seems to be a bug in `slop 5.3.28`. After updating to the current git version, it stopped happening (maybe it's less aggressive with grabbing?).

But it makes complete sense WHY it would fix the problem (especially for scrot). Thanks!
