### ISSUE TITLE
Serialized state is persistent after reboot

### ISSUE THREAD

**Issue by MichielDerhaeg** [xmonad/xmonad#86]
Because the state of xmonad is now serialized to a file, my xmonad breaks sometimes because it found the serialized state from the previous session and i end up having to remove the file and restart xmonad.

Maybe it's a good idea to remove the statefile after it has been read?
Or put it somewhere like /run/user/$(id -u) or /tmp?

**Comment by pjones** [comment]
Please elaborate.  What do you mean by "my xmonad breaks"?

**Comment by MichielDerhaeg** [comment]
XMonad.Util.SpawnOnce from xmonad-contrib stores the commands you spawned in an ExtensionClass, so they don't get started again when you restart xmonad. One of the things i start this way is urxvtd, so my terminals don't work.

**Comment by geekosaur** [comment]
On Tue, Feb 28, 2017 at 10:40 AM, Michiel Derhaeg <notifications@github.com>
wrote:

> Maybe it's a good idea to remove the statefile after it has been read?
> Or put it somewhere like /run/user/$(id -u) or /tmp?
>

Those aren't good enough if you log out and back in (say, to complete an OS
update that replaced things run as part of your session like a terminal).
Remove after read is correct.

**Comment by geekosaur** [comment]
This also would explain the recent reports about default workspaces hanging
around, btw. Also potentially some of the recent strut issues to some
extent.

On Tue, Feb 28, 2017 at 1:28 PM, Brandon Allbery <allbery.b@gmail.com>
wrote:

>
> On Tue, Feb 28, 2017 at 10:40 AM, Michiel Derhaeg <
> notifications@github.com> wrote:
>
>> Maybe it's a good idea to remove the statefile after it has been read?
>> Or put it somewhere like /run/user/$(id -u) or /tmp?
>>
>
> Those aren't good enough if you log out and back in (say, to complete an
> OS update that replaced things run as part of your session like a
> terminal). Remove after read is correct.
>
>


-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by MichielDerhaeg** [comment]
I have two suggestions, i dont know which one is cleaner.

http://derhaeg.be/file/deletefile.patch
http://derhaeg.be/file/deletefile2.patch

**Comment by geekosaur** [comment]
Actually, on thinking about it I realized that even delete after read has some edge cases (exec failed, computer crashed at the wrong time, etc.) The state file should contain some kind of session unique cookie. Session managers would give you one... but we don't want to depend on a DE's session manager. (hostname, login time) tuple would be better... but I don't recall offhand if there's a binding to the C getutx* functions that doesn't require an added dependency, and these can be hard to get right portably (everyone's version has its own extensions and edge cases) so we probably do not want to maintain one.

**Comment by liskin** [comment]
Couldn't you just generate a random cookie and pass it to the exec'd xmonad via command line or env?

**Comment by geekosaur** [comment]
Unclear. We're already cheating in a way stack could easily break in the future (it is a reproducible builds tool, and I can think of several future changes to enhance reproducibility which could cause our current restart stuff to break).

**Comment by colonelpanic8** [comment]
@geekosaur @liskin instead of a random cookie why not just hash the state file?

**Comment by liskin** [comment]
@IvanMalison That could work, too.

(Personally I don't care about stack in the slightest. xmonad is a library for building WMs and it's my responsibility to (re)build my WM with it. xmonad must not rewrite any binaries at runtime.)

**Comment by colonelpanic8** [comment]
I think this issue needs to be fixed now. I just restarted my computer and when I rebooted I had a different number of screens plugged in, but xmonad still had two screen because that was what was in the state file. I had to log out, delete the state file without logging in to xmonad (the only wm i have on my machine) and log back in to fix it.

**Comment by chrissound** [comment]
I've run into some issues with this myself:
(solution was to delete the `.xmonad/xmonad.state`)
https://github.com/xmonad/xmonad-contrib/issues/152

**Comment by pkel** [comment]
> I think this issue needs to be fixed now. I just restarted my computer and when I rebooted I had a different number of screens plugged in, but xmonad still had two screen because that was what was in the state file. I had to log out, delete the state file without logging in to xmonad (the only wm i have on my machine) and log back in to fix it.

I can confirm this. It happens everytime I do a mobile bootup after shutdown in docking station with monitors attached. Workaround is to delete `xmonad.state` in .xinitrc as proposed by IvanMalison. With only one wm installed it is a very painful issue. Identifing the problem without gui and any knowledge of recent changes is tough.

**Comment by pjones** [comment]
I'll have a fix for this later in the week.  Thanks everyone for reporting and suggesting workarounds.

**Comment by pjones** [comment]
This has been fixed by #91 

I've been testing it all day long and it seems solid to me.  If anyone gets a chance to test it please let me know what the outcome was.  Thanks.

**Comment by chrissound** [comment]
This fixed https://github.com/xmonad/xmonad-contrib/issues/152 for me.

**Comment by geekosaur** [comment]
So, it occurs to me the right way to do this with 100% reliability is to pass an open-but-unlinked file by file descriptor to the next xmonad instance. You do need to make sure FD_CLOEXEC is not set on the file descriptor, but otherwise the file goes away as soon as it is closed. At worst one could "leak" it by using the restart protocol with something that doesn't understand it, but (a) the restart option will probably make it exit immediately anyway (b) at worst the fd stays open until that program exits and then the unused restart state gets reaped.
