### ISSUE TITLE
Focus does not follow when moving between workspaces

### ISSUE THREAD

**Issue by Javran** [xmonad/xmonad#87]
### Problem Description

Dual monitor, when moving mouse from one workspace to another, but without moving into any window, the focus doesn't follow as I expected.

I believe the bug is introduced by https://github.com/xmonad/xmonad/commit/3a140badf52a7ce5676a3dc240265be136593f9c

### Configuration File

Default configuration should be sufficient to reproduce this bug.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] ~~I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~

**Comment by geekosaur** [comment]
You should in fact test this with a default config and no additional programs (specifically, no desktop window like a file manager). X11 has a screw case here, where it is impossible for clients to notice that something changed if focus is on a desktop window and you switch workspaces such that the mouse is still in the desktop window.

**Comment by Javran** [comment]
@geekosaur this bug can be reproduced even without having any window - simply moving between empty workspaces won't change the focus either.

hopefully there's an easy fix and I'm working on it.

**Comment by Javran** [comment]
update: finally got another monitor to test my fix, not working as expected. so I still need help on this.

**Comment by hicolour** [comment]
@Javran I have the same issue - in xmonad  <0.13 I was working perfectly fine.

The result is that even if I'm using  using independent  ```import XMonad.Layout.IndependentScreens```  (in two screens setup) only single workspace is used and to have something on 2nd screen I need to move it using mouse.

**Comment by Javran** [comment]
@hicolour #88 should have fixed the problem, you can have a try and let me know if that fixes the issue for you.

**Comment by hicolour** [comment]
This issue was solved by removing ```xmonad.state``` , as @pjones  said for #90, this one also can be then another side effect of xmonad/xmonad#86.

**Comment by pjones** [comment]
Closing as duplicate.
