### ISSUE TITLE
Workspace/window size reduced to smallest screen size

### ISSUE THREAD

**Issue by hicolour** [xmonad/xmonad#90]
### Problem Description

Issue was not present in xmonad < 0.13

Workspace/windows size is reduced to the smallest screen size.

In my configuration 
 * 2 x screens 2560x1440
 * 1 x laptop screen 1920x1080 - **DISABLED** 
 
So in my case when I'm opening new app its size is limited to 1920x1080 

### Configuration File

This issue  is not configuration specific

![screen_2017-03-10-22-47-07](https://cloud.githubusercontent.com/assets/619794/23815253/a79217b0-05e7-11e7-82c6-796055e7f4cb.png)

**Comment by zaidan** [comment]
Since Arch Linux update to xmonad 0.13 I have the same issue with equal screen setup. It is not possible to tile windows on other screens, they all snap to the first screen with limited size. It is possible to drag windows to other screens and resize them with the mouse, but tiling does not work. It is not possible to set the workspace on those screens. The xmobar fills the complete width of the first screen. When I turn off the 1920x1080 laptop screen with `xrandr --off`, it is possible to use the complete area of both screens for tiling and I can switch the workspace for both 2560x1440 screens.

**Comment by pjones** [comment]
Please post the output of `xrandr`. 

@hicolour Are you also using Arch?

**Comment by hicolour** [comment]
@pjones yes Arch

**Comment by pjones** [comment]
Okay, please post the output of `xrandr`.  I also wonder if the `X11` library was compiled with missing dependencies.

I suspect that this will ultimately have to be reported downstream to Arch as the bug may be there.

**Comment by geekosaur** [comment]
This isn't the usual "not linked with xinerama" issue, as that would lead to it treating all screens as one huge monitor. I'd kinda like to see what `getCleanedScreenInfo` has to say, since it sounds like xmonad has been told by the xorg video driver that the other screens don't exist.

**Comment by zaidan** [comment]
```shell
Screen 0: minimum 8 x 8, current 7040 x 1440, maximum 16384 x 16384
DP-0.1 connected 2560x1440+2560+0 (normal left inverted right x axis y axis) 708mm x 399mm
   2560x1440     59.95*+  69.93  
   1920x1200     59.88  
   1920x1080     60.00    59.94    50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-0.2 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 708mm x 399mm
   2560x1440     59.95*+  69.93  
   1920x1200     59.88  
   1920x1080     60.00    59.94    50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected primary 1920x1080+5120+0 (normal left inverted right x axis y axis) 382mm x 215mm
   3840x2160     60.00*+
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
DP-6 disconnected (normal left inverted right x axis y axis)
```

**Comment by zaidan** [comment]
```shell
$ ghc -e "Graphics.X11.openDisplay [] >>= XMonad.Operations.getCleanedScreenInfo"
[Rectangle {rect_x = 5120, rect_y = 0, rect_width = 1920, rect_height = 1080},Rectangle {rect_x = 2560, rect_y = 0, rect_width = 2560, rect_height = 1440},Rectangle {rect_x = 0, rect_y = 0, rect_width = 2560, rect_height = 1440}]
```

**Comment by geekosaur** [comment]
Actually it just occurred to me that this might be another effect of the leaking `xmonad.state` file, if xmonad was initially run without the additional screens attached (or they were disabled). That would make the observed behavior make a lot more sense.

**Comment by geekosaur** [comment]
@zaidan and @hicolour, you could test if it's the `xmonad.state` issue by seeing if the problem goes away with mod-shift-space to force layout recalculation.

**Comment by zaidan** [comment]
Thx, removing `xmonad.state` file solved the issue for me.

**Comment by pjones** [comment]
Well, then this is another side effect of xmonad/xmonad#86 then.

I'm going to close this as a duplicate so I can focus on the real issue.  Thanks for reporting.

**Comment by hicolour** [comment]
Confirmed removed ```xmonad.state``` solved the issue.
