### ISSUE TITLE
xmonad needs volunteers!

### ISSUE THREAD

**Issue by pjones** [xmonad/xmonad#93]
## Volunteers Wanted!

We're going to be working on release 0.14.  Bug fixes, features, docs, etc.

## How You Can Help

Welcome everyone!  And thank you for being willing to help xmonad.  There's plenty of work for everyone of all skill levels.  I'm going to break this issue into sections based on what you might help with depending on how comfortable you are with Haskell and/or xmonad.

By volunteering you are donating your time to the project.  That means you get to decide what you want to work on.  I'm not going to presume I know what you are interested in and therefore I'm expecting everyone to choose their own work depending on how and when you want to contribute.

If at any time you need any help just let me know.  You can tag me in an issue or contact me using the details in the "I Want to Learn Haskell" section.

Please read the [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md) guide before you write any code.  Thank you.

### Open Issues: Pick Your Own Adventure

The majority of the open issues have been labeled to help you pick something to work on.  Some of the issues even have a skill label (e.g., [3.skill: good-first-bug](https://github.com/xmonad/xmonad/labels/3.skill%3A%20good-first-bug)).

Please keep in mind that there are three repositories of interest and each one might have something interesting to you:

  * [xmonad](https://github.com/xmonad/xmonad/issues) -- The core repository

  * [xmonad-contrib](https://github.com/xmonad/xmonad-contrib/issues)  -- Where most issues are

  * [X11](https://github.com/xmonad/X11/issues) -- Bindings to X11

Pick an issue and then read the section below on "What to Do".

### Interesting Issues for Those Who Want Guidance

There are a couple of issues that I think are (somewhat) interesting and not terribly difficult.  Pick an issue and then read the section below on "What to Do".

  * [Good starter issues](https://github.com/xmonad/xmonad-contrib/issues?q=is%3Aopen+is%3Aissue+label%3A%223.skill%3A+good-first-bug%22)

  * [Improve X11 API](https://github.com/xmonad/X11/issues/51) -- No X11 experience needed!

### No Haskell Required

Here are some issues that don't require any Haskell skills.  Pick an issue and then read the section below on "What to Do".

  * [Documentation issues for xmonad](https://github.com/xmonad/xmonad/issues?q=is%3Aopen+is%3Aissue+label%3A%226.topic%3A+documentation%22)

  * [Documentation issues for xmonad-contrib](https://github.com/xmonad/xmonad-contrib/issues?q=is%3Aopen+is%3Aissue+label%3A%226.topic%3A+documentation%22)

### Hey! I Want to Learn Haskell and Help xmonad!

In exchange for donating your time, I'm willing to help mentor you and build your Haskell skills.  A few catches apply though:

  * I don't have time to teach you how to program

  * You are going to do most of the work

  * If you are willing to work hard and teach yourself Haskell I will help in every way that I can

  * No, you cannot come live with me.  However, if you are near Phoenix, San Francisco, or Seattle there may be a chance we can work face-to-face for a small amount of time (I travel for work).  (And yes, I have a quirky since of humor.)

If you find yourself in this category of people then reach out to me publicly or privately and tell me:

  * Who you are

  * What experience you have with Haskell so far

  * Any thoughts you have on helping the project

There are several ways to get in contact with me.  Pick the one that works best for you:

  * Email: You can find my address [here](https://github.com/pjones)

  * IRC: I'm on `chat.freenode.net` in `#xmonad` as `pmade`

  * Twitter: I'm [contextualdev](https://twitter.com/contextualdev)

  * Reddit: I'm [pmade](https://www.reddit.com/user/pmade/)

  * LinkedIn: [pmade](https://www.linkedin.com/in/pmade/)

If you want to start working on something interesting you can always do that and then reach out when you need help or guidance.

## What to Do

When you find something you want to work on:

Add a comment to the issue expressing your interest to work on it.  Include any questions you need to have answered before you begin.  (It's quite okay and even encouraged to continue adding comments to an issue as your work progresses.  The core team will automatically be notified when a new comment is added to any issue.)  When you pick an issue, one of the core members will assign it to you and change its status to "work-in-progress".

Some things to consider

  * Consider picking an issue that has the `v0.14` milestone set on it.  Of course, this isn't a requirement.

  * Try to keep the tips mentioned in [CONTRIBUTING.md](https://github.com/xmonad/xmonad-contrib/issues) in the back of your mind.

Actually making changes is exactly like any other project on GitHub:

  1. Fork the repo.

  2. In your fork, create a branch where you will commit your changes.

  3. When you are ready to share your work, rebase on master, squash your commits, and create a pull request.  (Rebase what?  Squash what?  See the [contributing](https://github.com/xmonad/xmonad-contrib/issues) guide!)

You may find it convenient to clone and work out of the [xmonad-testing](https://github.com/xmonad/xmonad-testing) repository since it has additional instructions and scripts for testing xmonad in a dedicated window.

**Comment by tippenein** [comment]
:+1:

**Comment by davama** [comment]
Me too

**Comment by colonelpanic8** [comment]
I'm in, but what am I volunteering for?

**Comment by simonyangme** [comment]
I am!

**Comment by byorgey** [comment]
As always, I will attempt to be intermittently helpful!

**Comment by geekosaur** [comment]
Likewise, health permitting. ( :/ )

**Comment by zoran119** [comment]
👍

**Comment by colonelpanic8** [comment]
Is there a list of things that need to be worked on for 0.14 somewhere?

**Comment by kniren** [comment]
👍

**Comment by cfricke** [comment]
👍

**Comment by erthalion** [comment]
:+1:

**Comment by aij** [comment]
What did I just sign up for?

**Comment by MichielDerhaeg** [comment]
Very willing to help.

**Comment by mcallisterjp** [comment]
:+1:

**Comment by balajirrao** [comment]
Count me in!

**Comment by atbd** [comment]
Willing to help if I can

**Comment by pjones** [comment]
Thanks everyone for showing up to help!  I'm so happy to see so many people want to help push xmonad towards the next release and beyond.

Today I'm going to process all the open issues and PRs.  I want to set up a labeling system like [what NixOS uses](https://github.com/nixos/nixpkgs/issues), i.e. labels that not only describe severity but also what needs to be done and how difficult the work might be.  After I finish I'll update this issue and those of you who want to jump right in can pick an issue and get started.

I'm also willing to mentor those who want some extra help with Haskell or figuring out how things work in xmonad.  We can do this over IRC, email, or whatever works best for you.

@byorgey and @geekosaur, I think where we can bring the most value is reviewing/merging PRs and helping volunteers by answering questions.

Stay tuned everyone!

**Comment by vaibhavsagar** [comment]
Me please!

**Comment by bendo** [comment]
:+1:

**Comment by katychuang** [comment]
Me me me! 
*to help with any ticket assignments to me: I'm still learning haskell, have a UX design background*

**Comment by jlarkbylahet** [comment]
:+1:

**Comment by wolfwood** [comment]
:+1: I've only written small projects in Haskell but I'm a longtime XMonad user and interested in contributing

**Comment by odi** [comment]
:+1:

**Comment by denibertovic** [comment]
Me.

**Comment by yury-pachin** [comment]
+1

**Comment by pjones** [comment]
It's so good to see everyone here willing to help!

Please come back to this issue, https://github.com/xmonad/xmonad/issues/93 and read the description.  I've updated it with details on how you can help out.

Please don't hesitate to contact me if you need any help or have any questions.

Thanks so much everyone!  And happy coding!

**Comment by pjones** [comment]
Everyone should have received a GitHub invitation to join the xmonad volunteers team.  Accepting the invitation will allow you to assign yourself to an issue.

**Comment by igorcavalcante** [comment]
Wow, im in!

**Comment by kpbochenek** [comment]
count me in too :)

**Comment by deech** [comment]
I'm in.

**Comment by Pascal-So** [comment]
I'm in :)

**Comment by pjones** [comment]
Hello everyone!

I thought that I would remind everyone that I'm here to help if you need it.  All of the issues are tagged to help you figure out what you want to work on.  But if that doesn't work for you then get touch with me and share any suggestions that you have.

Thanks.

**Comment by wisn** [comment]
@pjones I've a background on Web Development and I'm (technically) newcomer in Haskell. I'm glad to help xmonad. Maybe I can help.

**Comment by crocket** [comment]
@pjones I submitted a pull request to xmonad-testing upon your request, so I count as a volunteer. Yet, another maintainer assumes my patches are toxic by default until I'm proven. This clearly contradicts your call for new volunteers. I feel repelled and frustrated, especially since you **explicitly** requested my change. The pull request only changes a few lines, and it wouldn't be that hard to revert it or fix it if an unforeseen problem arises in other machines. The pull request was not going to break any production system, either. What happens is maintainers are hostile and suspicious to new contributors by default instead of mentoring new contributors into creating good patches. I was even accused of trying to take over xmonad for expressing somewhat naive(I admit) expectations in anger(I admit that I was unneccesarily angry).

I could easily become your new wanted volunteer who cleans up documentation, submits patches, and fixes issues for free. But, clearly, xmonad maintainers don't seem ready to accept new volunteers for the foreseeable future. At this point, if things don't change and I wanted to affect XMonad in any meaningful way, I'd seriously consider forking, renaming, and tacking [C4](https://rfc.zeromq.org/spec:42/C4/)(which is my favorite development process so far) to it.

If you really want to recruit volunteers, you should minimize friction in the process of getting a patch accepted. The friction is so expensive at this moment that many individuals can't afford to contribute to xmonad.

You're probably not ready to accept [optimistic merging policy](http://hintjens.com/blog:106), but I'm dropping it here for reference.

**Comment by pjones** [comment]
(My apologies to everyone for this off-topic reply.  I intend to lock this issue to prevent further off-topic comments, but I'm happy to continue to discuss this elsewhere.)

@crocket, I realized that you are frustrated and I would like to explain a few things.  I should be clear that I speak for myself and not for the xmonad core team.

While xmonad might be a niche window manager, it's an important project.  It's one of the flagship Haskell applications that gets pointed out every time someone asks "What real-world programs are written in Haskell?"

The number of xmonad users greatly exceeds the number of people working on the project.  We hear pretty quickly if a bug has been introduced into the project (or even when a downstream package maintainer makes a mistake).

For all these reasons we don't have the necessary resources to accept patches and then review them later and still maintain a quality product.  For this project, that kind of process would lead to a bit of chaos.  That said, the project is picking up steam and I feel like we're doing a better job of responding to issues and pull requests.

Personally, I think doing reviews before merges is better for the project.  It helps the contributors understand what the core team is expecting in the future and opens up discussion to the community on proposed features and changes.  It's far from a perfect system, but it's what we can afford given our constraints.

As far as your pull request goes, I made a mistake about what the correct solution should be.  I reviewed your issue and proposed changes too quickly while traveling for work.  Any frustration you have is completely my fault and I alone bear responsibility.  I will continue to work with you on that particular PR until your patches are ready to merge.  Please accept my apology.

In the end, we are all working on xmonad for the fun of it.  As far as I'm aware, no one is getting paid to work on xmonad.  As a contractor, I actually *lose* money when I work on the project.  But it's something that I greatly value and enjoy.  So, it might take us time to respond to an issue here, or a PR there.  That said, the project is moving forward thanks to everyone who is willing to donate their time and energy.

Thank you everyone!

**Comment by slotThe** [comment]
It might be nice to remake this post at some point (I'll remind myself to put it down for 0.17.1 or 0.18.0 somewhere), but for now I'll close this since the OP is not active in the project anymore and hence half of the opening post doesn't apply anymore
