### ISSUE TITLE
Adopt some style guidelines

### ISSUE THREAD

**Issue by colonelpanic8** [xmonad/xmonad#96]
The haskell style that is used xmonad and contrib seems to vary wildely from module to module. Take a look, for example, at a few different module statements. Some modules align the exported names with the opening parenthesis, some use 2 spaces, others use 4. I think it would be nice to set some style guidelines and slowly try to remove some of the inconsistency in xmonad's source code.

**Comment by colonelpanic8** [comment]
@pjones This seems particularly relevant since you are soliciting help from new contributors in #93

**Comment by colonelpanic8** [comment]
I think it would be nice to choose a set of standards that https://github.com/commercialhaskell/hindent provides.

This would allow us to make existing modules conform quite easily.

**Comment by pjones** [comment]
I'm not a huge fan of style guides, but I understand the need for them.  My vote would be the de facto standard "Johan Tibell" style with the ability to deviate if there's good reason.

**Comment by liskin** [comment]
Do we still think this is worth doing?

**Comment by TheMC47** [comment]
It might be worth it if there's a big influx of pull requests and we need to triage which ones to prioritize (it's not really fun manually commenting on style). This hasn't been an issue during the (brief) time I looked at pull requests here

**Comment by slotThe** [comment]
On Mon, Jul 26 2021 08:58, Yecine Megdiche wrote:
> It might be worth it if there's a big influx of pull requests and we
> need to triage which ones to prioritize (it's not really fun manually
> commenting on style). This hasn't been an issue during the (brief)
> time I looked at pull requests here

Yeah, I don't think this is that much of an issue either.  Especially
since, when contributing to existing modules, "local" style consistency
is much more important than "global" consistency at this point.  It
would perhaps be a different story if all modules had the same style
but, alas, that's not the case.

**Comment by liskin** [comment]
Let's close it then.
